### PR TITLE
Cocoapods preparation

### PR DESCRIPTION
**Pull request by ray-kraesig**
Clean up a little, to make the life of anyone testing experimental branches a little easier.

### CODE REVIEW

**Comment by gnprice** [comment]
Looks good, thanks! Two small nits:

* The tool's name is "CocoaPods", capitalized the same way as "GitHub" (and unlike "Dropbox" :wink: .) This applies to the commit messages, and the gitignore comment.

* For the first commit's summary line, I like the prefix `ios build:`. Generally the Android build and the iOS build (and the small amount of other build stuff) are very widely separated parts of the codebase from each other and have quite different flavors, so the distinction between them is a high-order bit that I like having in the prefix when scanning a commit log.

**Comment by ray-kraesig** [comment]
Done!

**Comment by gnprice** [comment]
Thanks!

Merged, with two small tweaks:
* fixed the name's capitalization in the gitignore comment
* s/under git control/under source control/ in the gitignore commit message, because the former doesn't really parse for me.

**Comment by gnprice** [comment]
Also fixed this PR's title -- just to minimize the number of places that might contribute to putting the wrong capitalization in people's heads :slightly_smiling_face:

**Pull request merged**
