### PR TITLE
Messages Refactor and Tests

### PR DESCRIPTION
**Pull request by borisyankov**
Main goals:
* Simplify message rendering and structure to enable the more advanced grouping, timestamp displays, etc.
* Add more tests to ensure changes did not break anything. Now the coverage of important code is rather high.
* Remove Immutable.js - I determined first that it does not impact the messages (the main concern) then I removed it from everywhere else. Now code is simpler, more 'native' and Flow can better track types.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
Thanks @borisyankov. This is a large PR so give me a little time to review it

**Comment by borisyankov** [comment]
To fix 'accounts.map is not a function.' uncomment the AsyncStorage.clear(); line in storage.js for a single run. Since no immutable is used, the stored data format is different.

I created another commit in another branch with eslint spellcheck rules and fixes.

**Comment by neerajwahi** [comment]
Thanks @borisyankov will take another look

**Comment by neerajwahi** [comment]
Looks good overall. Some quick notes:
- I get this warning when logging in: `subscriptions.find is not a function`
- Looks like tests are failing
- Why change 'stream' to 'chat'? I agree that 'stream' can be a little confusing but I'm not sure 'chat' is better

**Comment by borisyankov** [comment]
I found and fixed `subscriptions.find is not a function` in a subsequent commit.

I am using `message list` to mean the actual messages and `chat` to refer to a bigger picture combination of things that refer to what is current narrow etc. If we think of something better we can rename later?

**Comment by timabbott** [comment]
In case this is helpful, in the web UI, we use these names:
* message_store: Raw metadata store for messages
* message_list: the message list data structure, which includes details like what the current narrow is.  I think message_list.items is the actual messages in the message_list object.
* message_list_view: the additional structure with view rendering details, e.g. data about which messages should be displayed with a sender or recipient heading.

**Pull request merged**
