### PR TITLE
docs: Advise upgrading to latest versions for setup.

### PR DESCRIPTION
**Pull request by jackrzhang**
All issues / errors that I ran into during my setup were resolved by upgrading Yarn, Node, and XCode.

### CODE REVIEW

**Comment by borisyankov** [comment]
I think we need to add this as a separate sentence, summarizing that generally having the latest versions of these tools will avoid problems. In this, we should also include 'latest MacOS' version, as the latest XCode usually depend on it.

**Comment by gnprice** [comment]
Thanks @jackrzhang for these notes!

I just merged the Yarn and Xcode commits, with a couple of tweaks:
* I added the recommendation for latest macOS, as Boris mentioned and I recall you mentioning you had to do for the latest Xcode
* I tweaked the Yarn recommendation to "latest stable" rather than "latest 1.x" -- those mean the same right now, when they diverge in the future we probably mean "latest stable", and the install page we link to identifies the "stable" version right at the top so that instruction should be as clear as any.

I'm curious about your change to the Node line. In particular I'm not actually sure what version I would install if following that instruction. :smile: The [Node downloads page](https://nodejs.org/en/download/) doesn't identify a version as "stable", but it has an "LTS", which is 8.x, and a "Current", which is 10.x (and IIRC was 9.x when I was setting things up myself a few months ago.)

Did you have trouble on 8.x that was resolved on 10.x? I wrote 8.x because that's what I decided to install, based on upstream (on that downloads page) saying it's "Recommended For Most Users". But if 10.x worked better for you, maybe we should recommend that instead.

**Comment by jackrzhang** [comment]
@gnprice I've just resolved some merge conflicts, and this PR has automatically closed. I used Node 9.6.1 when I was setting up - it didn't seem to be the cause of any issues 😄

**Comment by borisyankov** [comment]
BTW, as a default we should recommend the `LTS`.
I personally use `Current` when playing with Node development, but for example `jest` was broken for a week after the initial release of `10.0`.

**Comment by jackrzhang** [comment]
@borisyankov I've rebased and updated the `developer-guide` to recommend Node LTS.

**Comment by gnprice** [comment]
> I used Node 9.6.1 when I was setting up - it didn't seem to be the cause of any issues :smile:

Got it -- thanks for the details!

I do think we want to keep saying "8.x" in the doc because that's the info that's actionable when following the instructions on the page we link to; but I've just pushed a small commit that hopefully makes the context clearer.

**Comment by gnprice** [comment]
Closing because I think that accounts for everything that was in this PR, but of course please open a new PR for any further notes you'd like to add to the guide :smiley:

**Pull request closed without merging**
