### PR TITLE
Show "followed topic" icon in several places

### LINKED ISSUE #5770: Show which topics are followed
In the web app, we indicate followed topics with a dedicated icon (see [here](https://chat.zulip.org/#narrow/stream/101-design/topic/followed.20topic.20left.20sidebar/near/1647200)).

We should also indicate followed topics with an icon in the mobile app, in the Inbox view (probably the most useful placement), as well as the app bar in topic views and topic header bars.

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #5770.

For the design in the inbox screen and the recipient headers, we use the current web design as a reference. For the app bar it's a bit more arbitrary.

### Screenshots

| inbox | app bar | recipient header |
| --- | --- | --- |
| image | image | image |

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Hmm, looks like some CI failures. (Commenting because I'm not sure if you get a notification when CI fails.)

**Comment by gnprice** [comment]
Indeed, thanks — I don't. Will fix.

**Comment by gnprice** [comment]
Pushed a change which should fix that.

**Comment by gnprice** [comment]
@alya @terpimost for feedback on the UI; see screenshots above.

Anything complex, let's save for the Flutter app where we'll be much more able to control things to be just how we want them. But size, padding, opacity, color are all just numbers and are easy to adjust from this draft's values to any other values.

**Comment by alya** [comment]
I would maybe reduce opacity in the app bar, but very happy to defer to @terpimost on any tweaks here.

**Comment by chrisbobbe** [comment]
Looks like still some CI failures, in message-list snapshot tests.

**Comment by gnprice** [comment]
> Looks like still some CI failures, in message-list snapshot tests.

Hmmm indeed. Now why wasn't that failing for me locally…

… aha, it's because it's in the same test file where I have unrelated breakage:
```
Summary of all failing tests
 FAIL  src/webview/__tests__/generateInboundEventEditSequence-test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: performance

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:20:20)


Test Suites: 1 failed, 67 passed, 68 total
Tests:       1 skipped, 2114 passed, 2115 total
```

(I think it may have been induced by a Node upgrade?) and I've gotten used to ignoring that. A parable, I guess.

(That issue only started sometime after we stopped focusing on this codebase, which is why I didn't promptly prioritize clearing it up.)

Anyway, will fix.

**Comment by gnprice** [comment]
OK, revision pushed. This includes a couple of new commits at the start to fix that other issue I was seeing locally.

**Comment by gnprice** [comment]
Just pushed another revision that fixes the last commit (the one about recipient headers) so that it properly updates if you follow or unfollow a topic.

(The lack of such an update is a glitch one's unlikely to notice as a user as of the tip of this PR, but starts becoming noticeable with #5771, if you try following/unfollowing a topic from the long-press menu on a recipient header itself.)

**Comment by chrisbobbe** [comment]
Thanks! LGTM; looks like it's just pending a decision on some opacity: https://github.com/zulip/zulip-mobile/pull/5793#issuecomment-1813921076

**Comment by gnprice** [comment]
OK, I've cranked down that opacity to 0.4. Here's an update of the screenshot:
image

Happy to tweak further, either now or after merging.

**Comment by alya** [comment]
Looks fine to me! It's probably reasonable to merge, and make any tweaks as a follow-up when @terpimost has time to provide feedback.

**Pull request merged**
