### PR TITLE
Switch to community async-storage module

### PR DESCRIPTION
**Pull request by ray-kraesig**
... and eliminate the angry red message from our build logs.

### CODE REVIEW

**Comment by ray-kraesig** [comment]
The test failure here appears to be due to the Jest harness reading the unprocessed Flow code in the referenced file as plain JavaScript – which is more than a little surprising, as the build process itself has no problem with it.

**Comment by ray-kraesig** [comment]
This looks like a simple Jest configuration issue, but resolving that yields further problems which are less trivial to satisfy.

Withdrawing until we have some solution for, or at least better characterization of, the issue of `flow-typed` ignoring type definition files outside of `flow-typed/npm` in favor of those within.

**Comment by ray-kraesig** [comment]
> Withdrawing until we have some solution for, or at least better characterization of, the issue of `flow-typed` ignoring type definition files outside of `flow-typed/npm` in favor of those within.

Well... we don't really have that. But do we have a list started in `.flowconfig`, and that'll probably do for now.

**Comment by gnprice** [comment]
SGTM; merged!

**Comment by gnprice** [comment]
(For the sake of GitHub cross-referencing: this fixed #3570.)

**Pull request merged**
