### PR TITLE
Grouped notifications into one and show the notifications as a list

### PR DESCRIPTION
**Pull request by kunall17**
This is expanding notifications not complete yet.
Wanted some suggestions if this can be made better 

Expanded:
screen shot 2017-06-24 at 10 44 03 am

Default view:  (the latest message is shown here) What would be the most appropriate content text here? 
screen shot 2017-06-24 at 10 45 42 am

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Updated 
screen shot 2017-06-24 at 11 44 01 pm

**Comment by borisyankov** [comment]
'New 4 messages' should be '4 new messages'.

If the message does not fit anyways, we should just say 'N new messages' without the 'from N conversations'.

Do we even want to group them though? How does it work in Slack & FB Messenger?

**Comment by kunall17** [comment]
Without grouping right now we are replacing the old notifications, hence loosing content 
Slack and whatsapp both group messages in a similar way

**Comment by kunall17** [comment]
Fixed and added a commit to show the number of messages in the home screen 
This is dependent on different launchers, library I used is popular and works well on my sony phone

screenshot_20170625-145406

**Comment by borisyankov** [comment]
Looks good to merge. Please rebase.

**Comment by kunall17** [comment]
Updated

**Comment by borisyankov** [comment]
Great. Thanks.

**Pull request merged**
