### PR TITLE
Add steps to run app on iOS device without dev vm

### PR DESCRIPTION
**Pull request by arpith**
These are the basic steps required when running the app for the first time. This will be helpful to new contributors trying out the app, and makes it clear that it is a straightforward process.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@arpith, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
Written like this, I think it is a bit confusing.

There are two aspects:
* running inside an iOS Simulator vs running on a physical device
* logging in to a dev installation of the server vs logging in to a production server

One is not connected to the other in any way.

The easiest way to run it actually is to run in iOS Simulator and connect to a production server.

**Comment by arpith** [comment]
@borisyankov what would you suggest?

**Comment by neerajwahi** [comment]
@arpith thanks for the PR! I'd probably get rid of the "Without a dev VM" heading since those steps are necessary whether or not you'd like to use the dev VM. Then we can rename the "With a dev VM" section to something like "Signing in to a local dev VM"

**Comment by arpith** [comment]
@neerajwahi done!

**Pull request merged**
