### PR TITLE
deps: Run `yarn upgrade`

### PR DESCRIPTION
**Pull request by chrisbobbe**

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks! Looks good; merging.

**Comment by gnprice** [comment]
Looking at the remaining output of `yarn outdated`, I see there are a few identified as `resolutionDependencies`, i.e. where `resolutions` in our package.json is holding us on an older version. I'll look into upgrading `node-gyp` in particular:
```
node-gyp                            8.4.1             8.4.1   9.0.0   resolutionDependencies
```

as that resolutions line originated as a way to make it use a newer version, not an older one:
a7d19c0ed252e91fc090ab9a55e7397210f8887f

**Comment by gnprice** [comment]
> I'll look into upgrading `node-gyp` in particular:

#5412.

**Comment by chrisbobbe** [comment]
Thanks!

**Pull request merged**
