### PR TITLE
Use icons for base-level narrows and search

### PR DESCRIPTION
**Pull request by borisyankov**
screen shot 2017-05-02 at 10 47 49 pm

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Should we use an envelope for "private messages"?  That's what we use in the webapp, and it looks better.

(As a sidenote, we should probably change the funny tag symbol next to @-mentions to an `@` in the webapp, since I think `@` is clearly a better choice).

**Comment by borisyankov** [comment]
Hmm. Does an envelope mean 'private messages' more than a chat bubble?

**Comment by timabbott** [comment]
I think it means it about as well, and the icon looks a lot better, especially alongside the home and star icons.

**Comment by borisyankov** [comment]
@timabbott Updated:

screen shot 2017-05-03 at 9 48 31 pm

**Comment by timabbott** [comment]
Definitely better, though, I don't super like that specific mail icon (the crease is too high); is it easy to use the font-awesome one we're using on web instead?  Ideally we'd be using the same icon sets.

**Comment by borisyankov** [comment]
Not very easy in that case.
I think it will look much better once you see it smaller on a phone; this probably looks twice as large on a laptop vs phone.

I suggest we do some 'icon matching' in a while though.

**Comment by timabbott** [comment]
Sounds reasonable.

**Comment by borisyankov** [comment]
Thanks, for the review. 👍 

The shadow looks good, I think we should apply it only when the list is scrolled.
Can we do that, and do you want to do a PR for it? :)

**Comment by Sam1301** [comment]
sure, will try 👍

**Pull request merged**
