### PR TITLE
Use gradle daemon in android to decrease build time

### PR DESCRIPTION
**Pull request by dhruvdutt**
Using gradle daemon in Android decreases build time. 🚀 
[A reference post](https://medium.com/@kevalpatel2106/how-to-decrease-your-gradle-build-time-by-65-310b572b0c43).

### CODE REVIEW

**Comment by borisyankov** [comment]
I don't think this is a good idea.
The `gradle daemon` will save few seconds, but our build is not few seconds, thus it will not be a 70% increase as in the article, but more like 2-5%... and it will take time.
On top of that usually, we do not restart the build during development.

What do you think about this @jainkuniya

**Comment by jainkuniya** [comment]
> I don't think this is a good idea.
The gradle daemon will save few seconds, but our build is not few seconds, thus it will not be a 70% increase as in the article, but more like 2-5%... and it will take time.
On top of that usually, we do not restart the build during development.

Completely agreed.

Actually `org.gradle.daemon=true` 
> You won’t be able to see the time difference in your first build as gradle has to initialize and start the daemon, but build times will decrease in subsequent builds as gradle daemon is already initialised.

And we only build once (for me it is almost once per month), so this will not be as that much useful.

BTW nice find @dhruvdutt

**Comment by borisyankov** [comment]
@dhruvdutt thanks for contributing and trying to make Zulip better.
I will close this PR because of the discussed reasons, but please do continue with the good work.
Thanks!

**Comment by dhruvdutt** [comment]
@borisyankov @jainkuniya I agree with you guys. Thanks for the motivation. 👨‍💻

**Pull request closed without merging**
