### PR TITLE
Renable prettier and fix all issues related to it

### PR DESCRIPTION
**Pull request by kunall17**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
Download a big file, for example:
`https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js`
It has already been run past their 'prettier'.

**Comment by borisyankov** [comment]
Prettier gets some of the config from eslint, so make sure the eslint rules match.

For example add this:
`    "comma-dangle": ["error", "always"],`

**Comment by borisyankov** [comment]
And I think, remove `"arrow-parens": 0,`.

**Comment by borisyankov** [comment]
Another file from another repo to use:
`https://raw.githubusercontent.com/facebook/react/master/src/renderers/dom/fiber/ReactDOMFiberEntry.js`

**Comment by kunall17** [comment]
I ran the prettier with our config on the FlatList file and got this result https://github.com/kunall17/zulip-mobile/commit/2aae2a25bb9b20a91030220e8e24ebcd0d2ee37f

**Comment by borisyankov** [comment]
Yeah, I compared the results. The two suggestions I made are moving the formatting in the right direction, but the exercise to find few more are left to you ;)

**Comment by kunall17** [comment]
This is the config they use, 
```
"prettier/prettier": ["error", {
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": false,
  "jsxBracketSameLine": true,
  "parser": "flow"
}]
```

The difference's are the bracketSpacing, trailingComma and they use 80 printWidth and we use 100. 
bracketSpacing I used as we used previous and about the trailingComma using all appends commas at weird places like https://github.com/kunall17/zulip-mobile/commit/2aae2a25bb9b20a91030220e8e24ebcd0d2ee37f#diff-0e9e178f26b4b38fb1dd2bbb7076b554L451

**Comment by borisyankov** [comment]
I don't think we necessarily need the squished `{}` with no spaces.
And also we don't need to match it 100%
I am just stressing any messing with the formatting better be done once, not sure we want to have another commit like this.

**Comment by borisyankov** [comment]
Yeah, the trailing commas is OK. Formatting in many projects tends to move to adding this extra and not needed comma.

**Comment by borisyankov** [comment]
So when you have 
```js
{
  a: 1,
  b: 1,
};
```
if you add another line it will not diff the `b: 1,` since you will not need to add a coma.

**Comment by borisyankov** [comment]
BTW I am fine with the 100 character width, but also with 80 if we decide to lower it.
What do you think? And what does @Sam1301 think?

**Comment by kunall17** [comment]
I would highly suggest for 100, as I think most of the screen of users are big enough or high resolution to have 100 chars of code in a line in their view

> And I think, remove "arrow-parens": 0,.

Then it would create conflict's b/w prettier
Btw was just going through the issue of arrow-parens in the prettier repo, and this is being highly suggested there to be implemented as an option.

**Comment by Sam1301** [comment]
I too think using `printWidth 100` would be better because of the changes it will require in the existing files. Though one reason to go with print width 80 would be to be able to easily view files in a standard sized terminal.

**Pull request merged**
