### PR TITLE
Add Search

### PR DESCRIPTION
**Pull request by borisyankov**
Based off of 'message cache' PRs.

* Add search UI and functionality
* Make MessageList more reusable. Use for search results

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
I am also not a fan of putting a search button in the left panel, and in the right panel for users.
Indeed having a search button on the main screen and everything organized in *tabs* and zero or one side bar is the norm.

**Comment by neerajwahi** [comment]
We can revisit whether to change the design to tabs at some point soon, but I don't see how that's related to this. Search can be in the main screen with or without tabs. Look at Slack for an example of an app without tabs but with a search icon in the navigation bar.

**Comment by borisyankov** [comment]
In order for a design to work on all mobile devices, and not just 5.5" phones (which I admit also having) we need to ensure focused views, with singular purpose.
We are already trying to fit a Stream + Topic in the nav bar, and it doesn't work that great on small devices.
We have at least 5-6 types of 'lists' of things. They do not naturally fit a left-right panel approach. That is consistent with most other mobile apps too, not unique to Zulip.

**Comment by neerajwahi** [comment]
@borisyankov I actually use the smaller 4.7" iPhone :)

Yeah I'm not sure what the right answer here is. I know you're in favor of a tab-based approach and there are certainly some advantages to that. My main concern is context. Suppose you have two tabs, "Streams" and "Messages". The "Streams" tab lists all your subscriptions and lets you narrow to a particular stream. But then narrowing will land you onto the "Messages" tab and it's not clear from a user-interaction standpoint that the two screens are coupled. Usually tabs are really nice for independent screens.

Another option is to move the topic and/or stream out of the navigation bar (below it perhaps) and add a search icon to the navigation bar.

@timabbott thoughts?

**Comment by timabbott** [comment]
A few ideas:
* What if we had one of the entries in the left sidebar like "Starred messages" be "Search"?
* We could put it in our main `...` menu that has stuff like "About the app/legal/etc." in it.

If none of these work, I'd probably just put it in the navbar and shrink the font size so things still fit...

**Comment by borisyankov** [comment]
I rebased and merged for 5th-6th time. 
There is no good reason not to merge.
Currently it is Tim's first suggestion, can be changed later, or course.

**Pull request merged**
