### PR TITLE
Vertically align text in ComposeBox

### PR DESCRIPTION
**Pull request by sniok**
**Before(iOS):**
image
**After(iOS):**
image
**After(Android)(Unchanged):**
image

### CODE REVIEW

**Comment by borisyankov** [comment]
@sniok thanks for working on this.
It is great that you did provide previews - always appreciated :)

I think a recent fix to the compose box resizing did improve the situation a bit (now the placeholder text is always centered). I think it is good enough now?

I wouldn't think a padding with a custom value would have worked long-term anyways.

**Comment by sniok** [comment]
I believe you are referring to this commit f8731c1422fb0d7d7b3dd409cf95437eb3de4def ?
Because on latest master commit the bug is still there:
image
The problem is in multiline input text alignment (regular input centers text just fine) and unforunately setting lineHeight to multiline input is not working (known unfixed bug https://github.com/facebook/react-native/issues/14232). And textAlignVertical is not supported on iOS https://facebook.github.io/react-native/docs/textstyleproptypes.html#textalignvertical

I absolutely agree that hardwiring absolute value is not optimal solution but I can't come up with better one.

**Comment by borisyankov** [comment]
I am not sure what is going on, I didn't expect this PR to necessarily fix that, but it seemed it did... for a while. Now I also reproduce the behavior you show in your screen shots.

The thing is, the correct behavior shows when the placeholder is long. So a custom offset also breaks the layout part of the time.

I suspect that a bug fix inside React Native is the solution we want. Maybe we should check for reported issues in the repo?

**Comment by borisyankov** [comment]
Thanks for working on this @sniok 
I am closing this PR and hoping for a complete fix produced by the React Native team.

**Pull request closed without merging**
