### PR TITLE
Improve topic screen.

### PR DESCRIPTION
**Pull request by jainkuniya**
* topic-screen: Pass streamId from props to selector.  08ce417
Before streamId was taken from getCurrentRouteParams, as on push/pop
current route params changes, resulting in re-render of screen.
Which is redundant.

* topic-screen: Connect to store with connectWithActionsPreserveOnBack. eae118f
So that it doesn't repaints when nav isTransitioning or going back.

### CODE REVIEW

**Comment by jainkuniya** [comment]
rebased 👍

**Comment by borisyankov** [comment]
Extra renders are not a problem usually, and certainly not a problem we should be solving with lots of effort (and potential to introduce issues).

I am OK with your 2nd commit.

**Comment by jainkuniya** [comment]
Submitted #2536

On older devices app is somewhat show when there are repaints on navigating.
So it's better to save unnecessary repaints on navigating, so that navigation transition are smooth.

**Comment by jainkuniya** [comment]
Closing in favour of #2748

**Pull request closed without merging**
