### PR TITLE
[WIP] Implement and smoothen UX around compatibility checks.

### PR DESCRIPTION
**Pull request by jackrzhang**
This PR corresponds to #3073.

This is a work in progress; I'm opening this now for reference - no need for review yet!

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @jackrzhang ! I've just merged the first of these commits, because that one is ready -- see 6f77a4a64 and its parent. (I made a tweak on top.)

**Comment by jackrzhang** [comment]
@gnprice With the last 4 commits, I've pushed updates to the `CompatibilityScreen` UI, which renders if a global check to https://zulipchat.com/compatibility fails.


<p align="center">
android-compatibility-screen-global-check
<p/>

**Comment by borisyankov** [comment]
That link does not look clickable.
We need the 'App Store' and 'Play Store' buttons:




These are just examples, not sure where is the the official source of these resources.

**Comment by jackrzhang** [comment]
The color and other visual properties of the linked text can be changed. I don't think the buttons are *needed*, though they're recognizable.

@borisyankov Where do you get those examples from?

**Comment by jackrzhang** [comment]
I've found the guidelines for the badges:
- https://developer.apple.com/app-store/marketing/guidelines/#section-products
- https://play.google.com/intl/en_us/badges/

(I'll go ahead and add them?)

**Comment by borisyankov** [comment]
I was a bit concerned about file sizes but the Google Play Store badge is just 13kb so I think that is reasonable.

**Comment by jackrzhang** [comment]
The (current) first 7 commits of this branch update the compatibility screen UI by adding touchable badges, as suggested by @borisyankov above, and phrasing the text a bit more concisely.

I ran `yarn jest` locally at  549d573; the tests passed.

I tested the screen on iOS 12.1 by running the build on my iPhone 7.

Here's a screen recording from an AVD with Google Play:

<p align="center">
android-compatibility-screen-global-check-with-badge
<p/>

@gnprice

**Comment by gnprice** [comment]
Thanks @jackrzhang ! This looks good.

Would you include also the original SVG download of the App Store badge? Good for reproducibility, as that is more like the real "source" version of the image.

**Comment by gnprice** [comment]
Merged, with a few edits. Thanks @jackrzhang !

**Pull request merged**
