### PR TITLE
WIP: account switcher: Add Realm Icons

### PR DESCRIPTION
**Pull request by punchagan**

### CODE REVIEW

**Comment by borisyankov** [comment]
I think you might not be using `prettier` or you have configured it incorrectly.
The formatting shouldn't be jumping like that. Better figure it out early 👍

**Comment by punchagan** [comment]
@borisyankov I was using `prettier` instead of `prettier-eslint` and that was causing some formatting to jump around, I fixed that now. Thanks! :smile:

**Comment by borisyankov** [comment]
Nice. :)

One of the reasons I didn't add icons earlier is that there were several changes needed first, to best implement this. Some of the changes were made, some not.

I think the optimal approach is for you to continue working on this, while I do some of the remaining changes, then you finish up the work based on them.

Right now, our `Account` and `Auth` objects match 100% but that we can consider temporary. By adding icon information, we want to separate them. `Auth` should not have this property, while `Account` should. (I will do this)

Then we need to consider how and when we will update the icons if the organization administrator changes them.

I was also thinking about separately storing the `serverSettings` data for each account and getting the information via a selector.

**Comment by chrisbobbe** [comment]
Hmm, this pull request looks a little old, but this would indeed be nice to add, as I don't currently see realm icons in master. 🙂

There are several conflicts, though, so we could either resolve them or throw out this PR and try again.

It appears that this (or a new PR) would fix https://github.com/zulip/zulip-mobile/issues/392 from early 2017.

**Comment by chrisbobbe** [comment]
Closing as superseded by #4647.

**Pull request closed without merging**
