### PR TITLE
Adds privacy and terms in SettingsCard

### PR DESCRIPTION
**Pull request by saketkumar95**
Fixes https://github.com/zulip/zulip-mobile/issues/297

Added the terms and privacy policy in settings card.

@borisyankov Review.

### CODE REVIEW

**Comment by saketkumar95** [comment]
@borisyankov  I saw slack's app. These were in the settings screen only.

**Comment by borisyankov** [comment]
Ok, then extract this to a LinkButton component. Instead of onPress pass it url.

**Comment by zulipbot-test** [comment]
Hello @saketkumar95, a Zulip maintainer reviewed this pull request over a week ago, but you haven't updated your pull request since. Please take a look at the requested changes and update your pull request accordingly.

Thank you for your valuable contributions to Zulip!

**Comment by borisyankov** [comment]
Another PR is merged implementing this. Closing.

**Comment by borisyankov** [comment]
Thanks for your contribution.

**Pull request closed without merging**
