### PR TITLE
Use flow-typed, react-flow-types and remove snapshot tests.

### PR DESCRIPTION
**Pull request by Sam1301**
* fixed snapshot tests
* added flow type for action sheet connector

### CODE REVIEW

**Comment by borisyankov** [comment]
@Sam1301 I think this PR was a very good learning opportunity for you...

That being said, what do you think about removing the snapshot test? 
Do you think it is useful or is it too much maintenance?

About the styles, I think we need to find the balance between helpful, but not too heavy-handed types. Maybe this much is too much.

**Comment by Sam1301** [comment]
I agree; the changes in this pr made possible to test missing props in various sub components of lightbox, which could also be type checked using flow. Since for redux connected components, flow isn't checking the missing props for the wrapped component, I think if we have a good working flow coverage, then removing snapshot tests would be good for simplicity.

Shall I update the pr to remove tests?

**Comment by borisyankov** [comment]
Yup! :)

**Comment by Sam1301** [comment]
Updated. Added `flow-typed` to install flow types for react-redux and added `react-flow-types` to use a type for HOC.

**Comment by borisyankov** [comment]
Looks good.

**Pull request merged**
