### PR TITLE
Google Auth

### PR DESCRIPTION
**Pull request by borisyankov**
* Add Google Auth for iOS
* Add Google Auth for Android
* Implement code to handle login/relogin

Note: none of the values configuring the services are secret. 
For iOS, the file is: GoogleService-Info.plist
For Android the file is: google-services.json

The Android file needs a manual edit before publishing (adding a secret key)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
@borisyankov why the dependency on Firebase?

**Comment by borisyankov** [comment]
About Firebase - no idea, it seems that the libs do depend on it somehow.
Followed Google's guide on how to add the dependencies, so didn't do it by mistake or anything.
They also talk about Firebase in the same Google Auth documentation.

**Comment by neerajwahi** [comment]
@borisyankov ok if I close this PR? What are your thoughts on the approach in #448 ?

**Pull request closed without merging**
