### PR TITLE
Use 'SafeAreaView' through the app

### PR DESCRIPTION
**Pull request by borisyankov**
Based on #2702 (as it changes internally how it uses `SafeAreaView`)

### CODE REVIEW

**Comment by borisyankov** [comment]
Rebased and updated. 
Now going over all the changes another time and double-checking everything works fine and nothing is missing.

**Comment by gnprice** [comment]
P1 because it fixes #3066 .

**Comment by gnprice** [comment]
We're now on react-navigation v2 (see #3573), so this is unblocked!

**Comment by gnprice** [comment]
Just rebased this branch. (Across over a year's changes!)

**Comment by chrisbobbe** [comment]
Just rebased across another year's changes; I came across this while looking at https://github.com/zulip/zulip-mobile/issues/4267.

There are a few issues with this branch that will need to be resolved:

- Things break if, on a single screen, we use a `SafeAreaView` and a `ZulipStatusBar` while the `ZulipStatusBar` still sets its own height. But the commits that add `SafeAreaView` and the commit that removes the `ZulipStatusBar`'s height are separate. They're not that large, so they could probably be reasonably combined into one commit.
- The status bar's background color isn't always correct (see, in particular, the chat screen).
- Tapping the image in the lightbox is supposed to make the header and the footer slide away completely; now, they just retreat into the safe area (top and bottom) but are still quite visible.

**Comment by chrisbobbe** [comment]
Also, it's worth noting that React Navigation has its own docs that go through how to handle safe areas—in a way that doesn't (at least doesn't directly) use the `SafeAreaView` component from React Native: https://reactnavigation.org/docs/4.x/handling-iphonex/.

**Comment by chrisbobbe** [comment]
This has been superseded by our current plan for #3066. Currently, we have #4683 open for part of that.

**Pull request closed without merging**
