### PR TITLE
Play zulip sound if new message but user in different narrow

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by Sam1301** [comment]
Looks great to me 👍 One super minor issue could be that we might not want to play sound in case of self @-mention and pm to self.

**Comment by borisyankov** [comment]
You are right. Though you will also be looking at the same narrow, if writing to yourself :)

**Comment by Sam1301** [comment]
I guess that makes sense :), I tested this by writing messages in the web client and see how the app responded. But in future once we support writing messages to a different narrow in the app, this might occur?

**Pull request merged**
