### PR TITLE
Added detox smoke test's in the travis CI

### PR DESCRIPTION
**Pull request by kunall17**
The ios build run's fine on Xcode but fails in command line ` xcodebuild -project ios/ZulipMobile.xcodeproj -scheme ZulipMobile -configuration Release -sdk iphonesimulator -derivedDataPath ios/build`

```
** BUILD FAILED **
The following build commands failed:
	CompileC build/Build/Intermediates.noindex/ZulipMobile.build/Release-iphonesimulator/ZulipMobile.build/Objects-normal/x86_64/AppDelegate.o ZulipMobile/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
child_process.js:634
    throw err;
    ^
Error: Command failed: xcodebuild -project ios/ZulipMobile.xcodeproj -scheme ZulipMobile -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/Users/travis/build/kunall17/AutoTools/node_modules/detox/local-cli/detox-build.js:26:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any info how to resolve this error?

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
You might want to try `ZulipMobile.xcworkspace` and maybe `pod install` (not sure if relevant)

**Comment by kunall17** [comment]
@borisyankov Not working with these!

**Comment by kunall17** [comment]
After a lot of work and trials the CI is hooked up with the basic detox UI test's! 
Next step would be initiate the server and then use the server to execute more tests. :) 🎉

**Comment by kunall17** [comment]
@borisyankov fixed this, LGTM
After this I'll write more test cases!

**Comment by borisyankov** [comment]
Do the Travis tests pass consistently? What are the risks if we merge this?
@Sam1301 have a look at this PR too (and comment). We will all be writing tests next.

**Comment by kunall17** [comment]
Let's see, I have rebased!

**Comment by kunall17** [comment]
@borisyankov the build passed after rebasing, so it would be stable if the detox test's passes locally!

**Comment by borisyankov** [comment]
Merging it then. 🌮

**Pull request merged**
