### PR TITLE
Replace legacy 5dip grid dimensions with Material dimensions

### LINKED ISSUE #2642: Replace legacy 5px-grid dimensions with Material dimensions
A lot of components in the app are styled with dimensions that are a multiple of 5px, like `padding: 10` or `height: 20`. Meanwhile, in newer code we've been moving toward [Material Design's guidelines](https://material.io/design/), which provide a systematic framework that can help us make consistent and well-designed choices across the app; and that comes with a 4px grid, so we have a lot of dimensions now that are based on that. Of course, these don't fit well with each other.

So, one thing we need to do in order to get fuller benefit from our use of Material guidelines is to convert each of the legacy dimensions to something consistent with Material Design. There are a lot of other kinds of changes we can and in many cases should make, but this issue is focused on adjusting the padding, margins, width, and height of components in our app without fundamentally changing their design.

To go about doing this:
* Find places where we have values of 5, 10, 15, etc., in our styles. A good way to do this is `git grep`: try `git grep ': 5\b' -- $(git ls-files src/ | grep -v __test)`. [1] For this issue, let's skip adjusting font sizes (those have their own complexities), but any padding, margin, width, height, or flex-basis value is good.
* Pick one component, or one style. Make each commit affect the smallest number of things that make sense to change together (like the height and margins of a single component, or of components that appear next to each other; but put changes to unrelated components in separate commits.)
* Find the appropriate Material dimensions to use. This will almost always be a multiple of 4px, often of 8px. To do this, find the most closely analogous components in the Material catalog (e.g., here's the page on [buttons](https://material.io/design/components/buttons.html); look through the other items under "Components" in the left nav bar), look at the "Specs" section of that component's page, and match those as closely as makes sense.
* Make that change. Be sure to take before/after screenshots to include in the PR.
* Send a PR with the first one or two such commits, for early feedback. Then send more.

[1] Here's a fancy version that finds all multiple-of-5 values at once:
```
git grep -P '(?<!fontSize|duration): (5|[1-9][0-9]*[05])([, ]|$)' -- $(git ls-files src/ | grep -v __test)
```

### PR DESCRIPTION
**Pull request by agzuniverse**
Most of the changes are too small to be noticed. I've provided screenshots of some of the more noticeable changes.

`AvatarItem` before:
avatars_before

`AvatarItem` after:
avatars_after

`Popup` and `TopicAutoComplete` before:
topicauto_before

`Popup` and `TopicAutoComplete` after:
topicauto_after

`RealmInfo` before:
realminfo_before

`RealmInfo` after:
realminfo_after

`ErrorMsg` before:
errormsg_before

`ErrorMsg` after:
errormsg_after

`SearchEmptyState` before:
searchempty_before

`SearchEmptyState` after:
searchempty_after

`StreamTabs` before:
streamtabs_before

`StreamTabs` after:
streamtabs_after

`NotSubscribed` before:
notsubbed_before

`NotSubscribed` after:
notsubbed_after

`LightBoxFooter` and `LightBoxHeader` before:
lightbox_before

`LightBoxFooter` and `LightBoxHeader` after:
lightbox_after

`NoMessages` just removes redundant padding, no visual change.

This PR aims to close #2642

### CODE REVIEW

**Comment by borisyankov** [comment]
Just by looking at the numbers, some of them look wrong.
Do not try to apply the closest number, but what the 'intention' was.
Our previous `10` meant what we now use `16` for. So `10 => 16` instead of `8`.

**Comment by agzuniverse** [comment]
I have made 10 to 16 in some places, but in others giving a value of 16 makes the spacing look too much, hence decided to go for 8 instead.

**Comment by gnprice** [comment]
Thanks @agzuniverse !

I just merged the StreamListCard commit -- that one looks good.

I tried to look closer at the AvatarItem case... but I can't actually locate a screen that looks like the one in your screenshot! E.g., I went to start a group PM thread, and I got this:
image
How'd you get to that screen?

**Comment by gnprice** [comment]
For the rest, I really would appreciate seeing before/after screenshots. That way, while we're going through these we can make sure we're really adapting these dimensions to appropriate values for a Material layout, beyond making them multiples of 4 or 8.

I took a look at SectionSeparator, one of the other first few in this series. For that one there's still too much space. I think the right thing might actually be to give it zero margin; or better yet, 0 below and -1 above. That's what the Material guidelines call for -- see the [dividers](https://material.io/design/components/dividers.html) doc, or the [old version](https://material.io/archive/guidelines/components/dividers.html) is actually clearer. (Because our list items aren't necessarily Material-aligned, that might not be exactly right for us, but I'd like to see what it looks like.)

**Comment by agzuniverse** [comment]
To get the screen in the screenshot, from the screen to create a group PM thread, tap on any user and their Avatar will show up at the top.
I shall provide screenshots for my other changes very soon.

**Comment by gnprice** [comment]
Sounds great -- thanks!

**Comment by agzuniverse** [comment]
I have added before/after screenshots for everything except `SectionSeparator` and `SectionHeader`, those will be added soon. Some of these changes are more or less imperceptible.

**Comment by gnprice** [comment]
Thanks @agzuniverse ! These screenshots are super helpful.

For AvatarItem: In the padding above the text, I think I actually like our existing 2px better. The actual space above the letters is more than that because of the font; sorting that out cleanly is another project. The rest of it: merged!

For Popup and TopicAutocomplete: My first reaction is that this amount of padding feels like too much.  Your commit message says the values of 12 and 16 come from Material Design; would you link to the particular spec you're thinking of there? I'd like to compare and see if there are other variables involved, where what we're doing is different from the Material component in other ways that affect the design.

RealmInfo: merged!

ErrorMsg: your "after" screenshot is showing up as a broken image.

SearchEmptyState: merged!

StreamTabs: merged!

NotSubscribed: merged!

LightboxFooter, LightboxHeader: merged!

NoMessages: Hmm, does this really have no effect?
```
-    paddingLeft: 10,
     padding: 8,
```
I'm not sure offhand whether the `paddingLeft` would override the `padding`. I'd want to check docs, or if they don't answer the question then check empirically, before assuming it doesn't do anything.

**Comment by agzuniverse** [comment]
`NoMessages`: It seems to make no difference except a padding of 2dips to the left, which seems to serve no purpose.

`ErrorMsg`: The after screenshot appears fine for me, but I'll re-upload here now.

Before:
errormsg_before

After:
errormsg_after


`AvatarItem`: Dropped the commit that increases `marginTop` from 2 to 4.

`TopicAutoComplete`: https://material.io/design/components/lists.html#specs was what I was referring.

**Comment by agzuniverse** [comment]
`SectionHeader` before:
header_before
a8cc75.png)

`SectionSeparator` before:
separator_before

`SectionSeparator` after:
separator_after

**Comment by chrisbobbe** [comment]
@agzuniverse did you mean to close this, or were there more changes that you'd like to be reviewed? 🙂

**Pull request closed without merging**
