### PR TITLE
language-settings: Fix layout.

### PR DESCRIPTION
**Pull request by jackrzhang**
See #2610.

### CODE REVIEW

**Comment by jackrzhang** [comment]
Here's how it looked before on my iPhone 6 simulator:



And here's how it looks with this pull request:

**Comment by borisyankov** [comment]
It is likely fine to change the `listItem` styles globally.
We definitely want to reuse styles.

**Comment by jackrzhang** [comment]
I think changing the `listItem` style globally wouldn't visually break anything, but my concern is that list items vary in terms of the details in their design and how they present their content. Something like the amount of padding that would make a list item look polished varies with each component.

@gnprice Thoughts?

**Comment by gnprice** [comment]
I think there is indeed such a thing as a generic "list item" style. Here's Material's specs for them:
https://material.io/design/components/lists.html#specs

It is more complicated than just one stylesheet entry -- even when sticking to Material, there's single/double/triple-line items, with or without right icons or big left images. So when we look closely at the different ways we apply `listItem`, we may find we should split it into several different style entries for the different cases. Those still all belong in a shared place, though.

In any case, this list is doing something funky in order to imitate a particular iOS convention. So I think it's fine for its style to live in the component's module.

**Comment by gnprice** [comment]
Merged -- thanks @jackrzhang !

I tweaked the commit messages a bit; mainly to reframe why we're moving this style into the local component file, also adding a "Fixes:" reference.

**Pull request merged**
