### PR TITLE
[Android] Fix: LightBox footer not visible.

### PR DESCRIPTION
**Pull request by vishwesh3**
Before
screen shot 2017-11-03 at 11 44 04 pm

After
screen shot 2017-11-03 at 11 42 49 pm

### CODE REVIEW

**Comment by borisyankov** [comment]
Good catch. I did rework it to get rid of the offset concept.
Since you are on that, can you implement it completely?
There is no need for calculation of heights and anything like that, we just need a container that 'owns' both the header and the footer (and the image I guess), with an overflow (just like the ComponentWithOverlay).

**Comment by vishwesh3** [comment]
okay! will look into it :) 👍

**Comment by vishwesh3** [comment]
updated 👍 
screen shot 2017-11-04 at 12 04 47 pm

**Comment by borisyankov** [comment]
Nice.

**Pull request merged**
