### PR TITLE
webview: Layout fixes.

### PR DESCRIPTION
**Pull request by jackrzhang**
See #2696, #2693.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @jackrzhang !

Would you post in the PR a before/after screenshot pair for each of these changes? That's helpful for reviewing them.

**Comment by jackrzhang** [comment]
For issue #2696 -

Before: 


After:
image

**Comment by jackrzhang** [comment]
For #2693:

Before:
image

After:
image

**Comment by gnprice** [comment]
Thanks @jackrzhang ! Pushed the first commit, for descenders on sender names.

The other commit seems to have extra side effects when there's other text around the emoji. The existing rendering isn't great in this situation, but this change seems to make it worse. Here's a few messages as shown in the webapp, in `#Testing` on czo for handy comparison:
image
These just put an emoji between words, with and without a space on each side between the emoji and the words.

Here's what those look like in master:
image
Arguably we're right to stick the glyph right up against the word to the right when there's no space (and the webapp is wrong not to); but the last message is `close:medal:emoji`, and we don't handle it symmetrically, which it seems like we should. Also if we decide not to follow the webapp, we should get the webapp fixed to minimize the surprise of something coming out differently for one user than another user saw and intended.

Now here's with this change:
image
There's a ton of extra space after each emoji glyph.

(For reproducibility: those are all on Android 8.1, with system font size turned up to max. I had the latter setting in place because it aggravates the issue in #2696 .)

Would you sort that out and fix it? If that means also fixing the underlying issue we already have, then great :smile:

**Comment by jackrzhang** [comment]
A fix could entail changing the html for an emoji within a message. [Here's a discussion on chat](https://chat.zulip.org/#narrow/stream/2-general/topic/Unicode.20Emoji.20Accessibility).

**Comment by gnprice** [comment]
Thanks @jackrzhang for that investigation!

It sounds like the fix for the remaining issue #2696 will end up looking different from the remaining change in this PR; so let's leave followup discussion to happen there.

**Pull request closed without merging**
