### PR TITLE
AccountDetails: Add the feature to select and copy the `full_name`.

### PR DESCRIPTION
**Pull request by VishalSharma2000**
This commit will allow the user to select the `username` and copy it.

Fixes: #5166

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Thanks! I tested on iOS. The experience was a bit different from the one you report on Android: instead of giving me start and end cursors to select a substring, it just offered a "copy" button on long-pressing the text. I think that's fine.

I should play with it a bit on Android, as I mentioned at https://github.com/zulip/zulip-mobile/issues/5166#issuecomment-1093496676 , but otherwise this looks good except for one nit.

The nit: instead of `username`, the commit message should say "full name", or `full_name` for the identifier we use in the code. It's more accurate about what this user-facing string is.

**Comment by VishalSharma2000** [comment]
@chrisbobbe I have done the required changes. Please have a look, and let me know if any more changes are required. 

Thank you :smiley:

**Comment by chrisbobbe** [comment]
Thanks, looks good to me! I'll aim to merge this in a few days if @gnprice doesn't have anything to add.

**Comment by chrisbobbe** [comment]
Thanks! Merged. 🙂

**Comment by VishalSharma2000** [comment]
Thank you @chrisbobbe for your help and guidance :smiley:. It was a good learning and starter for me in zulip community and open source.

**Pull request merged**
