### PR TITLE
Upgraded to RN 0.48.

### PR DESCRIPTION
**Pull request by vishwesh3**
Now trying for RN 0.49 😄

### CODE REVIEW

**Comment by borisyankov** [comment]
👍

**Comment by sapkra** [comment]
Maybe you can also upgrade react. We are still using the alpha version at the moment.

**Comment by borisyankov** [comment]
React's version is whatever peerDependency the React Native has with the given release. They still haven't moved to 16.0.0 final, so we shouldn't either.

**Comment by borisyankov** [comment]
Looks like it works. Merging.

**Pull request merged**
