### PR TITLE
Rework initial data requests for faster startup

### PR DESCRIPTION
**Pull request by borisyankov**
Implements #304

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Thinking about server-side changes to support the app in the future, it sounds like it'd be useful to have:
(1) A way to fetch the data on streams for the user with the subscribers data (since the latter is the vast bulk of the network activity for fetching streams/subscriptions)
(2) A way to fetch only the presence information for recently active users

Is that right?  Are there other things @borisyankov?  I want to make sure we get everything important into our next release.

**Comment by borisyankov** [comment]
Yep on both.
(2) is much more critical for a long running app on a mobile network. The response can be slow and large.
If there are other sources of large amount of data we should investigate.
Android has a pretty good graph of how much an app uses, which is good for us, but also is a thing that should keep devs caring about these things as customers (rightly) can see it too.

**Comment by timabbott** [comment]
Cool.  I'll open server issues for these.

**Pull request merged**
