### PR TITLE
Add LaTeX support (v2)

### LINKED ISSUE #2660: LaTeX Support in mobile
The Zulip app currently does not render LaTeX formatting correctly.

A simple example from a user in my realm:
* Correctly rendering visual of post in desktop app:
image

* Incorrect render on Android:
image

* source code:
````latex
\text{DRYLAB WEEK OF 6/10/18} 
```
```latex
General
```
- These updates will either come in the form of Hardware/Software/Simulations or Chromastat/Simulations or Chromastat/Game/Simulations

```latex
Chromastat
```
We will be meeting on Tuesday to talk about expectations, deadlines, and get started with work. We have gone in depth with how the device is built and programmed so far. 

```latex
Simulations
````

### PR DESCRIPTION
**Pull request by ray-kraesig**
Add LaTeX support. Fixes #2660.

Continuation and/or revision of #3679, which was closed due to overloading GitHub's UI with too many tangents. (Sibling, in some sense, of #3705.)

### CODE REVIEW

**Comment by ray-kraesig** [comment]
(Rebased and resolved merge conflicts. However, there are display issues on (at least) Android.)

**Comment by ray-kraesig** [comment]
The display issues mentioned above were resolved by a `yarn install`. Ready for review.

**Comment by gnprice** [comment]
Marking as priority, following the issue.

**Comment by jedbrown** [comment]
I'd just like to comment that this is a really compelling feature for the many research groups that grumble daily about Slack lacking math and language-specific code. "That all works in Zulip" is a much stronger pitch than "it works with some clients". Thanks, @ray-kraesig, for implementing, and thanks in advance for the review, @gnprice.

**Comment by pyrocto** [comment]
We've been waiting for this for a long time.  Looking forward to it!

**Comment by gnprice** [comment]
Thanks @jedbrown and @pyrocto for those words of support!

I've just sent #4005, which incorporates several of @ray-kraesig's commits from this PR for their math-displaying goodness, and replaces the build-infrastructure pieces which I'd been concerned about the complexity of. I'm hoping we'll be able to merge and release this functionality soon.

Closing this PR in favor of code discussion there. I've also copied @jedbrown's and @pyrocto's comments over into the issue, #2660 .

**Pull request closed without merging**
