### PR TITLE
ESLint 6.8.0 upgrade

### PR DESCRIPTION
**Pull request by chrisbobbe**
Closes: #4120

This was started with the RN v60 upgrade (#3548) in mind, since the [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.6) had us going to ESLint 6 from 5.

But running

`rm -rf node_modules && yarn && tools/test lint prettier --full`

(yes, newly ensuring to use `--full`! see [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4120.20ESLint.206.2E8.2E0.20upgrade/near/888186) for more on that)

with these commits positioned before or after the RN 60 upgrade gives no warnings or errors whatsoever. So it seems like we're in good shape to get this done at any time, and no mention is made of the RN v60 upgrade in this revision.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
@gnprice If you'd like the reorganization of those Airbnb overrides to look different, please feel free to change as you see fit, if you prefer that to a round-trip review. (Of course I'll make changes, as requested, if you prefer that, too.) I do always examine any changes you make before merging, when you mention them, to increase my chances of doing things better next time. 🙂

**Comment by chrisbobbe** [comment]
Oops! As also noted at https://github.com/zulip/zulip-mobile/pull/4133#issuecomment-637219322, I'll fix this to say `Fixes: #...` instead of `Closes: #...`.

**Comment by chrisbobbe** [comment]
> Oops! As also noted at [#4133 (comment)](https://github.com/zulip/zulip-mobile/pull/4133#issuecomment-637219322), I'll fix this to say `Fixes: #...` instead of `Closes: #...`.

Done. I also rebased and fixed some conflicts.

**Comment by gnprice** [comment]
Thanks @chrisbobbe ! Just read this, and it looks good. The main thing it needs is a rebase.

I might make some adjustments to how the eslintrc is organized. I agree that's better to just do rather than round-trip through a review.

Small comments:

#### cea62b754 tools/test lint: Make globs passed to `prettier-eslint` absolute.

There was a chat discussion about this, right? May be worth linking to in the commit message, to help explain the syntax for any reader unfamiliar with this sort of Bash arcana.

#### 859fee6e7 deps: Remove direct `eslint-config-airbnb-base` dependency.

    Also, run `yarn yarn-deduplicate && yarn`, as prompted by
    `tools/test deps`.

There's no change to `yarn.lock` here, so it seems like this change wound up in a different commit.

... Hmm, in fact -- in an earlier commit in the series:

#### 9c6aebb2f deps: Upgrade babel-eslint to ^10.0.3.

the `yarn.lock` changes look like they introduce duplicates which I expect `yarn yarn-deduplicate` would remove.

**Comment by chrisbobbe** [comment]
Thanks for the review, @gnprice!

> There was a chat discussion about this, right?

Ah, yes—thanks for the reminder! Added a link.

About `yarn yarn-deduplicate && yarn`:

Yup. Looks like I'd marked that I'd run that command on...both commits. Sure enough, running it at the `babel-eslint ^10.0.3` commit resulted in some changes, so, I committed those, and `tools/test deps` didn't complain at the `eslint-config-airbnb-base` commit, so I removed that bit of the commit message.

**Comment by chrisbobbe** [comment]
OK, just pushed my latest changes, for another review. 🙂

**Comment by gnprice** [comment]
Looks great, thanks -- merged!

**Pull request merged**
