### PR TITLE
libdefs: Fix/suppress most glossed-over errors in react-intl libdef

### PR DESCRIPTION
**Pull request by chrisbobbe**
Like we did for React Nav's libdefs in #5263. This will help us toward the RN v0.65 upgrade, #5230, by preparing to upgrade Flow.

Done by temporarily upgrading to Flow v0.149, which has [this bugfix](https://github.com/facebook/flow/blob/main/Changelog.md#01430) from Flow v0.143—

> * Previously, errors in library files were sometimes being missed due to a bug. This has been fixed, which may expose errors in library files that were not previously being reported.

—and going through the newly caught errors.

@gnprice, three of these errors remain after this branch. Would you be up for taking a stab at the best approach for them? You could add some commits if you see something easy, or else let me know a good direction and I'll do it. Thanks!

```
Error ---------------------------------------------------------------------------- flow-typed/react-intl_vx.x.x.js:64:36

Cannot resolve name `Pick`. [cannot-resolve-name]

   64|   declare var DEFAULT_INTL_CONFIG: Pick<
                                          ^^^^


Error --------------------------------------------------------------------------- flow-typed/react-intl_vx.x.x.js:173:43

Cannot resolve name `Exclude`. [cannot-resolve-name]

   173|   declare export type FormatDateOptions = Exclude<DateTimeFormatOptions, 'localeMatcher'> &
                                                  ^^^^^^^


Error --------------------------------------------------------------------------- flow-typed/react-intl_vx.x.x.js:780:37

Cannot resolve name `Omit`. [cannot-resolve-name]

   780|   declare type OptionalIntlConfig = Omit<IntlConfig, $Keys<typeof DEFAULT_INTL_CONFIG>> &
                                            ^^^^
```

Looks like they're uses of TypeScript's [utility types with those names](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys). (This libdef began from a TypeScript to Flow translation using Flowgen.) I am kind of puzzled by the uses of `Exclude` and I wonder if they really meant to be uses of `Omit`…

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks! These changes all look good -- please merge at will.

I'm looking at those three remaining errors.

**Comment by gnprice** [comment]
For `Pick`, it looks like it's basically doing the same job as the `SubsetProperties` in our `generics.js`.

Sadly I'm not finding a way to implement a version with the same interface as `Pick`, where it takes a union of the keys. I hoped this might work:
```js
type Pick<T, Keys> = SubsetProperties<T, { [Keys]: mixed }>;
```
but it doesn't ([try-flow](https://flow.org/try/#0FAFwngDgpgBAygVwEYGcogAoCcD20sgCWUKAPACoA0MAqgHwwC8MAJAPJIBWAsgIYSFSNaqQDS1AGp0AFKICUTBiwCiAGygBbKADsQ5SFArVRdOgG5QBmBkIBjANZGYoqGBQNmiVOmx4oBYjIqGABvGABtFzcAXQAuGA1CAA8oABMYAF9zGAB6HJhUnBJtAHIQGAB3HCx7ahReVNUwMxg0WCQoVRwK4EtoGHImUJheeO0EDQ6saiR4lBAsQm0Ac0yLYGkk+K80TFx8IhInMNGE5LTMujl4k7GJqczFGCSLTe3kXd8DwOOIkt4SnEzil0llrsNTuNJv5HowGC8Nlt4B8fPt-IcgtRbsC0jN4okQZdwdioVM8a0FktVhkngi3sjvHs-AEjsEwuF-iUYAAfGAlJCA-HnUFXG4jO7Q6YwWYUxYrWHwlp5Aq8FbUfy4LC9ek2BxOTmiiHxTQQcAK55K-Ia6qI+K6xzBA3E8UwUkwmlwi226x2B3UJ1i04Ei4exW5K1YTXe+36gGGsIy+Zy6m0y0wa1anW+2Nc3n8krxl1uqWJyny0MW8MwABCAEEACJ1AAWOAQqnSvFstigpuAQA)). And in retrospect that makes sense -- I think the issue is probably that `$ObjMapi` on an indexer like `{ ['a' | 'b']: mixed }` is going to produce a type with a corresponding indexer, `{ ['a' | 'b']: /* something */ }`, not an object type with separate property entries for `a` and `b`.

So the best available solution may instead be to copy in `SubsetProperties`, like `declare type SubsetProperties…`, and then edit each of the `Pick<…>` sites to use that instead.

**Comment by gnprice** [comment]
For `Omit`, I'm afraid it looks like the same story. Here I was more hopeful because this definition seems like it really *should* work:
```js
type Omit<T, Keys> = $Rest<T, {| [Keys]: mixed |}>;
```

But it seems to become another victim of indexers just being kind of broken:
```js
type Omit<T, Keys> = $Rest<T, {| [Keys]: mixed |}>;

type T = {| a: number, b: string |};

(x: Omit<T, 'b'>): {| a: empty |} => x; // error, good
(x: Omit<T, 'b'>): {| a: number |} => x; // BAD error

// What happens instead:
(x: Omit<T, 'b'>): {| a: number | void, b: string | void |} => x; // weird!
// or spelling that out:
(x: $Rest<T, {| ['b']: mixed |}>): {| a: number | void, b: string | void |} => x; // weird!

// It's fine if there's normal properties instead of an indexer:
(x: $Rest<T, {| b: mixed |}>): {| a: number |} => x;
```
([try-flow](https://flow.org/try/#0C4TwDgpgBA8gtgS2AHgCoBooGkIgM4B8UAvFACQBKEeKGUA3gD5QDaO+AugFxSIAeEACZRGAXwIBuAFBTQkKKhINmAQx4A7AK5wARhABOmHTxr6E6gOYjR0qQAo+PeEjSYA5DrcEAlDyZQ1KAg4MFBrEiI+CSgAehig-X0Ae0MoCySkwXtHWERad08fP1UNbT19cOJI6LioACEAQQARBOT9GVqAdQALFWAoXrBIdTwocxoIFUEubKc81ygPL19lANLdAxEoADckhEEjE2AzSy3d-crq2PiAdwgEfUEAQilalKg8SAAbL-MrYF6-SSmmAMwcPEo1HyqxYS24vAQAmEYiKq0CWg2FWY5wOUGMH2OfzOe2RogiUCi1ygdwezw68QAksA3KMAGbmaAIVlQAEGCAsqDqFJwFRfKBgZKQfTABDUMYjYCTYRJbkqdTywQQAT6ME5SE0Bb+fH8ITWVH+dFlTZiclRKRAA))

So there also, I think the best solution may be to edit each of the sites, here to use `$Rest` instead.

---

For one of them:
```js
  declare type OptionalIntlConfig = Omit<IntlConfig, $Keys<typeof DEFAULT_INTL_CONFIG>> &
    $Rest<typeof DEFAULT_INTL_CONFIG, { ... }>;
```
I think one can also simplify by taking advantage of Flow's spreads to make the `Omit` unnecessary:
```js
  declare type OptionalIntlConfig = { ...IntlConfig, ...$Rest<typeof DEFAULT_INTL_CONFIG, { ... }> };
```

**Comment by gnprice** [comment]
And then for `Exclude`, I agree that all of its uses appear to be mistakes where `Omit` was intended. (That can fairly be blamed on the TypeScript folks, perhaps -- those two names are basically synonyms and it's not at all clear how to say which one goes with which meaning.)

**Comment by chrisbobbe** [comment]
> Thanks! These changes all look good -- please merge at will.
> 
> I'm looking at those three remaining errors.

Great, thanks! Merged, and I'll address the three remaining ones in a new PR.

**Pull request merged**
