### PR TITLE
Fix: #3544. Fix empty selector is being provided to querySelectorAll.

### PR DESCRIPTION
**Pull request by jainkuniya**
* messageList, getUpdateEvents: Use `lodash.isequal` to compare object.
* web, msg read event: Make sure querySelectorAll never get empty selector

For more debug information, please refer #3544

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @jainkuniya !

Quick remark, having not yet looked at the code: please update the issue references to point at the original issue #3539, rather than #3544 .

**Comment by gnprice** [comment]
We chatted about this briefly in our video call today. Other than the nit above about issue references, just one small comment:
* The condition `!uevent.messageIds` is always false, so let's take that out. The type is `Array<number>`, and an `Array` is always truthy.
  * In general, for everything internal to the app, I want to rely on the types we've expressed in Flow, and not insert side conditions at runtime. If this value were `null` or `undefined` for some reason, that'd be a bug inside the app -- and a hole somewhere in our type-checking -- and we should just fix that bug.
  * (In some cases it could potentially be appropriate to have a runtime check of a condition that would represent a bug in the app. But if we did, it should be an error or at least get logged to Sentry. And in this case I don't see a particular reason to worry that there'd be a type error here that this would catch.)

After that, looks ready to merge!

**Comment by jainkuniya** [comment]
Updated 👍

**Comment by gnprice** [comment]
Thanks @jainkuniya ! Merged.

On reading again, I decided the optimization that switched to `!isEqual` from `!==` wasn't actually necessarily a good optimization. So I added a new commit on top to change it: ce4ed6ab2 .

**Pull request merged**
