### PR TITLE
webview: Fix: multiple messages are posted on Android.

### PR DESCRIPTION
**Pull request by jainkuniya**

### CODE REVIEW

**Comment by jainkuniya** [comment]
@borisyankov Can you please try this PR on your physical device, as a fix for #1600

**Comment by borisyankov** [comment]
I don't understand why this would fix it.
It looks the identical functionality.

**Comment by jainkuniya** [comment]
(https://stackoverflow.com/a/26146974/5612089)

BTW it seems to work when I encountered the same problem (https://chat.zulip.org/#narrow/stream/mobile/subject/meeting/near/400559)

**Comment by borisyankov** [comment]
In the example, they are actually calling `addEventListener` twice. I don't see any relation to our issue.

**Comment by borisyankov** [comment]
Can you confirm if this has any effect?

**Comment by borisyankov** [comment]
Looks like this is working now. Closing.

**Pull request closed without merging**
