### PR TITLE
Refactor: Move styles in GroupDetailsScreen to miscStyles

### PR DESCRIPTION
**Pull request by agzuniverse**
Also use the predefined HALF_SPACING for margin instead of setting it to 8.

### CODE REVIEW

**Comment by gnprice** [comment]
Are there other places in the app that use the same style and could refer to this instead?

In general I think moving a style to the shared global style sheet is only helpful when it's something that is really shared between different spots in the app -- if it's specific to a single component, then it's clearer all around if it's specified next to that component.

**Comment by borisyankov** [comment]
While we use this style only there, I think it is generic and reusable and this PR is a good step.
I am not sure about the name though, it needs to change.

**Comment by agzuniverse** [comment]
This styles does feel like it can be reused. What would be a better name for it? `subHeading`?

**Comment by gnprice** [comment]
I went and took a look at the context of this item. Here's a screenshot:

image

We're talking about the style that applies to the element with the text "Members".

It looks like this is trying to be what in Material Design terms is [a "subheader" of a list](https://material.io/design/components/lists.html#anatomy). A good short name for it would be "list subheader", or "listSubheader".

But zooming out a bit, to look at the design of this screen overall: there's no reason for this list to have a subheader. It's really just one uniform list of members. So a small fix I would be glad to see is to
* change the title in the app bar to "Group members"
* remove the "Members" subheader, making the whole thing just a list.

That will eliminate this style entirely. If we find ourselves putting in a list subheader in some other screen, we can make a "list subheader" style then. It'll be a bit different from this one, I think -- in particular, this one is aligned too far to the upper-left.

**Comment by gnprice** [comment]
Opened #2609 for the adjustment to this screen's design that I described above. Closing this PR because fixing that will subsume it. @agzuniverse , thanks for spotting this, and I'd be glad to see you take on that issue!

**Pull request closed without merging**
