### PR TITLE
Handle when subject is changed in EVENT_UPDATE_MESSAGE.

### PR DESCRIPTION
**Pull request by jainkuniya**

### CODE REVIEW

**Comment by borisyankov** [comment]
Have you seen this #2586

Ideally when your PR is ready, the Flow code in this PR should be passing (as the definitions are correct, but our code isn't)

**Comment by jainkuniya** [comment]
Okay! let's first finish and take #2586 in and then this :)

**Comment by borisyankov** [comment]
@jainkuniya you might have misunderstood me :)

The PR is just for the correct Flow type definitions, but it uncovered that we are not using the actual data correctly.

You can rebase to this branch and see if your changes make it pass.

**Comment by jainkuniya** [comment]
on it 👍

**Comment by jainkuniya** [comment]
Cherry picker that commit and refactored a bit. Now it is passing.

**Comment by gnprice** [comment]
Hi @jainkuniya !

I just spent a bit of time reading the code we have for this in `chatReducers` and `chatUpdaters`, and it is pretty complicated. This PR makes it even more complicated.

So, before we add more logic here, I'd like us to spend some time cleaning up the code we have. That means the bug this fixes will wait a bit to get fixed, but that's OK; it isn't a bug that I think users are running into a lot, and getting this logic (which is quite central to the app!) into better shape is a higher priority.

(Also, it looks like we don't have an issue to describe this bug. Would you file one? That will help us keep track of it.)

Here's an example: currently when we get an event to update a message, there are two places where we search for the existing message: at the top of `chatUpdater`, and a few lines later inside the `reduce`. That probably isn't great for performance; but worse, it makes this code harder to understand and harder to correctly make changes to -- it's likely to cause bugs.

With this change, we start checking in a third place (at the top of `eventUpdateMessage`); and then we duplicate that in several places with the refactor in the last commit.

**Comment by jainkuniya** [comment]
Opened #2688

**Comment by jainkuniya** [comment]
> With this change, we start checking in a third place (at the top of eventUpdateMessage); and then we duplicate that in several places with the refactor in the last commit.

I am to against this duplicity.
While working on this I was thinking to do minimal change in the existing code, which resulted duplicity.
Now refactoring it :) 👍

**Comment by gnprice** [comment]
Tracking the need for this kind of fix in #2688 ; let's track the eventual fix as a new PR.

**Pull request closed without merging**
