### PR TITLE
webView: Detect long press.

### PR DESCRIPTION
**Pull request by jainkuniya**
part of #1680

### CODE REVIEW

**Comment by borisyankov** [comment]
There is also an event called 'touchmove' that will be of help.
Maybe the sources of this component might be of help:
https://github.com/richadams/jquery-taphold/blob/master/taphold.js

**Comment by borisyankov** [comment]
Focus on these PRs as they are critical for us releasing a final version of the webview message list.

**Comment by jainkuniya** [comment]
ya! working on it

**Comment by jainkuniya** [comment]
Updated!
Now no interference between `click` & `longPress`. Both are independent.

For now I have tested on iOS simulator, Android emulator and physical device. It is working fine.

For now we take this in & and have an initial long press implementation in beta :)

Will be working on measuring touch distance and considering them next (and other part of #1680 )

**Comment by jainkuniya** [comment]
@borisyankov Updated 👍 
Ready to go in 🏃 
Will be connecting to our existing code of constructing action sheet next.

**Pull request merged**
