### PR TITLE
[Prototype] Modal Navigation

### PR DESCRIPTION
**Pull request by nashvail**
Prototype for Drawer-less Modal based navigation. Currently works only on iOS as 'modal' mode is not supported for Android in `react-navigation`.

Demo

### CODE REVIEW

**Comment by borisyankov** [comment]
Compared to a hamburger menu, this does not appear to have any benefit.
The huge downside is that the user has no idea the header is clickable.

**Comment by sapkra** [comment]
You should add a thumb menu on each stream view. This will solve the UX problem.

**Comment by nashvail** [comment]
@sapkra Could you elaborate on "Thumb Menu"? Didn't quite get what it is.

**Comment by sapkra** [comment]
@nashvail You already implemented the thumb menu in your popup view. I mean the bar with the hashtag and persons icon.

**Comment by borisyankov** [comment]
Thanks for prototyping this, Nash.
While I find it weird and wouldn't work for us, it was definitely helpful and I played with it few times to see we can be doing things differently.
As with any prototyping, many don't get implemented, but they contribute value by helping us understand how alternative interactions could work.

**Pull request closed without merging**
