### PR TITLE
flow: Add missing 'Context' types

### PR DESCRIPTION
**Pull request by borisyankov**
Components with `static contextTypes` get injected the context
object (of type `Context`).

Some components had this injected but the types were missing.
This adds `context: Context` to all such components.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @borisyankov !

I tried looking at a couple of these files, because I was curious what the effect of adding this was -- and I found they don't seem to use `context` at all! This includes at least `ZulipStatusBar` and `LightboxHeader`.

This might be a consequence of @agzuniverse 's recent refactorings to push down styles that were coming from `context` but actually were specific to the component.

Would you just remove the `context` properties we're not using? That'd clean things up a bit further, and also would make it easier to study this change.

**Comment by gnprice** [comment]
Meanwhile, I just went ahead and merged the first of these two commits.

**Comment by borisyankov** [comment]
The rest of the commits should now be ready to merge too.

**Comment by borisyankov** [comment]
@gnprice rebased. Looks ready to me.

**Comment by gnprice** [comment]
Merged -- thanks @borisyankov !

**Pull request merged**
