### PR TITLE
Open respective narrow on ios notification click

### PR DESCRIPTION
**Pull request by kunall17**
To be merged after server changes are merged https://github.com/zulip/zulip/pull/7080

This is untested though

### CODE REVIEW

**Comment by borisyankov** [comment]
Adding a WIP to the title of the PR. Remove it when you test and are sure it works.

**Comment by kunall17** [comment]
Hmm ok, but after the server PR merges you'll have to test it out because of the provisioning profiles!

**Comment by borisyankov** [comment]
@kunall17 where are we on this for Android?

**Comment by kunall17** [comment]
Waiting for the review in the server PR

**Comment by kunall17** [comment]
Can be merged without the server PR getting in 👍

**Pull request merged**
