### PR TITLE
Show stream in title when narrowed to topic. Fixes #171

### LINKED ISSUE #171: Fix formatting of stream sidebar
- Add more padding
- Delineate border with main screen (either via border or background color)
- Remove stream icons (and replace with '#')
- Add more boundary between the header (Home, Private Messages, etc...) and individual streams
- Highlight currently selected narrow (if applicable)
- Remove stream descriptions (and eventually move them to modal view visible with a hold-click)

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Can you post a screenshot of what this looks like?

**Comment by borisyankov** [comment]
image

**Comment by timabbott** [comment]
Nice (modulo that we should change that symbol to a `#`)

**Comment by borisyankov** [comment]
The sybol is changed, but in another PR 🥇

**Pull request merged**
