### PR TITLE
emoji: Show toast on error adding reaction emoji

### PR DESCRIPTION
**Pull request by WesleyAC**
Related: #4546

Screenshot:

Screenshot_20210318-231849

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks! Will be glad to fix this. As I mentioned [in the chat discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/force.20handling.20promise.20errors.3F/near/1135688) after you spotted this issue and sent this PR, this is an issue that Sentry shows us is happening regularly for a steady stream of users.

Showing the user this feedback is definitely an improvement, but I believe as is this change will also have the effect of suppressing the error in Sentry -- we're currently seeing it because the promise is throwing an unhandled exception. Because this condition is something we should fix in the software, I'd like to be sure we continue to get those reports; even after we fix #4546, that will mean we learn in the future if there's a regression.

We can do that by including a call to `logging.error`. See that function's jsdoc, and see the existing places we call it for examples.

**Comment by WesleyAC** [comment]
@gnprice done!

in debug mode, the error looks like this in the console:

```
[Fri Mar 19 2021 15:39:02.820]  LOG      {"httpStatus": 400, "json": {"code": "BAD_REQUEST", "msg": "Invalid emoji name.", "result": "error"}, "params": {"body": "reaction_type=unicode_emoji&emoji_code=0030-20e3&emoji_name=0", "method": "post"}, "route": "messages/1136226/reactions"}
[Fri Mar 19 2021 15:39:02.910]  ERROR    Error adding reaction emoji
[Fri Mar 19 2021 15:39:02.113]  ERROR        data: {}
    code: "BAD_REQUEST"
    httpStatus: 400
    line: 24092
    column: 28
    sourceURL: "http://localhost:8081/index.bundle?platform=android&dev=true&minify=false"
```

**Comment by gnprice** [comment]
> IIRC, server errors are translated, so the error will at least be in the language that the server admin has chosen for the server? Which is likely to correlate with the mobile app user's preferred language, I think.

I believe in fact it's better than that: for any logged-in requests they're translated into the user's preferred language, as set in their settings on the server (i.e. in/for the webapp.)

See the server code (and docstring) here:
https://github.com/zulip/zulip/blob/08212ef74a4703105b8e8ab563db76e5da68f91e/zerver/lib/exceptions.py#L57-L89

We actually introduced that abstraction, and the `code` property in the server's JSON responses, because the webapp had a bug where it wasn't properly handling the event queue going away if the user had chosen certain languages -- it was trying to interpret the text of the error message.

**Comment by chrisbobbe** [comment]
Ah OK, great, then! Thanks for that detail! 🙂

**Pull request merged**
