### PR TITLE
[WIP] Experimental replacement of the custom ScrollView with FlatList/SectionList

### PR DESCRIPTION
**Pull request by borisyankov**
This is experimental at this point.
We need to evaluate SectionList as replacement of our custom ScrollView (which currently has several issues on Android).

While we don't need to replace it urgently (maybe we do, since Android has issues) it is good to know if everything works and if not give feedback to the react-native team.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
We still need custom modifications to handle two-way infinite scrolling

**Comment by sapkra** [comment]
Check this out. Maybe it will help you.
http://stackoverflow.com/questions/43858585/two-way-infinite-scroll-react-native

If you have to modify the react component, please don't do it with native code.

**Comment by borisyankov** [comment]
@neerajwahi the virtual list view concept is quite perfect for that though, because we can have the item list recalculate-able, it is the perfect paradigm for our use case.

I am more than convinced that this is ideal for us, my only reservations are that there might be some missing features we might need (likely very few).

**Comment by neerajwahi** [comment]
I don't think that a virtual list solves the issue (although I'm happy to be proven wrong).

Imagine that you're scrolling up toward the top of the list (scrollOffset approaching 0). You fetch more data (which renders with height `h`) and prepend it to the top of the list. Now you have to bump scrollOffset from 0 to `h`, but if you make that change in Javascript it happens asynchronously and there will be a flicker during the delay from when you set `scrollOffset` in the JS thread and when it actually gets updated in the native ScrollView. This flicker makes the app look and behave really janky.

One option I have considered is using the Native Animation API but that doesn't support scroll offset as far as I'm aware.

This is why we have made custom modifications to the native scroll component.

**Pull request closed without merging**
