### PR TITLE
Fix: Components misalign on rotation (#414)

### LINKED ISSUE #414: Components misalign when app orientation is changed with SideBar open
When orientation of the app is changed with SideBar open following phenomenon is observed.

### PR DESCRIPTION
**Pull request by nashvail**
Fixes #414

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@nashvail, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
@nashvail do you know why changing it from 0.5 to 0.49 fixes the issue?

**Comment by borisyankov** [comment]
Indeed, the video shows it fixes it. I suspect it is some bug in the drawer component.
It looks like the drawer might be too wide still (but not buggy).
Try with 0.3, 0.35 or 0.4 to see if it works better.

**Comment by nashvail** [comment]
@neerajwahi not quite, looks like it has something to do with the drawer component (https://github.com/root-two/react-native-drawer). I'll go through their repo and open issues see if I can find something

**Pull request merged**
