### PR TITLE
docs: Add guide for connecting to a non-Vagrant dev server.

### PR DESCRIPTION
**Pull request by roberthoenig**

### CODE REVIEW

**Comment by gnprice** [comment]
OK, I just pushed a commit that fixes the within-Vagrant instructions. It includes a somewhat cleaner alternative to your instructions for editing `dev_settings.py`; the new version is mildly annoying but I think a lot more reasonable to have people do.

With that, I think the key point of difference remaining in these non-Vagrant instructions is the `--interface`, and looking up an IP address using `ifconfig`. I don't fully understand what that's doing for you; I'm curious about your networking config. Before merging these instructions, I'd like to better understand that -- partly in hopes that we might find a way to simplify :wink: , and partly because without more understanding I'm not confident the same instructions will generalize to work on others' machines.

What does `ifconfig` say for you? Or `ip addr`, which is the newer thing that I hear is recommended to switch to. (Maybe a chat thread would be a better place for this part.)

**Comment by roberthoenig** [comment]
> These steps aren't that bad, for the most part -- really the only one that's particularly bad

Do you mean "bad" as in "badly written" or "complex"?

`ip addr` is definitely better! What I meant with "local IP address" is "the IP address in the local network of your router" (for many local networks smt like 192.168.0.1). My router gives me 10.0.0.1. My `lo` address is 127.0.0.1 as well. 

```log
(zulip-py3-venv) robert@robhoenig:~/git/zulip$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 54:ee:75:26:2e:d9 brd ff:ff:ff:ff:ff:ff
3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 90:48:9a:a5:28:ef brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 brd 10.0.0.255 scope global dynamic noprefixroute wlp4s0
       valid_lft 250651sec preferred_lft 250651sec
    inet6 2a00:1028:8386:75de:2d35:45c3:8aa:ee01/64 scope global temporary dynamic 
       valid_lft 172780sec preferred_lft 77284sec
    inet6 2a00:1028:8386:75de:ca5:d3cf:dd83:9b69/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 172780sec preferred_lft 86380sec
    inet6 fe80::83a6:19d:16c6:5e0d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:92:9f:96:b3 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
The value of interest for me is here `inet` under wlp4s0. But the interface is dependent on how the reader is connected to the network, and also their OS (previous Ubuntus had this named as wlan0).

**Comment by roberthoenig** [comment]
I tried out your updated instructions with the `$ EXTERNAL_HOST=10.0.2.2:9991 tools/run-dev.py` using my local network IP address for external_host, without success. 

```
EXTERNAL_HOST=10.0.0.1:9991 REALM_HOSTS=10.0.0.1:9991 tools/run-dev.py --interface 10.0.0.1
```

didn't work either.

**Comment by gnprice** [comment]
> Do you mean "bad" as in "badly written" or "complex"?

Ah, sorry, I meant the actual steps the user has to take -- the writing is definitely fine!

I actually originally wrote "These instructions aren't that bad", but then realized that looked like it meant the writing, and changed it to "steps". But I guess it was still ambiguous.

**Comment by gnprice** [comment]
OK, and seeing that networking config for context is quite helpful.

One bit of background clarification: in that `ip addr` output, 10.0.0.1 isn't an address that refers to your router; it's an address that belongs to your machine. Each of the `inet` and `inet6` entries in that output describes an address belonging to your own machine. They each appear there underneath an interface (`wlp4s0`, `docker0`, etc.) which is connected to some kind of LAN, and the address is a local address on that particular LAN.

So, valid addresses for your machine include 127.0.0.1 (on the "loopback" LAN that goes nowhere but that one interface `lo`), 10.0.0.1 (on your wifi network), and 172.17.0.1 (presumably on a "bridge" LAN set up by Docker to connect that interface with an interface created inside Docker containers.)

To see the IP address of your router, you can use `netstat -rn`. Here it is on my laptop, while on the office wifi -- the "Gateway" column is the relevant one:
```
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.86.1    0.0.0.0         UG        0 0          0 wlp4s0
10.0.3.0        0.0.0.0         255.255.255.0   U         0 0          0 lxcbr0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 wlp4s0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.86.0    0.0.0.0         255.255.255.0   U         0 0          0 wlp4s0
```

And here's `ip addr`:
```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 54:ee:75:aa:a5:bd brd ff:ff:ff:ff:ff:ff
3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e4:a4:71:a1:93:66 brd ff:ff:ff:ff:ff:ff
    inet 192.168.86.94/24 brd 192.168.86.255 scope global dynamic wlp4s0
       valid_lft 57358sec preferred_lft 57358sec
    inet6 fe80::5bdc:ad7:de69:6271/64 scope link 
       valid_lft forever preferred_lft forever
4: lxcbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 scope global lxcbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:51:49:d4:ee brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
9: veth479FQC@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lxcbr0 state UP group default qlen 1000
    link/ether fe:aa:3e:95:ab:ef brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fcaa:3eff:fe95:abef/64 scope link 
       valid_lft forever preferred_lft forever
```

So from `ip addr`, my address on the wifi network is 192.168.86.94. Looking at `netstat -rn`: when I try to send a packet to any of various IP address ranges that correspond to local networks, it'll just send it directly (no gateway) to its destination over the appropriate LAN, using the appropriate interface. But for anything else, it sends to the gateway 192.168.86.1, over the wifi interface `wlp4s0`. That's the wifi router.

**Comment by gnprice** [comment]
With that background, the way I'd describe what 10.0.0.1 is doing for you is: it's an IP address of an interface on your laptop, that your emulator can reach. (Unlike the address 127.0.0.1 of the loopback interface -- if you try to reach that from the emulator, you'll get the emulated device's *own* loopback interface, if anything.)

That's the same thing that my "reload and watch the banner" trick should find too. So one thing I'm curious about is: does that trick work for you? If not, where and how does it fail?

We'll probably need to end up describing how to find such an address with something like `ifconfig` or `ip addr` too anyway, though, because in some studying with @jackrzhang today, we found the reload banner looks different on iOS so the trick doesn't work.

**Comment by gnprice** [comment]
> EXTERNAL_HOST=10.0.0.1:9991 REALM_HOSTS=10.0.0.1:9991 tools/run-dev.py --interface 10.0.0.1

> didn't work either

Huh, that is puzzling! You say this didn't work -- but editing `dev_settings.py` and then running just

```
tools/run-dev.py --interface 10.0.0.1
```

did?

I'm puzzled at that because from my reading of `dev_settings.py`, I'd think those should have exactly the same effect. So I'd like to get to the bottom of that so we understand why the instructions we give should work.

Could you try those two configurations with everything else held constant, and then post your exact diff to `dev_settings.py`?

**Comment by gnprice** [comment]
On the other part of this, I think I do now understand why you need the `--interface`, thanks to the investigation @jackrzhang and I did today to get a dev build on his iOS device working with his dev Zulip server, which is inside a Vagrant-managed VirtualBox.

In the Vagrant case, we forward the guest's port 9991 to the host, but only on 127.0.0.1. Which is a good default, not least because it's secure -- because it means it can only be reached from the machine itself.

So we had to tweak the Vagrant config to forward to all interfaces instead. (There's a documented way to do this; search for HOST_IP_ADDR in the Zulip dev docs.)

Similarly, I bet the dev server itself listens by default only on 127.0.0.1. So to use it on some other interface, we need to make it listen there. Which is what that option should do.

One thing that might simplify the instructions: often 0.0.0.0 serves as a wildcard to mean "listen on all interfaces". We did that for the Vagrant config tweak; I bet it'd work for `--interface` too.

**Comment by roberthoenig** [comment]
> One bit of background clarification: in that ip addr output, 10.0.0.1 isn't an address that refers to your router; it's an address that belongs to your machine.

Yup, that's what I meant with `Find the local IP address of your computer`. Can you think of a way to say this more clearly?

> Huh, that is puzzling!

Sorry, this was lack of rigor on my side. When writing this doc I must've not properly tested connecting to the dev server, so a mistake slipped in: It should be `tools/run-dev.py --interface=''` instead of `--interface=10.0.0.1`. In fact, I can run the whole thing now with
```
EXTERNAL_HOST='10.0.0.1:9991' tools/run-dev.py --interface=''
```

**Comment by roberthoenig** [comment]
(Note that the --interface='' must not be omitted.)

**Comment by roberthoenig** [comment]
> That's the same thing that my "reload and watch the banner" trick should find too. So one thing I'm curious about is: does that trick work for you? If not, where and how does it fail?

Nope, it doesn't. On my machine, RN for some reason uses 10.0.0.2 as the address (which is the wrong address): https://github.com/facebook/react-native/issues/17970 (We also have this as a gotcha in the dev guide).

> We'll probably need to end up describing how to find such an address with something like ifconfig or ip addr too anyway, though, because in some studying with @jackrzhang today, we found the reload banner looks different on iOS so the trick doesn't work.

Cool. That trick seemed odd to me anyway.

**Comment by roberthoenig** [comment]
Updated.

**Comment by gnprice** [comment]
Thanks!

I think at this point the only difference between the "dev server in Vagrant" and "dev server directly on host" cases may be that the latter needs the `--interface=''` option. (*) Which is really not that big a deal -- so I don't think this setup needs to be so strongly warned against. (Unless you want to warn people against trying to maintain a non-Vagrant dev server in the first place? I think the Zulip server dev docs are the place for that, if you want to make the recommendations there stronger than they are.) Or am I missing another issue?

In fact, the Vagrant case has its own bit of config that isn't needed in your setup, because it does the same job that `--interface=` does for you: setting `HOST_IP_ADDR`. In both cases, I think the server should end up listening only on localhost with no config, and this bit of config makes it listen on all interfaces instead. (For you, it's the server itself that listens on all interfaces; with Vagrant, it's the forwarder set up by Vagrant.) So, one thing I'm still curious about is why I don't seem to need that and you do.

One possible clue in pinning that down:

> > does that trick work for you? If not, where and how does it fail?
>
> Nope, it doesn't. On my machine, RN for some reason uses 10.0.0.2 as the address (which is the wrong address)

Hmm interesting -- where exactly does it fail? Does the reload itself work? And it shows 10.0.0.2? (It's 10.0.2.2 for me; not sure how it picks that.) But then if you use that address in the account switcher instead of 192.168.0.1, that doesn't work? If so, which screen do you get an error on?

> facebook/react-native#17970 (We also have this as a gotcha in the dev guide).

Hmm, that appears to be about an address like 10.0.2.2 not working *in a browser on the host*. For me, it doesn't work in a browser on the host, but it does work for the account switcher in the app inside the emulator.

I also did a quick CLI test with `adb shell`: on the host I ran `nc -l 8123` (port chosen arbitrarily), then I ran `adb shell` to get a shell inside the emulator and there I ran `echo foo | nc 10.0.2.2 8123`. It works -- the `nc -l` prints `foo`.

In that `adb shell` / `nc` test, 10.0.0.2 doesn't work for me, by contrast; but 192.168.86.94, my machine's address on its wifi interface, does.

My current theory is that the emulator is... aha. In fact, this is documented. :grin: Take a look at the discussion of 10.0.2.2 here: https://developer.android.com/studio/run/emulator-networking

Based on that documentation, I'm pretty sure 10.0.2.2 should work without needing to pass `--interface=`. Also, there's no need for my reload-banner trick -- that address is just a documented constant of the Android emulator.


(*) Shell tidbit: which can actually just as well be `--interface=` -- in fact that's what the shell processes it into before handing it to the command. Try `echo --interface=''` to demonstrate. Or:
```
$ python3 -c 'import sys; print(sys.argv)' --interface=''
['-c', '--interface=']
```

**Comment by gnprice** [comment]
I also empirically checked my understanding of what 10.0.2.2 means, by busting out `socat`, which is a more complicated alternative to `nc` that lets me (among many, many options) tell it to listen on just one interface. On the host: `socat TCP-LISTEN:8123,bind=127.0.0.1 STDOUT`. Then inside `adb shell`, I can still reach that port on 10.0.2.2 but no longer on 192.168.86.94.

**Comment by gnprice** [comment]
> Yup, that's what I meant with "Find the local IP address of your computer". Can you think of a way to say this more clearly?

Got it. I guess the way I think of things, "local" doesn't help here -- if anything, this address is the *least* "local" of any of the addresses belonging to your computer, in that it's the one exposed to the outside world.

I think you might be intending "local" to distinguish it from the IP address that a remote website might see you as coming from, which in a home or small office is typically an address assigned by your ISP and used by your whole home/office through a router. But I wouldn't call that an address "of your computer". Its relationship to your computer is the same as the relationship of an address like your 10.0.0.1, or my 192.168.86.94, to the emulator -- and we wouldn't call that the address "of the emulator".

Maybe "your computer's IP address on your local network"?

**Comment by gnprice** [comment]
I just pushed some commits that reorganize and reframe the existing doc to make space for this new material, and correct the bit about 10.0.2.2 for what I learned above.

Going AFK for dinner, but I'm partway through adapting this PR to go inside that framework; where I think it will be very helpful!

I am also curious to nail down the remaining mysteries discussed above about `--interface=` and about 10.0.2.2 / 10.0.0.2 .

**Comment by gnprice** [comment]
Merged. Thanks again! This has been quite educational.

I made some additional commits on top, which fold what we learned in both these instructions, and the iOS instructions from #2715, into the one main set of instructions.

Based on my current best hypothesis of how this works (see today's round of comments above), the instructions recommend for anyone using the Android emulator to use 10.0.2.2 and skip the whole business of finding an IP address and of setting `--interface` or `HOST_IP_ADDR`. In particular, that means I think that *should* work for you. :wink: So I am curious for you to try that! And to sort out what's happening if it doesn't.

**Comment by gnprice** [comment]
> The problem is that limits your dev server to connections from your emulator only. In particular, I cannot connect to the dev server from my browser anymore

Fair point, thanks!

I just added a note about this caveat: 04f1ac7a3. As the message there says, maybe that makes this alternative not worth including in the instructions in the end; we'll see, and perhaps take it out later.

**Pull request merged**
