### PR TITLE
Show current app version in settings card

### PR DESCRIPTION
**Pull request by kunall17**
simulator screen shot - iphone 6 - 2018-01-24 at 11 32 36
Make sure to call `react-native link react-native-version-check`

Also, this library can fetch the latest version from the play store so that can be a good feature too!

### CODE REVIEW

**Comment by borisyankov** [comment]
The lib `react-native-device-info` already gives version information.
I am also not sure if we need to add this, as this information is easily checked on iOS and Android.
(and the tests fail ;) )

**Comment by timabbott** [comment]
I think having it on some page would be useful; usually I'd expect the page in question to be the "about" page that has info on that it's open source, the license etc, which I suppose this is?

**Comment by borisyankov** [comment]
Generally, most big apps do not have such screens, thus users are not looking for them.
I find the 'Diagnostics' screen to be a proper place for the version info though (but using `react-native-device-info`)

**Comment by timabbott** [comment]
Yeah, "Diagnostics" sounds reasonable.

**Comment by kunall17** [comment]
I used `react-native-device-info` as it will be able to check for play store/ios store the latest version uploaded, for a future PR.

Anyways I'll use the existing one and send it diagnostics screen!

**Pull request merged**
