### PR TITLE
Fix input fields overlap with Nav bar in landscape mode (#2071)

### LINKED ISSUE #2071: Input fields overlap with the Nav bar in landscape orientation
screenshot_20180316-222709
It becomes hard to see what the user is typing.
screenshot_20180316-222740

### PR DESCRIPTION
**Pull request by codebu5ter**
BEFORE: 
screenshot_20180316-222709

AFTER:
screenshot_20180316-225906

Closes #2071

### CODE REVIEW

**Comment by borisyankov** [comment]
Nice, it looks you've found a fix! 👍 

Have you tested this on both Android and iOS?
The ideal solution will be to move this logic to the `KeyboardAvoider` component instead of removing it completely.

The screenshots are great, but a short description of the reason why our previous behavior was wrong and this is better is good to have.

**Comment by codebu5ter** [comment]
@borisyankov Yes, I've tested it on both iOS and Android and it works well on both platforms.
The reason I removed the `KeyboardAvoider` component is because it was only returning a `View` for Android and a `KeyboardAvoidingView` for iOS. This is a redundant exercise as the `KeyboardAvoidingView` works well on Android too, with the exception of the `behaviour` prop, which has been taken care of.
Also, since the visible area of the screen becomes tiny when the keyboard pops up in the landscape mode, I've wrapped the child components in a `ScrollView`, so that the user can easily scroll and reach input fields not visible otherwise.

**Comment by borisyankov** [comment]
KeyboardAvoider is the way we extract the logic for the two different platforms and that we do not repeat this every time.
Implementing the `padding` value difference can be implemented within this component.

**Comment by codebu5ter** [comment]
@borisyankov Understood. Turns out, wrapping the `children` in a `ScrollView` was enough to solve this issue. 😄

**Comment by borisyankov** [comment]
Cool. That looks like ready to merge.
Go over every single screen and confirm that wrapping it inside a ScrollView does not break them (because this applies to all of them) If it doesn't it likely improves them too, we just want to prevent a regression.

**Comment by codebu5ter** [comment]
@borisyankov After wrapping the child components inside a `ScrollView,` they were being pushed to the top of the screen, instead of being centered vertically.
I've made another commit to add some styling and fix this issue. Now, the `Screen` component looks exactly like before and even fixes the landscape overlap issue.

**Comment by borisyankov** [comment]
Aaaah :) Actually some of the screens centering their content is a minor bug I wanted to fix :)
So, we have screens that we want to have their content centered and some that we don't.

If you add a property that will optionally apply the styling you did add, that will solve the issue.
So a property like `centerContent: boolean`. By default it is `false` and `contentContainerStyle={componentStyles.content}` is not applied, but if `true` it is applied.

**Comment by codebu5ter** [comment]
@borisyankov I was about to point out the same thing. Centering the content does look out of sorts on some screens. 
I've made the changes, as requested. 👍 
Do let me know if you want me to add the centerContent prop to the screens requiring centering of content.
Or should that be covered in another PR?

**Comment by borisyankov** [comment]
I think this is good to merge as-is. Feel free to work on another PR adding this option 👍

**Pull request merged**
