### PR TITLE
Implement markdown parser to convert markdown to html

### PR DESCRIPTION
**Pull request by kunall17**
- [x] Emoji parser

Taken files raw files fenced_code.js, markdown.js, marked.js, util.js, hash_util.js

To be used in Full Screen editor and local echo of messages when sending message

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
We should publish the markdown as a library.
This is too messy, code that completely does not conform to our coding standards, uses outdated forEach lodash etc.

**Comment by kunall17** [comment]
Ok, @timabbott can you help me creating a repo zulip/zulip-markdown-parser perhaps?

**Comment by timabbott** [comment]
I'm happy to create a repo and give you admin access to it, but doing any sort of integration to make the server project use it is probably out of scope for what I have time to help with in the next few weeks.  I think there's 3 valid strategies for the near term:
* Basically include things as Kunal has, using lint-ignore files to just exclude the included code from our coding standards in the RN project.  That would let us get the integration correct and the RN app feature done without blocking on a big refactoring.  And then we can do the work to extract that as its own package much later.  Whether this is a good approach depends somewhat on how easy it is to do the style excludes.
* Just create a branch against `zulip.git` with the packaging (+ maybe some stubbing) changes and build+publish that to NPM (without it having its own repository or other infrastructure).  We'd rebase and re-publish the package as needed when we make changes we want to pull into mobile.  I think this is what Boris had in mind?
* Work in a new repository.  This feels cleaner, but also involves by far the most setup and maintenance work of the options, so I'd prefer we go one of the other routes.

**Comment by borisyankov** [comment]
I vote for option 2 in the short run.
@kunall17 if you don't know how to publish an npm package, I am sure you can figure it out, but also ask me if you have any issues.

**Comment by kunall17** [comment]
Ok, I'll create this is a package, just the emoji work has been left!

**Comment by kunall17** [comment]
Published this as a package https://www.npmjs.com/package/zulip-markdown-parser 
Works well :)

Pushed to a new repo as well for now https://github.com/kunall17/zulip-markdown-parser 
Has to be pushed to the zulip's branch!

**Comment by borisyankov** [comment]
@kunall17 do we need this PR since you published as a package?

**Comment by kunall17** [comment]
Nope!

**Pull request closed without merging**
