### PR TITLE
Add ScrollView in AuthScreen to support scrolling in landscape mode

### PR DESCRIPTION
**Pull request by saketkumar95**
This PR fixes some part of https://github.com/zulip/zulip-mobile/issues/787 scrolling issue.

### CODE REVIEW

**Comment by saketkumar95** [comment]
@borisyankov Ready for review!

**Comment by saketkumar95** [comment]
@borisyankov Apart from the conflicts, What do you think about this PR?

**Comment by borisyankov** [comment]
I am thinking if you are not just reinventing the KeyboardAvoidingView? 😄 
Did you try it out? And if yes, why did it not work in this case?

**Comment by borisyankov** [comment]
If you have a good reason to use this versus KeyboardAvoidingView, we can extract it to a component, as this logic is used elsewhere, and will likely be needed again.

**Comment by borisyankov** [comment]
Now all Screens are a ScrollView fixing this issue.
Closing as no longer needed.

**Pull request closed without merging**
