### PR TITLE
Store and use server settings

### PR DESCRIPTION
**Pull request by borisyankov**
Crates a `serverSettingsReducer` and when we receive that data updates it.
Adds calls to update the `serverSettings`
Also adds selectors to get this data out of the state.

Used to display realm icons, notification status etc.

### CODE REVIEW

**Comment by gnprice** [comment]
(#1507 is the issue for warning when the server isn't set up for notifications.)

**Comment by borisyankov** [comment]
Rebased.

**Comment by gnprice** [comment]
Thanks @borisyankov !

One thing I noticed just in doing a quick rebase of this:

> Extract a generic Notice component out of OffflineNotice
> refactor: Rework OfflineNotice to use Notice internally

This is a case where things would actually be clearer as a single commit. One commit copies a bunch of code, then the next one deletes (the bulk of) the original -- which means that what's really happening is the code is getting moved, and if they're squashed as one commit that becomes explicit.

In particular that means that when reading the green side of the diff, the code that's being copied is right there in the red side of the same commit, so the context is self-contained. It also means there's no worry when looking at the first commit that we're duplicating a bunch of code, because it's explicit that it's being moved.

**Comment by gnprice** [comment]
> +export type ServerSettingsState = {

Let's be sure to put a jsdoc on this. Follow the style of the other `*State` types' jsdoc.

One important question to answer: what are the keys exactly? There are several different formats we could potentially use for a string to identify a realm.

> +const initialState: ServerSettingsState = NULL_OBJECT;

There's no optimization benefit to making this be the same `{}` object as other `{}` we have lying around -- this `const` initializer runs once -- so let's write this more simply and directly as `{}`.

```
... => ({
+  ...state,
+  [action.data.realm_uri]: {
+    ...state[action.data.realm_uri],
+    authentication_methods: action.data.realm_authentication_methods,
+    realm_description: action.data.realm_description,
+    realm_icon: action.data.realm_icon_url,
+    realm_name: action.data.realm_name,
+    realm_uri: action.data.realm_uri,
+  },
+});
+
```

I think this would benefit from destructuring and object-initializer shorthand. Like
```
const { realm_uri, authentication_methods, /* ... */ } = action.data;
return { ...state,
  [realm_uri]: {
    ...state[realm_uri],
    authentication_methods,
    /* ... */ }};
```

... Oh hey, in fact after typing that I notice that `authentication_methods` is an *exception* to the names matching up. That makes me further inclined to prefer the shorthand -- the exceptions will stand out because the boring stuff will be simpler. :-)

> export type GlobalState ...
> +  serverSettings: ServerSettingsState,

Hmm -- this should have come when adding this reducer to `reducers`, no?

```
+export const getCurrentServerSettings = createSelector(
+  getCurrentRealm,
+  getServerSettings,
+  (realm, serverSettings) => serverSettings[realm] || NULL_OBJECT,
+);
```

Hmm -- I think it isn't 100% obvious expected behavior that the caller of this selector might get an empty object.

And in fact as drafted, this API is quite dangerous -- the type inferred for the selector is that it returns an `ApiServerSettings`, which means that if you just take `serverSettings.push_notifications_enabled`, that is already (supposedly) a `boolean`. It'd be very reasonable for someone to use that directly and not compare against `false` -- and then the code will implicitly treat "don't know" as false.

So this needs to get a type that causes `serverSettings.push_notifications_enabled` to have a type like `?boolean` or `boolean | void` (or else to just be an error without checking `serverSettings` first.)

It'd also be good to mention in jsdoc that it returns `{}` when not found, if that is what it ends up doing.

**Comment by gnprice** [comment]
This PR has been stale for a while. Given the last comments above, plus all the changes that have happened in master, I think the shortest route to fixing the issue will be to approach it fresh; so, closing this PR.

**Pull request closed without merging**
