### PR TITLE
 webView: Fix inline message emojies are not completely visible.

### PR DESCRIPTION
**Pull request by jainkuniya**
Before

This PR

### CODE REVIEW

**Comment by borisyankov** [comment]
That is definitely not a universal issue/fix.
Are you seeing this on Android?

**Comment by jainkuniya** [comment]
yup! on Android as well as iOS.
I have tested this PR on different devices.
(current sizes are really too big.)

**Comment by borisyankov** [comment]
That was a good effort but had drawbacks.
The emojis were too small - we have to handle both the unicode emojis and the image based emojis correctly.
I did experiment for an hour to solve it without these.
Have a look at #1729.
The width & height used is the maximum that will not misalign the lines (more than 18px and it makes the spacing larger). And then used transform: scale to make the emojis larger than that.

**Comment by jainkuniya** [comment]
cool! 👍

**Pull request closed without merging**
