### PR TITLE
Fire EVENT_UPDATE_MESSAGE_FLAGS on reading message.

### PR DESCRIPTION
**Pull request by jainkuniya**
So that unread count keeps on reducing on reading message.

This is more transparent than #1310 (alternative for #1310)

@borisyankov @kunall17 thoughts on this approach.

### CODE REVIEW

**Comment by borisyankov** [comment]
I definitely like this approach.
But you need to add debouncing. Just as we do it in the `queueMarkAsRead`.

**Comment by vishwesh3** [comment]
@borisyankov Updated 👍

**Comment by jainkuniya** [comment]
@borisyankov refactored a bit.
Let me know changes :)

**Comment by borisyankov** [comment]
I am not sure if this is still relevant?

**Comment by jainkuniya** [comment]
We still wants this.
(to give better user experience, that message are marked as read after reading them. It takes some time to do a API call and update on response)

**Comment by borisyankov** [comment]
To me, it still looks too complicated and the benefits are not worth the effort (there is more work needed before this would be ready to merge anyways). Closing for now, we can revisit later.

**Pull request closed without merging**
