### PR TITLE
deps: Upgrade to Jest 27

### PR DESCRIPTION
**Pull request by chrisbobbe**
Now possible after #5507, which bumped `jest-expo` to 45.

Blog post: https://jestjs.io/blog/2021/05/25/jest-27

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Some of the commits mention patches we've applied to the Jest libdef. To help explain what those are, here's the diff from `flow-typed/jest_v27.x.x.js` at the tip of this branch, to the upstream libdef for 27 as pulled locally and untouched:

```diff
diff --git flow-typed/jest_v27.x.x.js flow-typed/jest_v27.x.x.js
index b1c856aa4..0b5257e3e 100644
--- flow-typed/jest_v27.x.x.js
+++ flow-typed/jest_v27.x.x.js
@@ -248,8 +248,8 @@ type DomTestingLibraryType = {
   toHaveAttribute(attr: string, value?: any): void,
   toHaveClass(...classNames: string[]): void,
   toHaveFocus(): void,
-  toHaveFormValues(expectedValues: {| [name: string]: any |}): void,
-  toHaveStyle(css: string | {| [name: string]: any |}): void,
+  toHaveFormValues(expectedValues: { [name: string]: any, ... }): void,
+  toHaveStyle(css: string | { [name: string]: any, ... }): void,
   toHaveTextContent(
     text: string | RegExp,
     options?: {| normalizeWhitespace: boolean |}
@@ -277,7 +277,7 @@ type JestJQueryMatchersType = {
   toHaveText(text: string | RegExp): void,
   toHaveData(key: string, val?: any): void,
   toHaveValue(val: any): void,
-  toHaveCss(css: {| [key: string]: any |}): void,
+  toHaveCss(css: { [key: string]: any, ... }): void,
   toBeChecked(): void,
   toBeDisabled(): void,
   toBeEmpty(): void,
@@ -347,11 +347,6 @@ type JestExtendedMatchersType = {
    * @param {Array.<*>} members
    */
   toIncludeAnyMembers(members: any[]): void,
-  /**
-   * Use `.toIncludeSameMembers` when checking if two arrays contain equal values, in any order.
-   * @param {Array.<*>} members
-   */
-  toIncludeSameMembers(members: any[]): void,
   /**
    * Use `.toSatisfyAll` when you want to use a custom matcher by supplying a predicate function that returns a `Boolean` for all values in an array.
    * @param {Function} predicate
@@ -810,23 +805,11 @@ type JestObjectType = {
    */
   getTimerCount(): number,
   /**
-   * When mocking time, `Date.now()` will also be mocked. If you for
-   * some reason need access to the real current time, you can invoke
-   * this function.
-   *
-   * > Note: This function is only available when using modern fake
-   * > timers implementation
-   */
-  getRealSystemTime(): number,
-  /**
-   *  Set the current system time used by fake timers. Simulates a
-   *  user changing the system clock while your program is running. It
-   *  affects the current time but it does not in itself cause e.g.
-   *  timers to fire; they will fire exactly as they would have done
-   *  without the call to `jest.setSystemTime()`.
-   *
-   *  > Note: This function is only available when using modern fake
-   *  > timers implementation
+   * Set the current system time used by fake timers.
+   * Simulates a user changing the system clock while your program is running.
+   * It affects the current time but it does not in itself cause
+   * e.g. timers to fire; they will fire exactly as they would have done
+   * without the call to jest.setSystemTime().
    */
   setSystemTime(now?: number | Date): void,
   /**
@@ -1202,7 +1185,7 @@ declare var expect: {
     JestExtendedMatchersType &
     SnapshotDiffType,
   /** Add additional Jasmine matchers to Jest's roster */
-  extend(matchers: {| [name: string]: JestMatcher |}): void,
+  extend(matchers: { [name: string]: JestMatcher, ... }): void,
   /** Add a module that formats application-specific data structures. */
   addSnapshotSerializer(pluginModule: JestPrettyFormatPlugin): void,
   assertions(expectedAssertions: number): void,
@@ -1245,7 +1228,7 @@ declare var jasmine: {
   createSpyObj(
     baseName: string,
     methodNames: Array<string>
-  ): {| [methodName: string]: JestSpyType |},
+  ): { [methodName: string]: JestSpyType, ... },
   objectContaining(value: Object): Object,
   stringMatching(value: string): string,
   ...

```

**Comment by chrisbobbe** [comment]
(Pushed with the new generatedEs3.js that updated Babel gives.)

**Comment by gnprice** [comment]
Thanks for pushing through this!

Just pushed a commit-message tweak to describe that jsdom issue needing the workaround.

Reading the blog post: it sounds like we can drop `timers: 'modern'` from our Jest config, as that's now the default. Right?

Otherwise LGTM -- please merge at will.

**Comment by chrisbobbe** [comment]
> Reading the blog post: it sounds like we can drop `timers: 'modern'` from our Jest config, as that's now the default. Right?

The default is ['real'](https://jestjs.io/docs/27.x/configuration#timers-string), but I'd expect we can change it to 'fake' and it would default to the "modern" implementation.

**Comment by chrisbobbe** [comment]
Thanks for the review! Revision pushed, with a commit to switch the fake-timers setting.

**Comment by gnprice** [comment]
Thanks! Looks good -- merging.

**Pull request merged**
