### PR TITLE
deps: Run `yarn upgrade`.

### PR DESCRIPTION
**Pull request by chrisbobbe**
With a more specific upgrade pulled out into a commit just before, since we have a specific intention there.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
I kicked the tires on iOS and Android, and didn't notice anything off.

**Comment by chrisbobbe** [comment]
Rebased past #5230, the RN v0.65 upgrade.

**Comment by chrisbobbe** [comment]
Don't forget GitHub's handy "rich diff" feature when viewing `yarn.lock` changes:

image

**Comment by gnprice** [comment]
Thanks! Looks good; merging.

**Pull request merged**
