### PR TITLE
Fix issue with sending messages. Scroll to bottom on send

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Quick question about this -- if you're like 50 messages above the bottom and send a message, does this scroll you all the way down, or do we just scroll down when you were near the bottom in the first place?

Also, presumably we want to have most logic we have around scrolling down on send trigger on receive, not send, since otherwise you'll still miss things other people send, right?

**Comment by borisyankov** [comment]
Yeah, it does scroll you all the way down.
We already have @kunall17 outbox implementation where the message is locally prerendered!

**Comment by timabbott** [comment]
OK.  I think that's absolutely the right behavior if you're near the bottom, but the wrong behavior when you're more than a screen's height from the bottom of the feed.  Otherwise, sending a quick reply will lose your place (when catching up, I often find myself replying to several messages within a feed as I read through it).  

If you're not near the bottom, we may want a little notice that your message sent successfully and is further below.

**Comment by borisyankov** [comment]
Sounds good. And the notice, optionally, when clicked might scroll you to the bottom too.

**Pull request merged**
