### PR TITLE
Fixes #1744: Some emojis which are not updated results in undefined 

### LINKED ISSUE #1744: Some emojis which are not updated results in undefined
This is an example of `clinking_glasses` emoji name 

screen shot 2018-01-13 at 8 08 42 pm

### PR DESCRIPTION
**Pull request by kunall17**
Added the additional (new) emojis from the file `static/generated/emoji/name_to_codepoint.json'

### CODE REVIEW

**Comment by borisyankov** [comment]
Fix failing tests, please.

**Comment by kunall17** [comment]
Fixed :)

**Comment by borisyankov** [comment]
Looks good.

**Comment by timabbott** [comment]
It might be a good idea to move `codePointMap` to a separate JSON data file that's line-wrapped nicely, so it's easy to see a diff on this sort of update.

**Pull request merged**
