### PR TITLE
Enhancement: Improves Image Previews

### PR DESCRIPTION
**Pull request by pulkonet**
Minor design change, to have a comparable image preview to slack having high spatial efficiency. 
screenshot_20180305-061828
screenshot_20180305-061820

### CODE REVIEW

**Comment by borisyankov** [comment]
That is quite interesting!
Can you remove the padding from the image to match 100% the Slack screenshot?

@timabbott I think this is a good improvement. Maybe even worth considering for the web app. Do you like it for the mobile app?

**Comment by pulkonet** [comment]
Which padding are you talking about @borisyankov ?

**Comment by borisyankov** [comment]
The image in Slack starts at the beginning of the text 'Screenshot...'

**Comment by pulkonet** [comment]
Oh okay. I'll just do it and commit.

**Comment by pulkonet** [comment]
@borisyankov  I made the suggested changes and floated the image to left.

**Comment by borisyankov** [comment]
`float` is not the right approach. You need to make it as wide as the other text, not just left aligned.

**Comment by pulkonet** [comment]
@borisyankov I have corrected the float part and made it equally wide as other text. You can have a look.

**Comment by borisyankov** [comment]
That looks good now!

**Pull request merged**
