### PR TITLE
Slide drawers only from edges

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
I'm worried this will make it too difficult to open the slide drawers. Maybe we should use a value like 0.1 or 0.2?

**Comment by borisyankov** [comment]
The default one is 0.05

**Comment by neerajwahi** [comment]
I know but I personally find 0.05 really difficult to open.

Honestly, I'm not sure how much of a problem this is. I've never had an issue with accidental drawer opening while scrolling. Have you had that problem?

**Comment by timabbott** [comment]
Idunno, but given that we've had at least one of our small number of testflight users encounter this, probably worth adjusting it at least.  I think trying something in between like 0.25 and seeing if the user stops having the problem is a pretty reasonable test procedure; it's not like it'll be hard to change again later :)

**Comment by borisyankov** [comment]
0.25 is 1/4the of the screen, and 1/4th for the other drawer.
Overthinking this?

**Comment by neerajwahi** [comment]
I think @timabbott's approach seems pretty reasonable. Let's try it with 0.25 and if it's still a problem we can adjust further.

Have you had issues with this @borisyankov ?  I haven't encountered this problem and I've been using the app consistently on my phone, so I'm just curious

**Pull request closed without merging**
