### PR TITLE
icons: update react-native-vector-icons

### LINKED ISSUE #2209: Error in rendering terminal icon in dev auth screen.
screen shot 2018-04-03 at 7 09 07 pm

submitted https://github.com/oblador/react-native-vector-icons/pull/693

```
ExceptionsManager.js:73 Warning: Failed prop type: Invalid prop `name` of value `terminal` supplied to `Icon`, expected one of ["activity","airplay","alert-circle","alert-octagon","alert-triangle","align-center","align-justify","align-left","align-right","anchor","aperture","arrow-down","arrow-down-left","arrow-down-right","arrow-left","arrow-right","arrow-up","arrow-up-left","arrow-up-right","at-sign","award","bar-chart","bar-chart-2","battery","battery-charging","bell","bell-off","bluetooth","bold","book","bookmark","box","briefcase","calendar","camera","camera-off","cast","check","check-circle","check-square","chevron-down","chevron-left","chevron-right","chevron-up","chevrons-down","chevrons-left","chevrons-right","chevrons-up","chrome","circle","clipboard","clock","cloud","cloud-drizzle","cloud-lightning","cloud-off","cloud-rain","cloud-snow","codepen","command","compass","copy","corner-down-left","corner-down-right","corner-left-down","corner-left-up","corner-right-down","corner-right-up","corner-up-left","corner-up-right","cpu","credit-card","crop","crosshair","delete","disc","download","download-cloud","droplet","edit","edit-2","edit-3","external-link","eye","eye-off","facebook","fast-forward","feather","file","file-minus","file-plus","file-text","film","filter","flag","folder","github","gitlab","globe","grid","hash","headphones","heart","help-circle","home","image","inbox","info","instagram","italic","layers","layout","life-buoy","link","link-2","list","loader","lock","log-in","log-out","mail","map","map-pin","maximize","maximize-2","menu","message-circle","message-square","mic","mic-off","minimize","minimize-2","minus","minus-circle","minus-square","monitor","moon","more-horizontal","more-vertical","move","music","navigation","navigation-2","octagon","package","paperclip","pause","pause-circle","percent","phone","phone-call","phone-forwarded","phone-incoming","phone-missed","phone-off","phone-outgoing","pie-chart","play","play-circle","plus","plus-circle","plus-square","pocket","power","printer","radio","refresh-ccw","refresh-cw","repeat","rewind","rotate-ccw","rotate-cw","save","scissors","search","server","settings","share","share-2","shield","shopping-cart","shuffle","sidebar","skip-back","skip-forward","slack","slash","sliders","smartphone","speaker","square","star","stop-circle","sun","sunrise","sunset","tablet","tag","target","thermometer","thumbs-down","thumbs-up","toggle-left","toggle-right","trash","trash-2","trending-down","trending-up","triangle","tv","twitter","type","umbrella","underline","unlock","upload","upload-cloud","user","user-check","user-minus","user-plus","user-x","users","video","video-off","voicemail","volume","volume-1","volume-2","volume-x","watch","wifi","wifi-off","wind","x","x-circle","x-square","zap","zoom-in","zoom-out"].
    in Icon (at Icons.js:35)
    in IconTerminal (at ZulipButton.js:83)
    in RCTView (at View.js:78)
    in View (at ZulipButton.js:82)
    in RCTView (at View.js:78)
    in View (at Touchable.ios.js:25)
    in RCTView (at View.js:78)
    in View (at TouchableHighlight.js:306)
    in TouchableHighlight (at Touchable.ios.js:19)
    in Unknown (at ZulipButton.js:81)
    in RCTView (at View.js:78)
    in View (at ZulipButton.js:80)
    in ButtonNormal (at ZulipButton.js:129)
    in ZulipButton (at AuthButton.js:24)
    in AuthButton (at AuthScreen.js:150)
    in RCTView (at View.js:78)
    in View (at Centerer.js:41)
    in RCTView (at View.js:78)
    in View (at Centerer.js:40)
    in Centerer (at AuthScreen.js:144)
    in RCTScrollContentView (at ScrollView.js:793)
    in RCTScrollView (at ScrollView.js:889)
    in ScrollView (at Screen.js:76)
    in RCTView (at View.js:78)
    in View (at KeyboardAvoidingView.js:198)
    in KeyboardAvoidingView (at Screen.js:70)
    in RCTView (at View.js:78)
    in View (at Screen.js:67)
    in Screen (created by Connect(Screen))
    in Connect(Screen) (at AuthScreen.js:143)
    in AuthScreen (created by Connect(AuthScreen))
    in Connect(AuthScreen) (at SceneView.js:17)
    in SceneView (at CardStack.js:466)
    in RCTView (at View.js:78)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:78)
    in View (at CardStack.js:414)
    in RCTView (at View.js:78)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:78)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at AppWithNavigationState.js:39)
    in AppWithNavigation (created by Connect(AppWithNavigation))
    in Connect(AppWithNavigation) (at ZulipMobile.js:26)
    in Dummy (at StylesProvider.js:46)
    in StyleProvider (created by Connect(StyleProvider))
    in Connect(StyleProvider) (at ZulipMobile.js:25)
    in IntlProvider (at TranslationProvider.js:24)
    in TranslationProvider (created by Connect(TranslationProvider))
    in Connect(TranslationProvider) (at ZulipMobile.js:24)
    in AppDataFetcher (created by Connect(AppDataFetcher))
    in Connect(AppDataFetcher) (at ZulipMobile.js:23)
    in RCTView (at View.js:78)
    in View (at AppEventHandlers.js:89)
    in AppEventHandlers (created by Connect(AppEventHandlers))
    in Connect(AppEventHandlers) (at ZulipMobile.js:22)
    in Provider (at StoreProvider.js:22)
    in StoreHydrator (at ZulipMobile.js:21)
    in CompatibilityChecker (at ZulipMobile.js:20)
    in Unknown (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

### PR DESCRIPTION
**Pull request by ray-kraesig**
Update react-native-vector-icons to v6.6.0.

This updates Feather, in particular, to include the `terminal` icon which is used on the "Log in with dev account" option.

Fixes #2209. (See also PR #2892. This fixes the issue seen there by adding a call to a gradle file provided by `react-native-vector-icons`, as suggested in [their README](https://github.com/oblador/react-native-vector-icons/blob/07b156bb513dda45ca7468a92b4ffc04b072a588/README.md).)

### CODE REVIEW

**Comment by ray-kraesig** [comment]
Withdrawing for now. The upstream docs note that icons can be removed between releases, and I think we need tests to make sure none are – as it stands, it's entirely possible that this commit breaks an icon in some relatively obscure corner of the app.

**Comment by gnprice** [comment]
> Withdrawing for now. The upstream docs note that icons can be removed between releases, and I think we need tests to make sure none are – as it stands, it's entirely possible that this commit breaks an icon in some relatively obscure corner of the app.

Sounds reasonable. Want to make this comment over on #2209 as a reminder for when someone tackles the issue in the future?

Also perhaps your line above mentioning how you fixed the issue seen in #2892 .

**Comment by ray-kraesig** [comment]
The tests I was concerned about turn out not to be necessary, thanks to Flow types from upstream!

(On the other hand, a bit of `$FlowFixMe` _was_ necessary, thanks to inaccuracies in the Flow types from upstream. Oh well; can't win 'em all.)

**Comment by gnprice** [comment]
Merged -- thanks!

It turns out this doesn't quite yet ensure type-checking on the names used in `Icons.js` itself, though it does when we use our `Icon` (or `NavButton` etc.) elsewhere in the app. I experimented with this the other day when looking at your PR and have a branch that fixes that too.

**Pull request merged**
