### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pavankumarreddy8328**

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Hi, @pavankumarreddy8328! Could you please provide some reasoning / motivation for this change?

**Comment by pavankumarreddy8328** [comment]
I thought these change make some good reasonable understanding in zekyl
code of Read.me file. So, i changed that. I am also interested in
contributing towards zulip. Because i like this software and ideology. I
will also be more helpful in software development also.

Thankyou,
@pavankumarreddy8328

**Comment by agrawal-d** [comment]
Thanks for the PR @pavankumarreddy8328! I don't think these changes are necessary. However, you're welcome to make other changes that improve the app.

**Comment by chrisbobbe** [comment]
That's reasonable; thanks, @agrawal-d (and it's nice to see you again 🙂)!

Just in case there's been a misunderstanding, though—@pavankumarreddy8328, the changes proposed in this PR were just a few added blank lines to the README, with no changes to the actual text. Did you mean to propose more substantive changes, and they accidentally didn't make it into the PR? 🙂

**Pull request closed without merging**
