### PR TITLE
Fix: Narrow to correct sender on notification press

### PR DESCRIPTION
**Pull request by kunall17**
Crashing when application in dead state occasionally, but working perfect if app in background

### CODE REVIEW

**Comment by borisyankov** [comment]
Cool, for the working part ;)
Hope the 'WIP' is because you want to make it non-crashing before merge?

**Comment by kunall17** [comment]
Yeah, will fix it soon, also will be changing the formatting of notifications soon after this!

**Comment by kunall17** [comment]
Updated!

**Comment by borisyankov** [comment]
Looks good!

**Pull request merged**
