### PR TITLE
[WIP] Emoji Picker.

### PR DESCRIPTION
**Pull request by vishwesh3**
With tabs from react-navigation.
144ad0b7-2da9-4a89-bc9b-b92918cece94

### CODE REVIEW

**Comment by nashvail** [comment]
Wondering how this is different from the default emoji picker iOS/Android already provide.

**Comment by vishwesh3** [comment]
- Every Zulip server can have its own custom emojis. https://chat.zulip.org/#organization/emoji-settings 
- It depends on Keyboard we are using on device. It is not present on Nexus S 4.1.1 API 16 (tested on emulator)
c04e4d73-26b5-4ef8-81ed-fabca94d0289
- Other app's like Slack, FB etc have their on picker.
- In future we would like to sync recently used emojis with other platform (web etc.)

**Comment by nashvail** [comment]
@vishwesh3 understood, thanks!

**Comment by borisyankov** [comment]
@vishwesh3 nice prototype. We have lots of plans about a picker and I think the web app has something like this being worked on.
There were several other people that might have started on this feature. Please pause work on it before we discuss who will work on it.

**Comment by borisyankov** [comment]
Think if you want to take on the full Emoji implementation, it is a lot to do (not as fun as just doing the picker ;) )
It might be more important to do some stuff before that too, so it might be for phase 3 of the GSoC.

**Comment by borisyankov** [comment]
@vishwesh3 It might still make sense for you to work on the Emoji Picker, but let's wait for the actual implementation a bit more. There are a lot of things to discuss and consider before that, for example the tabs will be generated dynamically from the data we have etc.
But for now, continue on other tasks, as I think they are more important.

**Comment by vishwesh3** [comment]
sure :)

**Pull request closed without merging**
