### PR TITLE
[WIP]Add Help icon in Realm Screen

### PR DESCRIPTION
**Pull request by saketkumar95**
Some user friendly enhancement in the realm screen.

Needs suggestion , what to exactly add for help message in server URL? 

Also what to use? A tooltip or an actionSheet to display the message?

screen shot 2017-07-15 at 11 46 47 pm

### CODE REVIEW

**Comment by timabbott** [comment]
I would look at what other services like Slack that have different URLs for different sites use to document this concept.

**Comment by borisyankov** [comment]
Yes, indeed. We should explore way more what other apps do.

My concerns about adding 'help' are two fold:
 * no one reads help
 * we need to translate all of these

**Comment by timabbott** [comment]
This is definitely a problem that we need to improve.  We've had users email us asking what their "server URL" is when trying to figure out how to login.  But I agree we should see if we can make it more intuitive (e.g. changing the label) first.

I will note that Zulip has a particularly difficult challenge here compared to other apps, since we support any server URL, not just e.g. `subdomain.example.com`.  But I think we could probably do well with just showing the examples "zulip.example.com" and "organization.zulipchat.com" in the help.  

We could also consider having a way to enter "_____.zulipchat.com" on this form, since that is a super common case.

**Comment by borisyankov** [comment]
I fully agree with the problem needs fixing and partially agree with the idea of how to fix it.
I suggest we conceptually separate the URL entering into 'officially hosted' servers and 'custom/own' servers, instead of actually offering the full URL hints (though of course, the solution under the hood is exactly the same)

**Comment by borisyankov** [comment]
We will soon merge a reworked Realm screen, and this icon will not be needed.

**Pull request closed without merging**
