### PR TITLE
Handle back pressed in android

### PR DESCRIPTION
**Pull request by kunall17**
- [x] Pops narrow on back pressed on android

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
We are not going to implement this manually.
React Navigation is what is meant to do the navigating. On each narrow, we will be pushing a new route, and then the back button will automatically work.

It is too early to implement though. Nash has to prototype and we have to decide on the exact behavior.

**Comment by borisyankov** [comment]
Implementing this the correct way is also simpler.
Have a look at `MainScreenWithTabs.js` (which is not yet used) and if you want work on adding it there via pushing a new route.

**Comment by kunall17** [comment]
@borisyankov Hmm, i'll see already having a lot of things to work on! :)

**Comment by borisyankov** [comment]
Ok, I'll be finishing up the navigation-push approach. It is close to being done, and is way simpler than this...
Closing the PR then.

**Comment by kunall17** [comment]
@borisyankov I would say let's revive this PR for a temporary fix till we have the new navigation rework and fix for #906 
And the app exits on back press feels annoying!

**Pull request closed without merging**
