### PR TITLE
docs/push-notifications: Add missing step for setting bouncer url.

### PR DESCRIPTION
**Pull request by jackrzhang**
I split the changes into two commits for a cleaner diff.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks!

These steps are one-time setup, right? That is, once you do them once, you shouldn't have to do them again unless you build a new dev environment from scratch.

(Or more precisely, I think: as long as you're using the same `zproject/dev-secrets.conf` that was generated at provision time.)

These instructions sound a lot like this is something you have to do every time you want to run `tools/run-dev.py`, thanks to the "Before you run the server with `tools/run-dev.py`," bit. I think that impression is stronger after this change.

If these are one-time setup steps, want to try revising to make that clear? The "Now, follow ..." and thereafter are for *each* time, so some kind of separation is probably in order.

**Comment by jackrzhang** [comment]
Will do!

**Comment by jackrzhang** [comment]
Updated! @gnprice

**Comment by jackrzhang** [comment]
Updated!

**Comment by jackrzhang** [comment]
Hm, rereading this more, I think there are few more small tweaks that I want to make here. I'll post another comment when those are pushed :)

**Comment by jackrzhang** [comment]
@gnprice This can be reviewed.

**Comment by gnprice** [comment]
Thanks @jackrzhang ! Belatedly merged. :slightly_smiling_face:

**Pull request merged**
