### PR TITLE
api: Add new custom profile field type, "Pronouns"

### PR DESCRIPTION
**Pull request by gnprice**
Fixes: #5517

### CODE REVIEW

**Comment by gnprice** [comment]
Marked as draft just because I haven't yet tested this live.

**Comment by gnprice** [comment]
OK -- tested on CZO and all seems good.

**Comment by chrisbobbe** [comment]
LGTM, thanks! Please merge at will.

**Comment by gnprice** [comment]
Thanks for the review! Merging.

**Pull request merged**
