### PR TITLE
Add icon and polish splash screen

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
Why do we need 7 copies of the logo? All of the copies seem to be the same size

**Comment by borisyankov** [comment]
Different sizes. That is how iOS wants them.

**Comment by neerajwahi** [comment]
The assets in this PR are all the same size (512x512)

**Comment by borisyankov** [comment]
They will be optimized and will be different sizes when TDV does finalize the logo. No need to do the work on these?

**Comment by neerajwahi** [comment]
Yeah I agree we shouldn't do any work on these since they are temporary.

My question is, can we just include 1 binary file (`zulip-logo.png`) and link to that for each image size in `Images.xcassets/AppIcon.appiconset/Contents.json` instead of including 8 different binary files. It keeps the repo smaller.

**Pull request merged**
