### PR TITLE
Upgrade to React Native 0.57

### PR DESCRIPTION
**Pull request by borisyankov**
Based on RN 0.56 PR

Make sure to update to latest Android JDK.

### CODE REVIEW

**Comment by borisyankov** [comment]
@gnprice This PR is ready.

**Comment by borisyankov** [comment]
FYI: Just removed the `WIP` from the name of the PR.

**Comment by gnprice** [comment]
OK. Let's focus on getting the 0.56 upgrade completely in (so #2789, and I think that means #2994 first), before turning much attention to this again -- that will help some other ongoing work, and it'll also reduce the amount of stuff for us to keep track of in this PR.

**Comment by borisyankov** [comment]
The commits here are also ready to be reviewed.
I only thing that is not working OK is the `SpinningProgress` component that uses the `ART` library from the core `react-native` has issues rendering on Android. Confirmed with @jainkuniya that it does not work on his machine on a pristine 0.57 project too.
I will either figure out a fix, or replace the visual with something not using the ART lib.

**Comment by borisyankov** [comment]
All unmerged commits from here were appended to the 0.56 PR. Closing this one.

**Pull request closed without merging**
