### PR TITLE
[WIP] Added DrawerLayoutAndroid for android.

### PR DESCRIPTION
**Pull request by vishwesh3**
Now working on 
[ ] overlap drawer on StatusBar
[ ] close drawer when **Search Messages** or **Switch Account** (etc) is selected.

### CODE REVIEW

**Comment by borisyankov** [comment]
Ignore any StatusBar issues. Already resolved in #499

**Comment by borisyankov** [comment]
We are going to be replacing the NavigationExperimental component soon.
One of the best candidates for that is React Navigation
It also has a drawer that is universal:
https://reactnavigation.org/docs/navigators/drawer

We should investigate if it is currently performant on both iOS and Android and if it fits our needs, before coming up with our own custom solution.

**Comment by vishwesh3** [comment]
Tried with https://reactnavigation.org/docs/navigators/drawer, Same effect as android native drawer.
ezgif com-video-to-gif 30

**Comment by borisyankov** [comment]
Cool. We can implement in this PR later:
https://github.com/zulip/zulip-mobile/pull/521

I am not sure if React Navigation is bug-free enough, to replace our usage immediately, also lacks some configurability.

**Comment by borisyankov** [comment]
Hey, I'll close this PR, but keep the branch yourself if we decide we might need the native implementation.
But for now, we'll go with the drawers in React Navigation.

**Pull request closed without merging**
