### PR TITLE
fix: Show loading when narrowing from notification

### LINKED ISSUE #2714: Incorrectly shown 'no messages' after opening from a notification
When opening the app from a notification sometimes the following incorrect behavior happens:
 1.  'No messages' notice is shown
 2. In few seconds, the text disappears and the loaded messages are shown.

Expected behavior:
1. Loading indicator is shown
2. Messages loaded are shown

This happens if:
* app is started from a notification
* no messages were currently loaded for the narrow

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #2714

Narrowing from a notification is a special case, where we load
messages for the message narrow on startup.

We were not setting correctly the 'fetching' state and we were
displaying 'No messages' while actually loading new messages.

### CODE REVIEW

**Comment by gnprice** [comment]
Hmm, interesting, thanks!

There are a couple of other spots, both in this file, where we do a `getMessages`, await on that, and then when it's done we do a `messageFetchComplete` -- just like here.

Should those also add a `messageFetchStart`? If not, why not? I don't feel like I really understand the logic in this area.

**Comment by gnprice** [comment]
Also, would you file an issue to describe the bug you're talking about? Or link to an existing one, if there is one.

**Comment by borisyankov** [comment]
Yeah, I should have filled a bug report first. Done at #2714

**Comment by borisyankov** [comment]
The `backgroundFetchMessages` is intentionally not calling the `messageFetchStart` as it is intended as 'silent' fetch, though it seems we have removed any solo-use of this function and it can possibly be merged into `fetchMessages`.

The function `fetchRestOfInitialData` is fetching for the `PM` special narrow, which we do not display, and we are doing the special case of calling `tryUntilSuccessful`, basically ensuring this request succeeds (compared to many others that are OK to fail because of bad connection)

I think we should consider simplifying this code a bit more, as not much behavioral changes are needed, we can make it more clear (in future commits)

**Comment by gnprice** [comment]
> The backgroundFetchMessages is intentionally not calling the messageFetchStart as it is intended as 'silent' fetch, though it seems we have removed any solo-use of this function and it can possibly be merged into fetchMessages.

Aha, indeed. OK, just did that.


> The function fetchRestOfInitialData [...] we are doing the special case of calling tryUntilSuccessful, basically ensuring this request succeeds (compared to many others that are OK to fail because of bad connection)

Hmm. We're calling `tryUntilSuccessful` here in `fetchEssentialInitialData` too, right? So that doesn't seem like a difference.


> The function fetchRestOfInitialData is fetching for the PM special narrow, which we do not display,

I see. (I just went and traced what we do with `allPrivateNarrow`.)

OK, so that seems like a reason it might be harmless to leave out the `messageFetchStart` for that one. But would something go wrong if it were included?

One thing that would make this logic significantly easier to understand would be if it were possible to say that the rule is, messageFetchComplete is always paired with messageFetchStart, and in fact they always come together in a sequence with getMessages.

**Pull request merged**
