### PR TITLE
webView: Fix regression in getMessageNode.

### PR DESCRIPTION
**Pull request by jainkuniya**
When loop breaks due to curNode !== documentBody, then previous node is the message node.

### CODE REVIEW

**Comment by borisyankov** [comment]
Cool that you've caught the bug, but already fixed in an upcoming PR.
The better fix is changing the `if` to end like this:
`curNode.parentNode !== documentBody` (adding the `parentNode`)

**Comment by borisyankov** [comment]
BTW this PR will be including the completed sending of messages read IDs (so you don't work on it and duplicate the efforts)

**Comment by jainkuniya** [comment]
okay! cool 👍

**Comment by borisyankov** [comment]
Merged the fix. Closing this.

**Pull request closed without merging**
