### PR TITLE
Added Flowtypes to unreadSelectors

### PR DESCRIPTION
**Pull request by AB261**
Issues in focus: #2971, #3166

I went ahead and added some Selectors to the unreadSelectors that was referenced in #3166. So I did use the rebase-oriented workflow and removed the merge pull request commit that was in #3348.
Tests Ran:
- [x] yarn run test
- [x] npm run prettier-full

### CODE REVIEW

**Comment by AB261** [comment]
The travis-ci lint build failure error is currently on master itself so I am not sure what to do to make it pass.

**Comment by gnprice** [comment]
When the failure is in master, don't worry about it :slightly_smiling_face: -- we can see that too and act accordingly. Do mention it (as you did), though.

**Comment by gnprice** [comment]
Thanks @AB261 ! Merged as 7295f1ed3.

The PR will show as "closed" instead of "merged", because GitHub doesn't understand that that commit corresponds to this PR. Normally I handle that by updating the PR branch before pushing to master, but for some reason GitHub wouldn't let me do that on this PR.

Possibly it's because you used the `master` branch on your repo? Try using a different name next time (just make up any name related to what the PR does, like `unread-selectors`). That's also convenient because it helps you have several PRs open at once without them getting in each other's way :slightly_smiling_face: 

Would be glad to see a next PR taking care of the other selectors in that file! They look like they might be slightly more complex :wink: .

**Comment by AB261** [comment]
Thank you @gnprice for letting me know about the master issue! If there is an issue in master, I will bring it to light instead of haphazardly acting on it. Changing the branch name might solve the second problem so will do that for the next PR I send hopefully solving more difficult issues :smiley:.

**Pull request closed without merging**
