### PR TITLE
ui: Better align confirmation dialogs with the web app

### PR DESCRIPTION
**Pull request by chrisbobbe**
As discussed on CZO: https://chat.zulip.org/#narrow/stream/48-mobile/topic/confirm.2Fcancel.20modals/near/1401724

Here are screenshots of (I think) all our confirmation dialogs, after my changes. I've included Android just for the "Delete topic" one; let me know if you'd like to see more.

Hmm, one thing that stands out to me: should the title of the dialog (e.g., "Delete topic") have a question mark? If the web app consistently doesn't, then probably we shouldn't either, right?

Topic long-press menu, pressing "Delete topic":

Account picker, removing an account from the list:

Profile screen, pressing the "Log out" button:

Edit-stream screen, exiting with unsaved changes:

### CODE REVIEW

**Comment by alya** [comment]
> Hmm, one thing that stands out to me: should the title of the dialog (e.g., "Delete topic") have a question mark? If the web app consistently doesn't, then probably we shouldn't either, right?

Yeah, good observation! Let's remove the `?` from the titles to be consistent with the webapp pattern.

**Comment by alya** [comment]
Otherwise looks good to me!

**Comment by chrisbobbe** [comment]
Thanks for the review! Revision pushed, with that change.

**Comment by gnprice** [comment]
Good idea. Thanks all!

The changes all look good -- merging.

**Comment by chrisbobbe** [comment]
Thanks for the review!

**Pull request merged**
