### PR TITLE
typingSelectors: Fix selecting welcome bot in pm crashes the app

### PR DESCRIPTION
**Pull request by Maskedman99**
Issue was caused beacuse ```getUsersByEmail``` couldn't determine the user-id of Welcome Bot. This is fixed in the PR by making use of ```getAllUsersByEmail``` instead.

Fixes: #4067.

### CODE REVIEW

**Comment by ray-kraesig** [comment]
For reference, this was introduced in #4054.

LGTM at first glance, but pinging @gnprice and @agrawal-d for comments.

**Comment by agrawal-d** [comment]
Thanks for fixing this, @Maskedman99!
You can also modify the tests by adding some `CrossRealmBots` to `state.realm.crossRealmBots` in `src/typing/__tests__/typingSelectors-test.js`, by using `eg.makeCrossRealmBot`.
Looks good otherwise.

**Comment by ray-kraesig** [comment]
As this is an active crash bug that hasn't yet made it out to a release, I'll go ahead and add tests myself.

**Comment by gnprice** [comment]
Thanks all! Merged -- glad to have this caught and fixed.

I'd describe the underlying cause of this as the fact that we were using the `getUsersBy*` selectors here, which are in fact limited to just some users, instead of `getAllUsersBy*` which cover all users. Then the change in #4054 increased the impact of the bug by a lot, because it caused this code to start using the user data structures earlier and for all the users in the thread, instead of just the ones that are typing at the moment.

So I've added a commit on top which fixes that underlying bug too. This is a good example of how a bug which has a small direct impact because it's very hard to trigger in itself can be a "latent bug" which starts having a much bigger impact later on after an otherwise-innocent change to the code.

And then the *root* cause is more like: the `getUsersBy*` selectors sure sound like they're the thing to use, as they have the obvious, unmarked names. I'll file an issue for fixing that generally.

**Pull request merged**
