### PR TITLE
Remove ZulipStatubar from SearchScreen

### PR DESCRIPTION
**Pull request by saketkumar95**

### CODE REVIEW

**Comment by borisyankov** [comment]
Use 'active' tense in the title 'Remove' instead of 'Removes' and be more specific. Right now it seems like you are completely removing it, not just from one place.

**Comment by saketkumar95** [comment]
yeah actually I was correctly that only. I realised it after pushing. 
Improved 👍

**Comment by Sam1301** [comment]
@saketkumar95 I believe you also need to change the title of the pr here 👍

**Comment by borisyankov** [comment]
Fix the 'eslint' error.

**Comment by saketkumar95** [comment]
@borisyankov Done ! 👍

**Pull request merged**
