### PR TITLE
Flow: fix flow types for Subscriptions

### PR DESCRIPTION
**Pull request by ebouJ**
push_notifications property was missing. So I console subscription and figured other properties were also missing. Currently, they are not causing any error but figured anytime they are accessed the flow test will fail so I  decided to add them anyways. Please see attached

screen shot 2018-04-02 at 3 15 21 am

### CODE REVIEW

**Comment by borisyankov** [comment]
Please, fix the merge conflict.

**Comment by ebouJ** [comment]
@borisyankov I already did. I am not seeing any conflict on my side. I fix the merge conflict it was because of the clean you did. You removed DomElement so I fix it on my side. Please advice me accordingly on what the conflict is?

**Comment by borisyankov** [comment]
This PR looks outdated now?

**Comment by ebouJ** [comment]
@borisyankov yea I will go ahead and close it.

**Pull request closed without merging**
