### PR TITLE
Fix: stream tabs not rendered on Android.

### PR DESCRIPTION
**Pull request by vishwesh3**

### CODE REVIEW

**Comment by borisyankov** [comment]
Hmmm, why does this fix the issue?
All three changes are undesirable, so if we can fix the issue without doing them, this will be the best case.

**Comment by borisyankov** [comment]
I am not experiencing the issue you are describing.

**Comment by vishwesh3** [comment]
Tested on current master 00342df31836dafc3edafd2cddbcb614787c306f
I am still facing this on Android (only) (all 3 nested stream tabs are not rendered).
https://chat.zulip.org/#narrow/stream/mobile/subject/zulip-mobile.20.2F.20master/near/280585
screen shot 2017-09-20 at 10 20 44 am

**Comment by vishwesh3** [comment]
>Hmmm, why does this fix the issue?

https://github.com/react-native-community/react-native-tab-view/blob/ef4b76bd9c5f857bec664c75f03fe4dc647a8be4/src/TabViewAnimated.js#L50

For different platforms there are different components. For Android it is `TabViewPagerAndroid` which is using `ViewPagerAndroid`. I thinks this causing problem.

>All three changes are undesirable, so if we can fix the issue without doing them, this will be the best case.

Tried different combination of this 3 properties, nothing other seems to work. Should we only add this for Android?

**Comment by borisyankov** [comment]
In my testing, this did not show and was working, check if some `flex: 1` is missing?
But another just as serious issue manifested - you can not tap on any item.
That is a critical issue. If you can resolve today... if not I'll try to fix, as it is a blocker.

**Comment by borisyankov** [comment]
Thanks for figuring out the problem. 

We need a better fix as your research suggested. Another PR addressed this issue so I am closing this.

**Pull request closed without merging**
