### PR TITLE
ZulipMobile: Add and use RootErrorBoundary.

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes: #4584

### CODE REVIEW

**Comment by chrisbobbe** [comment]
See screenshots/discussion at https://github.com/zulip/zulip-mobile/issues/4584#issuecomment-812172389.

**Comment by chrisbobbe** [comment]
Hmm, potentially interesting: Sentry provides a ready-to-use component [`Sentry.ErrorBoundary`](https://docs.sentry.io/platforms/javascript/guides/react/components/errorboundary/). It looks like it was designed for use on the web, so in particular its built-in [user feedback widget](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/) hasn't been working for me.

But when I pass a function for the `fallback` prop, I get the Sentry event ID along with the error info.

**Comment by chrisbobbe** [comment]
> It looks like it was designed for use on the web, so in particular its built-in [user feedback widget](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/) hasn't been working for me.

Though it looks like it might not be too hard to set something like this up manually: https://github.com/getsentry/sentry-react-native/issues/500

**Comment by gnprice** [comment]
Looks good, thanks! Merging.

I have one bit of UI feedback that I think is worth doing (naturally we don't want to spend a lot of time on this UI): instead of having a lot of text in the button:
image

a more idiomatic thing to do would be to have some text to say most of that, and then have the button very concisely say what the button itself will do. Like maybe "Copy details". See e.g.:
https://material.io/components/buttons#text-button

But given that I'd like to ship a beta today with #4588, and it'd be good to include this in that too, that is not something worth blocking on and instead can be a small followup :slightly_smiling_face:

**Comment by gnprice** [comment]
(Also I made a tiny formatting tweak to the output:
```diff
 Component Stack:
-
 ${
```
because it seemed like empirically there were one too many blank lines in there. My screenshot just above reflects that change.)

**Comment by chrisbobbe** [comment]
Thanks for the review!

**Pull request merged**
