### PR TITLE
Correspond prefixes in modules' names to the name in the state.

### LINKED ISSUE #3043: Rename `accounts`, `narrows`, and `messages` modules to match the state.
Copying over @gnprice's [comment from #3008](https://github.com/zulip/zulip-mobile/pull/3008#issuecomment-429018194):
> I agree with @jackrzhang that we should have the prefix in the module's name correspond to the name in the state. There are a few places we don't currently respect that:
>```
>accounts -> accountReducers
>narrows -> narrowReducers
>messages -> messageReducers
>```
> So we should just rename all those modules to match the state.

I'd like to claim this.

### PR DESCRIPTION
**Pull request by jackrzhang**
Resolves #3043.

### CODE REVIEW

**Comment by borisyankov** [comment]
That looks potentially ready to merge.
@jackrzhang could you resolve the merge conflicts?

**Comment by jackrzhang** [comment]
Thanks for the ping! 

The GitHub UI is showing this popover; I'm curious what conditions are causing it:

image

**Comment by jackrzhang** [comment]
The conflicts have been resolved! Although it's unclear to me what exactly was conflicting.

On my local machine, I ran `git pull --rebase upstream master`:
```
From https://github.com/zulip/zulip-mobile
 * branch              master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Rename accountReducers to accountsReducers.
Applying: Rename accountSelectors to accountsSelectors.
Using index info to reconstruct a base tree...
M	src/pm-conversations/pmConversationsSelectors.js
M	src/typing/typingSelectors.js
Falling back to patching base and 3-way merge...
Auto-merging src/typing/typingSelectors.js
Auto-merging src/pm-conversations/pmConversationsSelectors.js
Auto-merging src/account/__tests__/accountsSelectors-test.js
Applying: Rename narrowReducers to narrowsReducers.
Applying: Rename narrowSelectors to narrowsSelectors.
Applying: Rename messageReducers to messagesReducers.
Using index info to reconstruct a base tree...
M	src/message/messageReducers.js
Falling back to patching base and 3-way merge...
Auto-merging src/message/__tests__/messagesReducers-test.js
```

Then `git push origin, rename-to-match-state`, which was rejected:
```
To https://github.com/jackrzhang/zulip-mobile.git
 ! [rejected]          rename-to-match-state -> rename-to-match-state (non-fast-forward)
error: failed to push some refs to 'https://github.com/jackrzhang/zulip-mobile.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

And then I force pushed with `git push origin -f rename-to-match-state`.
```
Counting objects: 113, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (112/112), done.
Writing objects: 100% (113/113), 22.37 KiB | 2.49 MiB/s, done.
Total 113 (delta 80), reused 0 (delta 0)
remote: Resolving deltas: 100% (80/80), completed with 41 local objects.
To https://github.com/jackrzhang/zulip-mobile.git
 + f624c8e4...8604993c rename-to-match-state -> rename-to-match-state (forced update)
```

**Comment by gnprice** [comment]
Thanks @jackrzhang ! Merged.

Remind me on Monday and I'll be glad to explain what Git understands about file renames :smile:

**Pull request merged**
