### PR TITLE
Handle narrow to unsubscribed stream.

### PR DESCRIPTION
**Pull request by vishwesh3**
- [x]  Create UI.
18361530_792155470978263_871307726_n
18361626_792156557644821_1584327350_n

- [x]  Handle subscribe button.

- [x] Handle stream events.

### CODE REVIEW

**Comment by borisyankov** [comment]
I don't think having so much custom code for handling the 'no messages' and 'not subscribed' case is worth it.

**Comment by vishwesh3** [comment]
refactored litter bit. What other approaches are you thinking of?

**Comment by borisyankov** [comment]
Other high-level concerns: we are adding translations very soon, and you can not assume that a text that fits in some space in English, will fit in the same space when translated. We should also be considering different sizes of device screens.

**Comment by vishwesh3** [comment]
yes, will make sure that it looks good in all languages on different screen sizes.

**Comment by vishwesh3** [comment]
Updated
PR includes
	Handle narrow to unsubscribe/invalid stream.  …
-Disable switch in Subscription screen.
In case when stream is not subscribed
and stream is invite only.
fix:#568

-Ensure stream is valid  before narrowing from link in messages.
If not valid then show message in snackbar.
18447868_794071080786702_741695338_n

-Narrow to home if narrow in cache becomes outdated (stream deleted).
-Handle stream update, create, remove, events.
-Added tests for stream events.

Fix:#555

**Comment by borisyankov** [comment]
Hey, let's move this PR along. Can you rebase, please? Thanks.

**Comment by vishwesh3** [comment]
Updated

**Comment by vishwesh3** [comment]
@borisyankov Rebased 👍 .

**Comment by vishwesh3** [comment]
splitting this PR :)

**Comment by vishwesh3** [comment]
closing this. Only one part remaining is https://github.com/zulip/zulip-mobile/pull/735

**Pull request closed without merging**
