### PR TITLE
Fix: safe-area-insets event is fired on every launch.

### PR DESCRIPTION
**Pull request by jainkuniya**
Safe area parameters are only dependent on device, so we can store it one time and use it in future instead of recalculating.

### CODE REVIEW

**Comment by borisyankov** [comment]
Hmmm. Does that hold true when you change orientation?

**Comment by vishwesh3** [comment]
yup! updated 👍 
tested on iPhone x and iPhone 6

**Comment by vishwesh3** [comment]
@borisyankov Rebase 👍 
Ready to go in 🏃

**Comment by borisyankov** [comment]
I know you've put a lot of effort into this.
It has become rather complex though.
I am questioning if the benefit (which seems small) is worth all this.

**Comment by vishwesh3** [comment]
I thinks it worth including it. Because on every launch native part is calculating and sending it to js one. And on the same time we are sending data to native part to render. Although it has little benefits, but have benefit :). Also listener on native side have some cost.

**Comment by borisyankov** [comment]
I continue to think it is too much code for too little benefit. 
We can always reconsider it later, but closing this PR for now.

**Pull request closed without merging**
