### PR TITLE
Rework ComposeMenu to have menu construction like message action sheet

### PR DESCRIPTION
**Pull request by kunall17**
It changes the menu construction & hides the 'Toggle compose tools' in the topic narrow

### CODE REVIEW

**Comment by borisyankov** [comment]
Don't spend efforts on this. It will be completely rewritten to not use an action sheet.
This is a rework that encompasses the 'full screen' editor and that is why I have not moved on with it yet.
It will be a custom menu with icons or something that slides from the bottom - not a priority in the next 2 weeks.

**Comment by kunall17** [comment]
Ok, didn't knew about your plan, let's discuss it sometime? 
I think the priority should be Google oAuth

Also let's merge this one as the Toggle compose tools in topic view seems confusing!

**Comment by borisyankov** [comment]
Ok, I'll merge this, but we should make an effort to coordinate more on stuff to-do to avoid extra work. Sounds good?

**Comment by kunall17** [comment]
Yup, sounds good!

**Pull request merged**
