### PR TITLE
Deep HTML Message Render

### PR DESCRIPTION
**Pull request by borisyankov**
* Rendering logic is completely reworked.
* Tree is parsed deeply (not just one layer)
* Cascading css styles
* Custom tag renders for multiple tag types
* Code plain and color formatting supported
* Even tables are rendered ;)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
Thanks @borisyankov ! Reviewing this..

I just had this thought (for future work):
We could fetch all messages as Markdown and render that instead of HTML. The advantage there is that there's less variation to support in the Markdown format, and we could easily support optimistic updates (where sending a message immediately shows up in the stream before the server has processed it).

@timabbott do you see any downsides with that strategy? I know that `echo.js` in the Zulip web app defers to server rendering in certain cases (such as embedded images or tweets), but it seems like we should be able to support those cases pretty easily.

**Comment by borisyankov** [comment]
I am not sure if everything has markdown alternative. 
Maybe it is a combination of html+css and markdown when the user have typed in.
In that case it wouldn't make sense.

**Comment by timabbott** [comment]
Doing markdown rendering on the client has a few downsides:
* Performance -- If there are messages that are expensive to markdown render, you pay that on every load, rather than just once on the server.  Probably not a big deal since markdown processors are usually fast, but can be important if a lot of messages have complex syntax or the device is slow.  May also be relevant with features like LaTeX support that might exist only on the backend.
* Inline link/tweet/open graph previews -- The client basically can't handle these since they involve doing multi-second API requests to other services, which have rate limits, etc.  One could imagine refactoring the backend to support sending the raw markdown + the data on what one gets back from links needed to handle these, but that feels like a pain, and regardless, the link processor is the most complex part of our markdown customizations.

We will probably end up wanting to import the Zulip webapp's marked.js and maybe parts of echo.js implementations for doing optimistic updates anyway (I wouldn't want to try to duplicate the logic), so doing it on the backend doesn't really save code duplication.  

http://zulip.readthedocs.io/en/latest/markdown.html is a useful reference on how things work on the web.

**Comment by neerajwahi** [comment]
@timabbott In this case I imagine rendering the markdown will actually improve performance, because we have to parse the HTML anyway (into React Native components) and markdown is probably faster to parse.

Yeah the inline previews are pretty hard. It might be nice if we could augment the markdown with those, but probably not worth it for now.

**Pull request merged**
