### PR TITLE
Baby steps toward detangling `ComposeBox`.

### PR DESCRIPTION
**Pull request by chrisbobbe**
Including a new comment on the `subject` field on our `Message` type, and fixes for some at least latent (though possibly not-super-common?) bugs.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Just rebased across #4506.

**Review by WesleyAC — APPROVED** [review]

**Comment by WesleyAC** [comment]
Thanks for the detailed commit messages :)

I wouldn't have been able to figure out what was going on here without that, it was quite a rube goldberg machine to set the topic :grimacing:

**Comment by chrisbobbe** [comment]
Thanks for the review! Merging. (@gnprice, hopefully it's OK to skip your review, but this has been open for a bit. Also, I've tried to leave a careful trace of my thought process in the commit messages, in case this causes new bugs that don't camouflage into the component's existing bugs. 🙂)

**Comment by gnprice** [comment]
Yeah, sorry I let this sit for a while. I just read through it now -- that was indeed quite a complicated sequence! Thanks for cleaning up this bit of the logic, and leaving that careful trace of your analysis.

**Pull request merged**
