### PR TITLE
First message request replaces cached messages

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes an issue with invalidating cached messages

* Add a new parameter to MESSAGE_FETCH_SUCCESS to optionally replace existing messages
* Initial message requests replace cached messages

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Rather than deleting all of the cached messages, how about we let the last 50 (maybe more or less) reside and clear the rest? 
Many a times we need to scroll up to see what was going on, so its better than deleting all the messages?

**Comment by borisyankov** [comment]
We will probably do something like this in the future, though realistically that looks good enough to me for a long time.

We need at least two more things:
* ways to clean up messages from cache, or it will grow indefinitely
* we need a way to determine how many messages are missing, likely needs additions to the backend
* needs to handle the case where we can load missing message since last time vs having too many messages

... and so on, and so on.

**Comment by borisyankov** [comment]
Looking to merge this ASAP, as not having it causes a bug that you might not realize yet (messages grow indefinitely).

**Comment by borisyankov** [comment]
@nashvail and/or @kunall17 just looking for some sanity check on this PR, and want to merge (without it we might be having bugs)

**Pull request merged**
