### PR TITLE
outboxActions: Show dialog if message send fails with informative ApiError

### PR DESCRIPTION
**Pull request by chrisbobbe**
outboxActions: Show dialog if message send fails with informative ApiError
    
    This is our minimal support for #5870 in this legacy codebase.
    Supporting it properly with a client-side check of the setting is
    more effort than we can spare right now.
    
    Probably more error handling is called for in general (like for
    network or server issues), but #3881 ("Sending outbox messages is
    fraught with issues") is complicated and it's probably best to leave
    it be.
    
Fixes: #5870

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Screenshots from a dev server:

| a | b | c |
| --- | --- | --- |
| EF938FE1-8815-4B54-AB9A-45FB8294E8A9 | BBA46F74-F912-492C-B47C-F2FD3B771839 | 99F52821-D8C8-4B5B-B4A1-AFFB4507798E |

**Comment by alya** [comment]
Can we get a more accurate error in the non-authorized case? Like the webapp front end error:

image

**Comment by chrisbobbe** [comment]
Thanks for catching this; `#api design` thread: https://chat.zulip.org/#narrow/stream/378-api-design/topic/new.20DM.20settings.3A.20a.20server.20error.20message.20seems.20wrong/near/1882954

**Comment by gnprice** [comment]
Thanks! LGTM; merging.

Definitely would be good to fix that error message; we'll pursue doing so via that `#api design` thread.

I made one tweak to the commit message, elaborating on why we're not doing the full-featured version:

         This is our minimal support for #5870 in this legacy codebase.
         Supporting it properly with a client-side check of the setting is
    -    more effort than we can spare right now.
    +    more effort than we can spare here, because it requires implementing
    +    the group-based permissions system.

**Comment by chrisbobbe** [comment]
Makes sense; thanks!

**Pull request merged**
