### PR TITLE
Implementation of ios push notifications

### PR DESCRIPTION
**Pull request by kunall17**
- Currently untested, due to some issues of apns certificate on chat.zulip.org (Will be resolved soon) 
- Not sure if Bundle ID should be the same as the certificate ID, but a provisioning team needs to be create to test this on a device
screen shot 2017-06-26 at 6 05 16 am
- The displaying content part of the notification is mostly related from the server (unlike GCM), hence a PR will be landing there.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by borisyankov** [comment]
At a first glance the code looks ok. I'll do a more thorough review and merge if OK.
Make sure the code does not crash the app even if the server has no support for notifications, both for iOS and Android, because we might have to connect to older servers that don't have that.

**Comment by borisyankov** [comment]
Rebase and try to test and improve the code and prepare it for the server with a certificate. Likely we will have it very soon and then it will be highest priority to make it work.

**Comment by borisyankov** [comment]
Make sure tests pass.

**Comment by kunall17** [comment]
Done

**Comment by borisyankov** [comment]
Nice. Getting it in.

**Pull request merged**
