### PR TITLE
Provide JSDoc documentation for all `common` components

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by gnprice** [comment]
This is clearly a huge improvement, so given that it's all in comments and the downside risks on my concerns are low, I'm going to go ahead and merge all these changes in the interest of keeping you unblocked for further work in this direction.

For the reasons mentioned above, I'm pretty sure I'd like to cut out the brackets-for-optional convention and just let optional/not-optional be one of the things the reader learns by looking at the types. That can be a followup commit to sweep through and convert the existing comments. (If I were getting to this at an hour when you're still working, I might ask you to do that before I merge, but I'm not and it's not worth the added night of latency.)

I'm waffling on the question of whether to describe routine things like `onPress` or `color` when they have the obvious meaning. I'd be interested in more thoughts/reasoning on that. A sort of middle option might be to just mention such a prop so it shows up in the list:
```
 * @prop onPress
```
but not say anything except where there's something interesting to say. Whatever we end up with there, if it's different from these commits we can pretty easily do a sweep later.

I'll leave this PR open (rather than close it as "merged") because it seems like a helpful thread for at least a bit more discussion -- as well as for adding more great commits like these!

**Comment by gnprice** [comment]
Collecting some style-guide advice for comparison, [Google's says](https://google.github.io/styleguide/jsguide.html#jsdoc-method-and-function-comments):
> Method, parameter, and return descriptions (but not types) may be omitted if they are obvious from the rest of the method’s JSDoc or from its signature.

[Flutter's says](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-useless-documentation):
> If someone could have written the same documentation without knowing anything about the class other than its name, then it’s useless.
> 
> Avoid checking in such documentation, because it is no better than no documentation but will prevent us from noticing that the identifier is not actually documented.

and then follows with a very nice list of prompts to think about to think of useful information to write down. (In general, one of the things that has most impressed me in poking a bit at Flutter is their extremely high-quality developer documentation.)

And [a Mozilla style guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#General_C.2FC.2B.2B_Practices) refers to a JavaDoc guide, which [has this](https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#styleguide) on the subject:
> The best API names are "self-documenting", meaning they tell you basically what the API does. If the doc comment merely repeats the API name in sentence form, it is not providing more information.

I think a fair synthesis of what all of those say on this subject, and a rule I'm pretty happy with, is:
* If you're documenting a component, include all its properties as `@prop` entries.
* Don't force yourself to write a text description for every property; only write where you have something interesting to say.
* Repeating what the name says, or something you could have written without knowing anything other than the name of the component and of the prop, is boring; better to just leave that one blank.

How's that sound?

**Comment by borisyankov** [comment]
You are right, maybe we don't want to describe all props after all. I think it is OK to provide a one-liner for the obvious ones. I felt a bit weird describing `onPress` events, though quite often there are details about obvious events that might be useful. I think leaving it with no description sometimes is clearly the sane option.

It seems the JSDoc preview is not configurable, but maybe they will accept a PRs if we come up with better formatting. I think the relevant file is this one:
https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/utils/previewer.ts

About the optional params - even with the apparent mismatch, they are actually more correct than Flow will let you believe. `Props` refers more towards what the component expects to receive than to what is given to the component as `<Component someProp={valueHere} />`. The discrepancy comes from the `defaultProps` we are giving to the component. Since we are providing defaults for most `Avatar` props they are truly optional. They are not typed as `someProp?: type` because they are guaranteed to have some default value, so they are not optional in that sense to the internal component code.

I think I agree 100% with the last comment it belongs do the documentation 👍

**Comment by gnprice** [comment]
(I did in fact merge these back several weeks ago when I made the previous comments, as c6b2aa482 and ancestors. Not sure why I left this "open" instead of "merged"; maybe I thought you'd send further changes here? Anyway, new PRs seem like a better way to do that, so let's close this one.)

**Comment by gnprice** [comment]
> About the optional params [...] The discrepancy comes from the defaultProps we are giving to the component. Since we are providing defaults for most Avatar props they are truly optional. They are not typed as someProp?: type because they are guaranteed to have some default value, so they are not optional in that sense to the internal component code.

Oh hmm, I see.

Well, I'm still concerned about having a lot of boring information that we maintain ourselves without automated checking -- that's generally a recipe for stuff becoming wrong. But glad to see why this isn't yet an example. :-)

**Pull request closed without merging**
