### PR TITLE
[WIP] Use particular narrow corresponsing chatScreen.

### PR DESCRIPTION
**Pull request by jainkuniya**
for #2019

Till now I have tired 3 approaches.

Approach 1: partially implemented: https://github.com/jainkuniya/zulip-mobile/tree/issue-re-render-o1
Reconstruct selector and call individual selector, before calling  main selector: later I realised, it will add lots of overhead.

Approach 2: very partially implemented: https://github.com/jainkuniya/zulip-mobile/tree/issue-re-render-o2
Rewrite `getActiveNarrow` selector, to get last narrow from the state. But the problem of global narrow will still persist.

Approach 3: almost done: https://github.com/jainkuniya/zulip-mobile/tree/issue-re-render-o3 : This PR
Wrap selector in a function 
https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

### CODE REVIEW

**Comment by jainkuniya** [comment]
Ready for initial review.
This fixes all the issues listed in #2019.

**Comment by borisyankov** [comment]
Great analysis of the issue, thorough research of possible solutions and lots of rework.
You are going in the right direction.

**Comment by borisyankov** [comment]
I did a thorough review line-by-line and it seems almost everything is correctly done on macro level.

Do rename anything that says 'getSomethingForActiveNarrow' or 'CurrentNarrow' to just 'ForNarrow' so it refelcts more correctly what is going on.
I suspect you need to implement all `// TODO` stuff too. Keep working on them, you are doing it right.

And last - we need to fix all tests, and add tests that catch the current bugs.

Think of ways to compartmentalize some of the changes.

And... lots of manual testing of the app. I will help with that a lot tomorrow.
These are lots of changes but we need to make them and we need to make them fast.

**Comment by jainkuniya** [comment]
Pushed some more commits, now its in stable state.
Remaining tasks (noting down so that we can have track on them):

- [ ] Write/fix Tests.

- [ ] Take cares of TODO

- [ ] Renaming & code refactoring.

Will complete it by EOD today.

**Comment by jainkuniya** [comment]
Updated 👍

**Comment by borisyankov** [comment]
Looks good!
I did thorough pass through the code and tested a lot.
It seems it fixes a lot of the issues!
I am merging it now, but we need to test in the next 1-2 days heavily to ensure so much code change did not break anything (it likely did!).

**Pull request merged**
