### PR TITLE
Fix spacing in sidebar

### PR DESCRIPTION
**Pull request by obnoxiousorc**
Fix for big spacing in sidebar (between Home, Private Messages, etc.).

Fixes part of issue #212.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@obnoxiousorc, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by timabbott** [comment]
@obnoxiousorc thanks for working on this!  Can you provide some more explanation in your comment message about the bug being fixed?  Check out the Zulip commit message guidelines for more details: https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages

Also, you need to sign the Dropbox CLA before we can take your submission/

**Comment by borisyankov** [comment]
The commit looks reasonable. 
Need to test it on iOS, because there is some small differences in how the layout works between Android and iOS and hopefully this does not inadvertently break iOS.

**Comment by neerajwahi** [comment]
Thanks for the contribution @obnoxiousorc. While we review it could you sign the Dropbox CLA above (which we need before merging)?

**Comment by obnoxiousorc** [comment]
Yep, I'll get it signed today or tomorrow (most likely with my company). Sorry that it's taken so long!

**Comment by obnoxiousorc** [comment]
Okay, just signed the CLA.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@obnoxiousorc, thanks for signing the CLA!

**Comment by neerajwahi** [comment]
Thanks for the contribution @obnoxiousorc !

It looks like this breaks the layout on iOS: 
screen shot 2017-01-29 at 4 13 53 pm

**Comment by obnoxiousorc** [comment]
Uh oh - I'll have to find a way to test on both iOS and Android for layout fixes then. Thanks for letting me know, I'll see if I can figure that out sometime soon!

**Comment by neerajwahi** [comment]
:+1:

**Comment by borisyankov** [comment]
This issue was fixed in another PR.

**Pull request closed without merging**
