### PR TITLE
Fix: Message being requested in a loop on Android.

### PR DESCRIPTION
**Pull request by Sam1301**
Did a bisect and found it was this change that caused it. 
Not sure why this happened :/

### CODE REVIEW

**Comment by borisyankov** [comment]
... and the funny thing is the previous change was done by you? :)

I think we need to fix this somehow without removing the sticky headers.

**Comment by Sam1301** [comment]
Yeah, I guess I couldn't test the changes back then because the android build was broken after latest upgrade.
Sticky headers need to be removed on android since we need the clipped views optimisation. Both can't be accommodated after upgrade to RN 47.

**Comment by borisyankov** [comment]
What if we turn off the clipped views? How significant is the perf difference?

**Comment by Sam1301** [comment]
The memory consumption increases with the number of messages (same bug which we used to get 2 months back when clipped views optimisation wasn't working) and the app crashed for me on a device after scrolling through ~600 messages.

**Comment by borisyankov** [comment]
So.... one more reason to use SectionList 👍

**Pull request merged**
