### PR TITLE
apiTypes [nfc]: Cut some require cycles.

### PR DESCRIPTION
**Pull request by chrisbobbe**
Unfortunately, we'll need to do more—but this is a fairly straightforward bit of progress I think we've landed on.

From [discussion](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M3745.20Server.20version.20to.20Sentry/near/930324).

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Heh, actually, debatable whether this is NFC—as it's meant to fix a bug.

**Comment by gnprice** [comment]
This change looks good, thanks!

Just one quibble, in the commit message: this doesn't actually cut many cycles. We go from 18 cycles reported by `tsort`, down to 17:
```
$ tools/tsort-modules pairs | tsort 2>&1 >/dev/null | grep -c 'contains a loop'
17
```

Or in terms of whole cycle-blobs (the technical term is "strongly-connected components" or SCCs), it actually increases the number of them... by breaking up the biggest of them, with 2 of its 12 modules moving off into their own tiny cycle-blob and 3 others getting freed entirely, leaving 7 behind.

This is still quite helpful, though! For basically the reason described in the body of the commit message: it prevents an anticipated future import from creating a much larger import cycle-blob, and triggering that Flow bug. Details [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/import.20cycles/near/1057133).

**Comment by chrisbobbe** [comment]
Thanks for the review and analysis! I just pushed some tweaks to the commit message; please take a look.

**Comment by gnprice** [comment]
Thanks! Merged.

**Pull request merged**
