### PR TITLE
Use translated strings in message action sheet

### PR DESCRIPTION
**Pull request by kunall17**
After this gets merged will convert the other local strings as well!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Updated

**Comment by borisyankov** [comment]
Not a fan of how it is implemented.
I would have preferred for everything to go through React Intl.
Give me few days, I'll research the topic more and give you a more thorough review and suggestions.

**Comment by kunall17** [comment]
@borisyankov Updated the branch, with usage with react-intl!

**Comment by kunall17** [comment]
@borisyankov Reminder for this one!

**Comment by kunall17** [comment]
@borisyankov Rebased and fix merge conflicts!

**Comment by kunall17** [comment]
@borisyankov Is there any blocker with this PR ?

**Comment by borisyankov** [comment]
Sorry for the delay, had to research if this is the proper way to implement this.
I think it is good to merge, after the rebase ;)

**Comment by kunall17** [comment]
Updated!

**Pull request merged**
