### PR TITLE
removing `hideIfOffline` prop[nfc]

### PR DESCRIPTION
**Pull request by abhi0504**
removing `hideIfOffline` prop will show a grey box for the offline users

### CODE REVIEW

**Comment by chrisbobbe** [comment]
@abhi0504 I don't see how this is a complete solution for #4575 based on its description. Could you help me with that?

**Comment by abhi0504** [comment]
Thanks @chrisbobbe for review 

- It basically tells us about the user (offline or online) I accept the fact that it doesn't not resolves #4575 completely its just can be a enhancement 😊 
- I have resolved all the CI failures

**Comment by chrisbobbe** [comment]
> I accept the fact that it doesn't not resolves #4575 completely its just can be a enhancement 😊

Ah, OK! Enhancements are nice. 🙂 But let's be sure not to say `Fixes: #4575`, either here on GitHub or in the commit message, then, since it's not true. 😉

**Comment by chrisbobbe** [comment]
> * It basically tells us about the user (offline or online)

Could you talk more about the "why" for this change? It looks like the prop was set to `true` in #2545; do you think that was a mistake, or is there anything else that stands out from reading the history?

**Comment by abhi0504** [comment]
> > I accept the fact that it doesn't not resolves #4575 completely its just can be a enhancement 😊
> 
> Ah, OK! Enhancements are nice. 🙂 But let's be sure not to say `Fixes: #4575`, either here on GitHub or in the commit message, then, since it's not true. 😉

Sure just removing that  `Fixes: #4575` tag

**Comment by abhi0504** [comment]
> > * It basically tells us about the user (offline or online)
> 
> Could you talk more about the "why" for this change? It looks like the prop was set to `true` in #2545; do you think that was a mistake, or is there anything else that stands out from reading the history?

I think in my opinion there must be the `statusIndiactor` dot in offline cases

**Comment by chrisbobbe** [comment]
Possibly there's something we want to do here, but it's not at all clear to me; some more explanation and evidence might have helped make this a viable PR. But some things naturally have to be closed to keep the workload manageable, and this is one of those times.

If someone wants to resume something like this in the future, I'd recommend looking at the history I mention above in https://github.com/zulip/zulip-mobile/pull/4597#issuecomment-814384746.

**Pull request closed without merging**
