### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by saketkumar95**
fixes : #810 

picsart_07-11-04 07 52

### CODE REVIEW

**Comment by saketkumar95** [comment]
@borisyankov Which reset button should we keep then? There is already a reset button in `SearchScreen` but it's implemented again in `Input.js`. I think we should remove the reset button from `Input.js`

**Comment by borisyankov** [comment]
We should remove the one in SearchScreen.

**Comment by saketkumar95** [comment]
@borisyankov Done! 👍

**Comment by saketkumar95** [comment]
@borisyankov Checks are failing on master branch.

**Pull request closed without merging**
