### PR TITLE
Compose box uncontrolled

### LINKED ISSUE #2589: Text input gets very slow on some Android devices
On some Android devices, in some specific cases, the 'compose' input responds very slowly to a point of being unusable.
Reported here:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/speed

The issue was reproduced on Pixel 2, so it is not a purely performance problem.

Very likely, it is related to:
https://github.com/facebook/react-native/issues/19126

The fix then seems to be to make our compose box not-controlled.

This is not a bad idea as it will be a performance improvement regardless of the specific bug encountered, and something I wanted to do before this issue was reported.

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #2589 

When having 'controlled' `TextInput` components we run the risk of
JS blocking the updates to these components while you type.

This is generally not an issue in web React and rarely in React Native
(communication through the bridge is fast but slower than not having it at all)

Some users have experienced unusually slow input in the compose box.
This is likely related to https://github.com/facebook/react-native/issues/19126

Instead of using the topic and message inputs' property `value`
we can short-circuit this and update native properties ourselves.

This was an improvement I wanted to implement previously even before the
issues were reported, but back then it wasn't worth the effort.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @borisyankov !

> Applying the 'clear text input' patch to React Native is a superior solution.

Do you consider this PR ready to merge, and then ship in a release, without doing that?

If not, we shouldn't merge it until we have that ready too. How much work do you believe that will be?

**Comment by borisyankov** [comment]
Without the patch, when sending a message the text remains in the compose box.
With the patch, I'll need to handle few specific cases, and the placeholder disappears because it contains a character.

**Comment by gnprice** [comment]
> Without the patch, when sending a message the text remains in the compose box.

OK. That does not sound ready to me -- I expect that will (very reasonably) generate a lot of user complaints.


> With the patch, I'll need to handle few specific cases, and the placeholder disappears because it contains a character.

Wait, I was replying to what you said about "the 'clear text input' patch to React Native", which I take to mean [this upstream PR](https://github.com/facebook/react-native/pull/18278). Are you referring to that here, or are you talking now about the zero-width-space hack?

How much work do you believe it will be to apply the patch (i.e. the PR I just linked) to React Native and ship a version of the app using that?

**Comment by borisyankov** [comment]
'Not too long' is my guess, few hours. But I haven't kept a fork of RN so, not sure.

**Comment by borisyankov** [comment]
After reading the guide:
https://facebook.github.io/react-native/docs/building-from-source.html
Possibly few hours to half a day.

**Comment by gnprice** [comment]
OK, thanks. Given the uncertainty in our estimates of how much work that will be, I think I would rather not have it block getting a release out that fixes this issue. I do want to set up that infrastructure because it will help us on this and other issues, but I'd rather do it without that pressure.

I'm also not 100% confident that PR is good to apply -- the review feedback is cryptic, but it sounds like it may not be minor -- like the reviewer may think it's the wrong approach. I'd want us to either do some QA, or do some study of the context in the code to understand what the reviewer is saying (in particular whether it's a potential live issue, or a concern about code clarity which we can overlook for a temporary local patch), before we applied it.

This PR won't be ready to merge until we've done those two pieces of work, but let's leave it open because it's likely we will want to merge it then. (Basically, unless RN upstream suddenly responds to and fixes the original issue this works around -- and maybe even if they do, given the potential performance improvement.)

**Comment by gnprice** [comment]
In a chat thread, @borisyankov pointed out another option: we could release a version with this patch only on Android. The RN bug it works around only appears there, and the RN bug it triggers only appears on iOS.

That seems likely to be a good immediate solution. I have to go AFK for a bit, but I'll review this code later today, and if it looks good I think I'll do that.

**Comment by gnprice** [comment]
Some comments from reading through this branch:
* I'm having a hard time understanding some of what it's doing. Part of this is because it seems like a lot of the commits don't make sense on their own, and leave things in a broken intermediate state. For example, the first commit in the series removes the `value` prop from the inputs, without doing anything yet to replace its functionality. And the third commit moves a bunch of logic from methods of the component (which do get called) into `updateTextInput`, which was just introduced in the second commit and isn't called from anywhere yet. Would you try to reorganize these as a series of [coherent commits](https://zulip.readthedocs.io/en/latest/contributing/version-control.html)?
* One of the commit messages says "React Native has problems with some custom Android keyboards. It fails to reset the TextInput contents." What issue are you referring to there? A link or issue number would help.

None of this would stop me from shipping it as a temporary fix, in a stable branch, for a high-priority issue like #2589 -- I'll be OK with some empirical testing. But before we merge a change into master I definitely want something that's clearer to understand.

**Comment by borisyankov** [comment]
The custom keyboard fix is not a new line of code, but I was clarifying.
It is this one:
```js
TextInputReset.resetKeyboardInput(findNodeHandle(textInput));
```

**Comment by gnprice** [comment]
OK -- I've gone and shipped this on Android as a quick fix for #2589, as version 13.5.89. (In beta so far; will push to prod later today assuming all clear.)

Would you revise this branch to make it clearer along the lines of my comment above? And one more change:
* I'd like to see a version of this PR that changes things only for Android, and leaves iOS unaffected. The motivation is that that would give us the option to actually land this change without blocking on getting that iOS issue in RN fixed. In particular, I'd like to do a new major release before too long, and we'll definitely want #2589 fixed in that too.
  * I think it's OK if that duplicates some code between `.android.js` and `.ios.js` versions, if that seems cleaner than scattering conditionals around. The duplication isn't great, but the alternative of having different versions in Git for Android and iOS (like I just did for 13.5.89) is worse -- it effectively does the same duplication but along a different axis that is less transparent, plus it significantly complicates the release workflow.

**Comment by borisyankov** [comment]
Sounds good as an immediate step. I am strongly in favor of shipping a patched RN soon after this.
I suspect making the inputs uncontrolled on iOS will fix this issue #2434

**Comment by borisyankov** [comment]
@gnprice I did add the unmodified version for iOS and simplified the commits.

**Comment by gnprice** [comment]
Thanks for adding that Android/iOS split and for taking a pass over the commits!

I think both of the things I identified earlier that make the commits confusing to understand still apply, though:

> the first commit in the series removes the `value` prop from the inputs, without doing anything yet to replace its functionality.

> And the third commit moves a bunch of logic from methods of the component (which do get called) into `updateTextInput`, which was just introduced in the second commit and isn't called from anywhere yet. [Both of these are now the second commit; but this new function is still not called from anywhere at this point.]

It seems like each of these leaves things in a broken intermediate state. That makes it hard to work out how the changes are really meant to fit together.

Is it possible to separate out some part of these changes (apart from the Android/iOS split) and have that not leave things in a broken state? If not, it's best to just squash them all together -- the reader already has to read them together to understand any of them anyway.

**Comment by gnprice** [comment]
(Also, there are merge-conflict markers in one of the intermediate commits; that's a very clearly broken state, and those should be resolved.)

**Comment by borisyankov** [comment]
Thanks for catching the merge conflict issue. I did rebase and fixed this.
I would prefer to keep the commits separate as they 'tell a story' kinda. Though I wouldn't consider any of the first three 'stand-alone'.

**Comment by borisyankov** [comment]
I did went over the commits once more.
* Fixed the formatting issue (that was introduced then fixed)
* Made sure several messages are more logical or clear with the commits differing from before
* I did split the last change to ComposeBox and left for last the making of the component to 'uncontrolled'

**Comment by gnprice** [comment]
@borisyankov and I had a detailed discussion about these changes out of band, and he's posted a revised version as #2738 .

Closing this one because it's superseded by that.

**Pull request closed without merging**
