### PR TITLE
Fix layout issues in user autocomplete

### PR DESCRIPTION
**Pull request by chrisbobbe**
This is the PR Greg asked me to separate out of #5508; see https://github.com/zulip/zulip-mobile/pull/5508#pullrequestreview-1167785275.

Here's a new set of screenshots, since:
- I'm not sure if anything has changed in `main` since I opened #5508 
- The ["after" screenshot](https://github.com/zulip/zulip-mobile/pull/5508#issuecomment-1302629158) from that other PR, before splitting this out, is no good to use here, because this PR doesn't start using the bullhorn icon for wildcard mentions.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
As a data point, the task of making the simulator screenshots [above](https://github.com/zulip/zulip-mobile/pull/5551#issue-1446179007), plus the set I just posted on the original PR, [here](https://github.com/zulip/zulip-mobile/pull/5508#issuecomment-1312315271), took me 15 minutes, with about 11 of those spent waiting for the app to build. The "before" screenshot in both places is the same screenshot, taken from `main`.

**Comment by gnprice** [comment]
Thanks! Looks good -- merging, with just a tweak to the the last commit's summary line to make those more uniform.

> with about 11 of those [minutes] spent waiting for the app to build.

Dang. Does that represent building the app once, or several times?

It'd be great to make the iOS build less slow. I'm not sure how hard that would be -- the first question is what the slow parts are.

**Comment by chrisbobbe** [comment]
It was two builds of the app:

- one for `main` and the tip of this branch
- one for the tip of #5508 (since I needed to run `yarn`, which raised the [`cancelButtonTintColor` issue](https://chat.zulip.org/#narrow/stream/48-mobile/topic/stale.20FBReactNativeSpec.20causes.20iOS.20build.20failure/near/1461372) and I had to clean the build folder and rerun).

**Comment by gnprice** [comment]
OK. Yeah, taking 5+ minutes to build is not good.

For comparison, the Android build on my desktop (though the hardware is certainly a confounding factor here ­— plus the host OS, as macOS has a notoriously slow filesystem) takes a bit under 1 minute from a completely cold start:
```
    # clear all build caches:
$ time android/gradlew -p android clean
…
time: 7.383s wall (0.927s u, 0.083s s)

    # stop the running Gradle daemon too:
$ time android/gradlew -p android --stop
…
time: 0.541s wall (1.349s u, 0.091s s)

$ time android/gradlew -p android :app:assembleDebug
…
BUILD SUCCESSFUL in 55s
492 actionable tasks: 492 executed

time: 56.188s wall (1.494s u, 0.144s s)
```

---

… Hmm, but wait, though. There's no change to native code in this PR, nor in #5508 -- right? The only things changing are JS code, either in our own tree or in dependencies.

When that's the case, it shouldn't be necessary to rerun the build in Xcode. You should be able to launch the existing debug app you already have on the device, and just have it get the new JS code from Metro.

That is a key optimization I rely on regularly when testing on Android. Even though the build is "only" about 1 minute, it's much nicer to not pay that cost every time I'm switching branches; I'll rerun the build only when there's been a change affecting native code, or sometimes at the start of the day when I'm not sure what the previous state might be.

**Pull request merged**
