### PR TITLE
issue #161 Displaying current server in home-page

### PR DESCRIPTION
**Pull request by vaibhavs2**
Issue #161 
Please refer to PR #4516  for details that I closed by mistake and also it was failing CI tests.
- with small update, both email and realm in toast message

### CODE REVIEW

**Comment by vaibhavs2** [comment]
I am working on it

**Comment by chrisbobbe** [comment]
Hi, @vaibhavs2! Thanks for your work on this.

I see this has some CI failures and has gathered some rebase conflicts, and the commits aren't yet clear and coherent in this particular revision. Are you looking for any feedback to help get the PR back on track, or are you thinking of moving on to other work or starting over? 🙂 Anything is fine, I'm just wondering if you think it might be time to close this to help clean up the PR tracker.

**Comment by vaibhavs2** [comment]
yes , that time I did't familiar with the code quality, flow-types, indentation etc. that's why it got conflict errors, I have a ready updated code for it but I didn't push that yet, I am waiting for comments is this idea worth? if it worth then I am ready to work on it too, now I have to make changes as realmAdd and some more functionality has changed now. Details are here  #4516 , by mistake I opend two PR because its the first time I faced something like `CI check` and got confused what just happened that time.

**Comment by chrisbobbe** [comment]
> If the idea is not providing any value then close it :)

Ideas can certainly provide value even if we end up closing the issue/PR they were presented in. 🙂 Sometimes we start out thinking we'll do something one way, then we explore doing it that way and that causes us to try a different way, etc., and our thinking moves forward.

I appreciate all your screenshots (here and on #4516); thanks for those! I have a few concerns with the proposed UI; I'm basing these on those screenshots and your descriptions, as I haven't yet checked out the PR to try it locally.

- If meaning is only expressed through color, people with colorblindness can have a worse experience.
- I think the dot on the tab icon looks a bit too much like a notification indicator, saying "please check out this tab, it has news for you!" If I understand correctly, that's not what it really means; it means to show what account/server is active by showing its corresponding color.
- Long-press interactions can be hard to make discoverable.
  - Ah, and in fact—when the app's performance is doing well and things are responding quickly, it may actually be faster to learn the account/realm details with a _short_-press on that tab icon, than with a long-press. That's because a short-press (which is shorter) opens the account details screen that should have all this stuff. I think this might lead to the long-press not getting used much.

@gnprice, @WesleyAC, @alya, and I have recently been chatting about a [drawer-navigation](https://material.io/components/navigation-drawer) idea, and some other ideas, for #161 (and better multi-account support in general). Those ideas go in different directions than this PR, but of course we're happy to hear feedback. So I'll close this, but again I appreciate your work on it. 🙂

**Pull request closed without merging**
