### PR TITLE
Improve WebView build system

### PR DESCRIPTION
**Pull request by borisyankov**
This is an important rework of how building the WebView assets work.
Considered 'merge-ready', it is the base for further improvements.

This rework now enables the `WebView` to load its assets (styles, js, potentially fonts) from external files and not need to be built into the single `JS` file.

This approach is needed so we can embed:
* fonts
* emoji or other images

Makes it simpler to embed:
* polyfills and other vendor JS files
* styles that are pre-generated (code-highlighting, LaTeX/KaTeX)

In addition, this makes the reported error line-numbers in JS reliable.

This also adds:
* full code-formatting
* LaTeX styling

### CODE REVIEW

**Comment by gnprice** [comment]
Excellent, thanks @borisyankov ! It'll be great to have this system cleaned up -- I'm already appreciating how it makes the IDE able to highlight and show warnings in `theme.css` like a normal CSS file. :-)

A few things I'd like to see changed before merging this:
* There are a lot of spots where the changes in one commit don't really make sense without the context of some later commit.
  * For example: one commit adds `emoji.css` and explains that the point is to stop generating the data dynamically in `cssEmojis.js`, but it doesn't actually make any changes related to `cssEmojis.js`. Then a few commits later we stop using `cssEmojis.js` in `css.js`, in a commit that's doing a lot of other stuff and doesn't mention that change in its commit message. In the end it looks like the actual `cssEmojis.js` file sticks around even though it's not used anymore.
  * An example of what I'd much rather see: one commit (a) adds `emoji.css`, (b) switches `css.js` to use it, and (c) deletes `cssEmojis.js` -- and it doesn't do anything else. I think this would make it a lot easier to follow the changes; it'd probably also make it less likely for something to fall through the cracks like leaving the unused file around, precisely because it's so much easier to look back at and reread.
* It's kind of unfortunate to make a bunch of copies of all these files. For one thing, it makes them all look like source files you have to edit when making changes -- and it makes them look like they might *differ* between the platforms, which would be really complex to read.
  * There must be some reasonable way we can script this, making these copies happen at build time. E.g. on the Android side, we can add a few lines in the Gradle scripts to just invoke our `build-webview.js`. Let's do that instead.
  * I know this was already awkward this way with `generatedEs3.js`, but it gets a lot worse with so many files, so I'd like to solve the problem properly before doing that.
  * If there is a generated file we end up keeping in the repo, I'd want it to be super clear (a) that it is generated and (b) how to edit/regenerate it. Like the header I added at the top of `generatedEs3.js`.
* Small Git tip: don't delete a `-diff` line from `.gitattributes`. It remains useful when looking at history from before the file was removed -- e.g. when reading this branch, I get a big diff for where you remove that file.

**Comment by borisyankov** [comment]
I did undo the removal of the `diff` line.

`codeToCss.js` is not deleted because we will use it in future to regenerate the css static file, if the input data changes. I did update the commit message to include that information.

**Comment by borisyankov** [comment]
About the duplication of files. I researched today, and while Android is reasonably straight-forward, not so with iOS.

I will continue exploring a solution for both platforms but suggest we do work on merging this first?

**Comment by gnprice** [comment]
> codeToCss.js is not deleted because we will use it in future to regenerate the css static file, if the input data changes. I did update the commit message to include that information.

Ah, OK, thanks.

Would you add something in the repo explaining how to do that regeneration? A little script in `tools/` would be ideal; but if for any reason it's a pain to script, then some written instructions would be totally fine. I just want to make sure it's easy for any of us (including future-you) to reproduce what you did.

The rest of that example still applies -- I'd be much happier seeing a commit that added `emoji.css`, switched `css.js` to use it, and didn't do anything else.

Similarly, I'd like to have one commit (a) add `matches-polyfill.js`, (b) switch `script.js` to use it, and (c) remove `matchesPolyfill.js`. And another commit that does the same thing for `smooth-scroll.js` / `smoothScroll.min.js`.

I think a good commit, or series of commits, to start with would be to just switch from `generatedEs3.js` to the `zulip.js` resource. That has the fewest moving parts because that's already a generated file; and once that's done, the others can follow by building on the infrastructure for that one. I would gladly merge some commits that do that, as the first N commits on a branch, even before we're done with any revisions on the other changes -- that would help us move things forward.

---

> About the duplication of files. I researched today, and while Android is reasonably straight-forward, not so with iOS.

> I will continue exploring a solution for both platforms but suggest we do work on merging this first?

Sure; I'd be OK with merging for now a version with the duplicate files. We can focus first on the other aspects discussed above.

**Comment by gnprice** [comment]
BTW, my current thinking is it'd be good to turn our attention back to this after we complete the RN 0.56 and 0.57 upgrades (#2788 and #2955); we've seen a couple of instances recently of places where it'd be good to have this done.

**Comment by gnprice** [comment]
Bumping the priority because this blocks #2660, which people keep asking for and I just bumped.

**Comment by gnprice** [comment]
Much of what this PR aimed to do has now been accomplished with #3636.

There are still some further things to do. I think those will be best tracked as we see things we need (e.g. to complete #2660) rather than based on this prototype PR, so closing it.

**Pull request closed without merging**
