### PR TITLE
Migrate from Unimodules to Expo Modules

### PR DESCRIPTION
**Pull request by chrisbobbe**
Following the plan I sketched out at https://github.com/zulip/zulip-mobile/issues/5133#issuecomment-1016972765.

I kicked the tires on Android and iOS, and everything seemed fine:
- (No observed behavior changes anywhere when poking around, including in the message list)
- `expo-apple-authentication`: iOS native Apple auth worked
- `expo-screen-orientation`: nothing odd on rotating the screen
- `expo-web-browser`: opening a link in the "in-app browser" on iOS worked fine (and we don't use this on Android)
- `expo-application`: The app version on the Diagnostics screen showed up fine

Fixes: #5133

### CODE REVIEW

**Comment by chrisbobbe** [comment]
This'll be too long for a commit message, so I'll leave it here. We use five `expo-*` modules, and they vary in whether they cut a new major version for the breaking change from "Unimodules" to "Expo modules". (Because some of them didn't, I haven't bothered to send one of my easy, catch-all `yarn upgrade` PRs in a long time. To get it mergeable, I'd have had to spend time figuring out exactly which packages were violating semver and how, and exclude them. That seemed annoying.)

Collapsed below are the details of how I plan to upgrade those five modules, in the same commit that switches us over from `react-native-unimodules` to `expo`.

<details>
<summary>`expo-web-browser`</summary>

expo-web-browser seemed to make the switch at 9.3.0:
- Migrated in expo/expo@314e850c3 and expo/expo@8285c0328.
- 9.3.0 was likely published from expo/expo@fe74edd44. (There's no Git tag, which I think is the convention.)
- The [changelog](https://github.com/expo/expo/blob/master/packages/expo-web-browser/CHANGELOG.md#930--2021-09-09) doesn't mention any breaking changes we'd encounter by upgrading there. So, upgrade to ^9.3.0 with no further changes.
</details>

<details>
<summary>`expo-application`</summary>

expo-application seemed to make the switch at 3.3.0:
- Migrated in expo/expo@8285c0328 and expo/expo@efd75decd.
- 3.3.0 was likely published from expo/expo@fe23a511e.
- The [changelog](https://github.com/expo/expo/blob/master/packages/expo-application/CHANGELOG.md#330--2021-09-08) doesn't mention any breaking changes we'd encounter by upgrading there. So, upgrade to ^3.3.0 with no further changes.
</details>

<details>
<summary>`expo-apple-authentication`</summary>

expo-apple-authentication seemed to make the switch at 4.0.0:
- Migrated in expo/expo@314e850c3 and expo/expo@8285c0328
- 4.0.0 was likely published from expo/expo@1fffde734.
- The [changelog](https://github.com/expo/expo/blob/master/packages/expo-apple-authentication/CHANGELOG.md#400--2021-09-28) only notes one breaking change we'd encounter by upgrading to there: iOS 11 support is dropped. We've already done that.
- The changelog notes a few changes to align the types to the actual implementation, from expo/expo#13567. So, propagate those (really jsdoc plus TODOs for actual meaningful type changes) to our libdef, and upgrade to ^4.0.0.
</details>

<details>
<summary>`expo-sqlite`</summary>

expo-sqlite seemed to make the switch at 10.0.0:
- Migrated in expo/expo@8285c0328 and expo/expo@efd75decd
- 10.0.0 was likely published from expo/expo@1fffde734.
- The [changelog](https://github.com/expo/expo/blob/master/packages/expo-sqlite/CHANGELOG.md#1000--2021-09-28) only notes one breaking change we'd encounter by upgrading to there: iOS 11 support is dropped. We've already done that.
- The changelog notes a small change to the types (expo/expo#13826), which we already took in our 995422ae4. So, upgrade to ^10.0.0 with no further changes.
</details>

<details>
<summary>`expo-screen-orientation`</summary>

expo-screen-orientation seemed to make the switch at 4.0.0:
- Migrated in expo/expo@8285c0328, expo/expo@efd75decd, and expo/expo@6e35719a7.
- 4.0.0 was likely published from expo/expo@1fffde734.
- The [changelog](https://github.com/expo/expo/blob/master/packages/expo-screen-orientation/CHANGELOG.md#400--2021-09-28) only notes one breaking change we'd encounter by upgrading to there: iOS 11 support is dropped. We've already done that.
- The changelog notes a small change to the types (expo/expo#14150): an existing type is exported, and a lot of jsdocs are added. So, follow that.
- We find that there's a breaking change at 4.1.0 (likely published from expo/expo@df68325f3), so we exclude that from the range. In particular, expo/expo@057488d1a started depending on something called `ExpoReactDelegateHandler` offered by expo-modules-core, which wasn't available until expo/expo@0f5f192f4 landed in expo-modules-core@0.6.0 (likely also published from expo/expo@df68325f3).
  - expo-screen-orientation@4.1.0 doesn't seem to enforce expo-modules-core@0.6.0 or later with (peer-)dependency requirements; it probably should. (There don't seem to be (peer-)dependency requirements that *disallow* it, which is good.)
  - I think we're not ready to take expo-modules-core@0.6.0; I suspect (though unverified) that we may need to do a React Native upgrade before that. When I tried to bring that in, I got this failure from `pod install`:
    
    ```
    Installing ExpoModulesCore 0.6.4 (was 0.4.10)
    [!] The following Swift pods cannot yet be integrated as static libraries:
    
    The Swift pod `ExpoModulesCore` depends upon `ReactCommon`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    ```
    `ReactCommon` is a React Native thing, and the way we declare the dependency is by running a script published by React Native in our Podfile.
- So, upgrade to >=4.0.0 <4.1.0.
</details>

**Comment by chrisbobbe** [comment]
| Expo commit | When resolved in zulip/zulip-mobile | Comment |
| --- | --- | --- |
| 63b5a92b8 [templates] Remove unnecessary imports | N/A | We didn't have these imports to begin with. |
| c44d9daa8 Remove READ_PHONE_STATE permission from default template (#13176) | 2cc6a5277 | Our manifest explicitly says we don't want this permission. |
| 15aa41994 Update AndroidManifest.xml (#13173) | N/A | Our manifest wasn't requesting `android.permission.MODIFY_AUDIO_SETTINGS` to begin with. |
| 79ca9839c [expo-constants] Modularized  expo-constants without further app setup (#13424) | N/A | On Android and iOS, this stops pulling in code in node_modules/expo-constants that we weren't pulling in to begin with. The stated reason for the commit is "Try to achieve the goal of `expo install expo-constants` without any further setup." Well, we haven't run that command, or `yarn add expo-constants`, because we haven't yet had a reason to depend directly on expo-constants. An unrelated surprise I found right next to the removal on iOS is that the template app pulls in some code from node_modules/expo-updates. We don't depend on expo-updates at all. Looking at https://github.com/expo/expo/pull/7382, which seems to be when this got added, that omission should be fine: "almost all groups of people likely to use these templates […] will want to have expo-updates installed". Well, I guess we're the exception. Its description on NPM: "`expo-updates` fetches and manages updates to your app stored on a remote server." |
| b9f2132e7 Remove AppleTVOS12 JavaScriptCore.framework (#13591) | 64e5f8c12, ed91c3d80 | We've already removed these chunks that are about tvOS. |
| 060fbd4fa Remove xib file (#13590) | 78a62b249 | We've already updated to the modern .storyboard file for our iOS launch screen. |
| 3ad2d33e8 Added iOS background color support (#13607) | 575be428e | We decided in 575be428e not to set `rootView.backgroundColor` at all. This `RCTRootViewBackgroundColor` seems to be an Expo thing, not a RN thing (there are no search results for it on the RN GitHub). There isn't an obvious reason to approach Expo's way of doing things in this direction. |
| 9e66f3bce [template] Add react-native-safe-area-context to expo-template-bare-minimum (#13840) | N/A | We already have react-native-safe-area-context in our dependencies. |
| 05f2ed0c7 [autolinking] Use NodeJS to resolve autolinking script location & popularise it among other imports (#13901) | PR | For the actual headline change of this commit, we could take it or leave it; shrug. (For the benefits, see https://github.com/expo/expo/pull/13901#issuecomment-894530030 .) We end up taking it. In our commit that takes this change, we include bugfixes from expo/expo@d3f983699 and expo/expo@9781212eb. |
| f05c8ccb6 [android] Update Gradle to 6.9 (#13929) | PR | |
| 896103abd [sdk] upgrade typescript to v4.3.5 (#14015) | N/A | ^7.12.9 is already the version range we specify for @babel/core. |
| 507e608fd [ios][autolinking] Move autolinking scripts from the adapter to expo-modules-core (#14046) | N/A | This gets moved again later; we'll import it from its final location (node_modules/expo/scripts/autolinking.rb) in the main commit, following expo/expo@9781212eb |
| d3f983699 [ios] fix autolink error from pod install (#14034) | PR | We applied relevant parts of this when we handled expo/expo@05f2ed0c7. |
| dbd384b22 [template] React Native Image gif and webp support (#14163) | N/A | This change would have the template app define and use new "expo"-named variables to conditionally include dependencies that, if included, React Native's `Image` component would use for GIF and WebP support. I don't think we have a strong reason to add such variables, or any variables, as a way to change how the `Image` component behaves. We already directly give animated-GIF support without doing adding a variable; see our `// For animated GIF support` comment. Also, RN's doc for the Image component already talks about GIF and WebP support: https://reactnative.dev/docs/image#gif-and-webp-support-on-android |
| 09e76aae3 [templates] Remove expo forked react-native from managed apps (#14261) | N/A | This bumps `react-native` in package.json to 0.64.2, and brings `react` and `react-dom` up correspondingly. We're already using react-native@0.64.3. |
| eb2c86e38 [ios] Fix versioning script and shell app workflows (#14436) | da269e956 | Looks like this drops support for iOS 11; we've already done that. |
| 505f2066b [expo] Updates splash, adds dist/ to gitignore (#14439) | N/A | This adds a `dist/` directory to the project's gitignore. We don't have a `dist/` directory, or a reason for having one. |
| 9781212eb [templates] Update templates for the next SDK (#14409) | PR (main commit) | (See commit message.) |
| 9886c0aaf [expo-modules][ios] Fix errors from use_frameworks in Podfile (#14523) | PR | We just make a note of this, since it addresses an issue seen when using `use_frameworks!`, and we don't use `use_frameworks!`. |
| 38acbdec4 Update versions in project templates | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P Under `dependencies`, it updates `expo` from "~43.0.0-alpha.3" to "~43.0.0-beta.1"; we won't be taking an alpha or beta version. It updates `expo-splash-screen` and `expo-updates`, which we don't use. It updates `react-native-screens` from "~3.7.0" to "~3.8.0"; we're on 2.x because 3 is a breaking change. |
| d3b29ead0 [templates] Automatically resolve RN path in Xcode build scripts (#14546) | N/A | Shrug. This looks like more work like expo/expo@05f2ed0c7. As we said for that, we could take it or leave it; see https://github.com/expo/expo/pull/13901#issuecomment-894530030 . Maybe not this time. The string "node_modules" has 6 occurrences that we'd want to address, if doing so, not just the 3 that are in the Expo commit. It'd be fiddly and not great for readability. |
| c152aa35c Update project templates to expo@43.0.0-beta.2 | N/A | We won't be using a beta release of `expo`. |
| 7ba6eeb78 [templates] Update for latest publish packages | N/A | We won't be using a beta release of `expo`, and we don't use `expo-splash-screen` or `expo-updates`. |
| f1812e55b [android] Added support for opening https links (#14638) | N/A | This adds a declaration that the app would like to discover other apps that can open URLs, presumably for the "package visibility filtering" changes when targeting Android 11. We added almost the same declaration, in 30b4d6a64; the difference is that we didn't include the `<data android:scheme="https" />` part. That should be fine. AIUI, for that to make a difference to the results of the query, there would have to be some browser app that doesn't handle `https://`-schemed URLs, and think that's very unlikely. |
| 3bb65c866 [template] Use symbol to access reactNativePath rather than string (which does not work) | N/A | Our Podfile already has this fix. |
| 7946cd428 [template] Update bare template | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P |
| 8e1d7c05b [template] Set PROJECT_ROOT based on xcode project to fix release builds in monorepo | N/A | Shrug. This looks like a followup in the direction of expo/expo@d3b29ead0, which so far we've decided not to take. |
| 3de590bb7 [template] Update bare template | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P It updates `expo` to another beta version (we won't end up using a beta version), and it updates `expo-splash-screen` and `expo-updates`, which we don't use. |
| c026bda1d [templates] Publish updates for latest package versions | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P |
| 6e90b5214 [templates] Bump some dependencies | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P It updates `expo-splash-screen`, which we don't use. |
| ffdcd2a62 [template] Use expo run commands in bare templates | N/A | We're happy with our `scripts` in package.json. |
| d13d80c8f [template] Bump version for expo run changes | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P |
| 5b0c17a32 [templates] Update templates | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P It updates `expo` to the non-beta version "~43.0.0", but there are later versions than 43.0.0 (we'll probably want the latest 43.x), and it updates `expo-updates`, which we don't use. |
| 3ab513775 [template] Add back updates manifest embed script | N/A | This pulls in some code related to `expo-updates`, which we don't use. |
| 03ad7ee61 Revert "[template] Add back updates manifest embed script" | N/A | This reverts the template-app change in expo/expo@3ab513775, which we didn't take. |
| d034a6761 [react-native] Update from 0.64.2 -> 0.64.3 (#15108) | bfdf99bfd | |
| afa47a57b Update template versions | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P It updates `expo` to "~43.0.2", but there are later versions than 43.0.2 (we'll probably want the latest 43.x), and it updates `expo-splash-screen` and `expo-updates`, which we don't use. |
| 231fd1415 [templates] Publish | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P |
| 87a3d02aa [android] Fix building error from outside of project root (#15109) | PR | |
| c75c6c417 [template] Fix hermes command not found on monorepo (#15154) | PR | |
| 2726b3298 [templates] Publish | N/A | This updates `version` in package.json. We do that on our own schedule, which looks like it's just never. =P |
| 282f5070b [templates] Add missing react test render and upgrade jest (#14993) | N/A | We already use jest-expo and react-test-renderer at these versions. We already use the jest-expo preset. We're happy with `scripts` in our package.json. |
| 6877c1f5c [templates] Bump up expo-updates to 0.10.15 (#15257) | N/A | We don't use this library. Its description: "expo-updates fetches and manages updates to your app stored on a remote server." |

**Review by gnprice — COMMENTED** [review]
Excellent! Thanks for taking so much care with this. Glad to be unblocked again on keeping things upgraded.

This all looks great, except I'd like to skip those `node --print` changes. Comments about those below.

**Comment by chrisbobbe** [comment]
Great, thanks for the review! Revision pushed.

**Comment by gnprice** [comment]
Looks good; merging. Thanks again for taking care of this.

**Pull request merged**
