### PR TITLE
Initial implementation of stream settings.

### PR DESCRIPTION
**Pull request by jainkuniya**
Another step towards making nav bars clickable.
Push Stream setting screen on clicking stream title.
Currently showing only list of subscribed users of that stream.

### CODE REVIEW

**Comment by borisyankov** [comment]
I think we will actually move away from clicking the navbars.
We will likely not have this same title soon, it will be a back button on the left and a menu item to the right, so you will access them by clicking there.

You should call this 'StreamMemberList' and have the 'StreamDetails' have info on 
* name
* description
* member list button
* maybe topic list

Basically a combination of what is to the right of this:
https://chat.zulip.org/#streams/1/announce
and what Slack shows on mobile.

**Comment by kunall17** [comment]
After the stream push notifications we should have this PR as the initial step! 
[Screenshot](https://user-images.githubusercontent.com/12700799/30740576-2aa76522-9faf-11e7-90f3-4804e9cf7148.png)

@vishwesh3 Will you be working on this one anytime soon?

**Comment by vishwesh3** [comment]
> @vishwesh3 Will you be working on this one anytime soon?

@kunall17 yes!

**Comment by borisyankov** [comment]
Hey Vishwesh, closing this for now.
The 'screen' part is already implemented & merged.
The 'members' part - we would like to have this, but right now we do not have a 'subscribers' key anymore. We might want request and show this data. Feel free to work on this as a separate PR when you have time (it is nice to have but not urgent)

**Pull request closed without merging**
