### PR TITLE
Wait 800 msecs for persist/REHYDRATE to complete to narrow to notification

### LINKED ISSUE #1815: Android app crashes when opened through notification
Notification to narrow generally seems to work if the app is already running. 
If it is not, opening it via notification crashes it!

### PR DESCRIPTION
**Pull request by kunall17**
Fixes #1815 

device-2018-01-28-110005

### CODE REVIEW

**Comment by borisyankov** [comment]
800 is totally a 'magic number' that would work on some devices and not on some other devices.

**Comment by kunall17** [comment]
A magical number which is safe enough for every phone! 
The emulator takes 178 ms to rehydrate for a big server, so the phone would do it a lot faster.

**Comment by borisyankov** [comment]
The rehydration time is very dependent on the phone performance and sometimes can be several seconds.

**Comment by kunall17** [comment]
Fixed in #1830

**Comment by borisyankov** [comment]
This does NOT fix the issue.

**Pull request closed without merging**
