### PR TITLE
api errors: Give RequestError a constructor that writes httpStatus and data

### PR DESCRIPTION
**Pull request by chrisbobbe**
And adapt RequestError's callers to use the new constructor instead
of the Error class's constructor, which is pretty generic and just
takes `message?: mixed`.

This means one functional change, which seems like a bug fix: the
RequestError we construct in fetchServerEmojiData now stores the
http status code, instead of dropping it on the floor.

### CODE REVIEW

**Comment by gnprice** [comment]
Hmm interesting.

My intention when writing `RequestError` was that it'd be abstract: every instance would be an instance of a subclass, and specifically of either `ApiError`, `ServerError`, or `NetworkError`. But it seems I didn't think about how the constructor inherited from `Error` would mean it wasn't actually abstract.

I think the right fix for the functional issue here is that `fetchServerEmojiData` should make a `ServerError` in that situation, not a base `RequestError`.

And then `RequestError` should be made explicitly abstract. This can be done dynamically by having the constructor throw if it's being invoked at the base class, using `new.target`:
https://stackoverflow.com/a/30560872
In this case, though, that might do more harm than good given that this is constructed only in error-handling paths. Lacking a way to say it's abstract in the static types, maybe best is to just say that explicitly up front in its jsdoc.

**Comment by chrisbobbe** [comment]
Cool, makes sense. What do you think about the first three commits:

33f9819af api errors [nfc]: Make MalformedResponseError's `data` param optional
34d689763 api errors [nfc]: Make UnexpectedHttpStatusError's data param optional
2b7578dfe api errors [nfc]: Give ServerError constructor an optional `data` param

**Comment by gnprice** [comment]
I think this makes the meaning clearer; before, the implementation
    relied on the convenient fact that `undefined` is a subtype of
    `mixed`.

This doesn't feel like an accidental convenient fact to me, but rather a fundamental one: `mixed` is the type which has everything as a subtype. So I don't see the motivation for these on their own.

**Comment by chrisbobbe** [comment]
Closing in favor of: #5667

**Pull request closed without merging**
