### PR TITLE
CustomProfileFields: Use `selectable` prop for text fields

### PR DESCRIPTION
**Pull request by chrisbobbe**
Dec-08-2022 14-33-22

FYI @alya for the UX change.

Fixes: #5592

### CODE REVIEW

**Comment by alya** [comment]
Sure, seems reasonable to me. I assume it also looks fine in light theme?

**Comment by gnprice** [comment]
Thanks for this fix! The code looks good.

The other thing I'd like to have before merging is to manually test on Android too -- this is an area where we're relying on things that RN has to do separately for Android vs. iOS.

**Comment by chrisbobbe** [comment]
Sure; here's light mode on iOS, and a GIF from Android:

Dec-09-2022 19-48-17

Dec-09-2022 19-41-57

**Comment by gnprice** [comment]
Great, thanks. All looks good — merging.

**Pull request merged**
