### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by im-adithya**
Closes: #4455 

Additional Context: I'm sorry if this feels unnecessary!

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Merged in ff0b462a5bcc820a88f93286154b4a1757c313cb, with some small tweaks to the commit message to match our [style](https://zulip.readthedocs.io/en/latest/contributing/version-control.html). Thanks for catching and fixing this! 🙂

**Comment by im-adithya** [comment]
Thanks for merging it @chrisbobbe
I'll make sure to follow the guidelines next time! 👍

**Comment by gnprice** [comment]
Hmm - there's actually a reason those links were to that text and not directly to the chat stream. That section of text is where we link to the document with norms and conventions for the chat.zulip.org community:
https://zulip.readthedocs.io/en/latest/contributing/chat-zulip-org.html

There's important context there that I'd like people to see when they're first joining.

I'm sure the existing text can be made clearer about that, though. I'd be happy to see changes in that direction.

**Comment by chrisbobbe** [comment]
Ah OK, sorry about that! I'll start by reverting the commit; what do you think?

**Comment by gnprice** [comment]
Sounds good!

**Comment by chrisbobbe** [comment]
OK, done (d65b9bfc17ff66999a0b8339d9d49a2bf2bd5ccc).

**Pull request closed without merging**
