### PR TITLE
Fix: Limit react-native-photo-view to 1.3.x.

### PR DESCRIPTION
**Pull request by Sam1301**
The recent library version 1.4.0 has a bug.

Also submitted an issue for the same here https://github.com/alwx/react-native-photo-view/issues/84

### CODE REVIEW

**Comment by timabbott** [comment]
Stategically, do we want to be pinning fixed versions for everything and updating them manually, rather than having everything use this sort of limit approach?  I guess each approach has its costs, but it seems like we encounter issues like this pretty often.

Maybe the right answer is to have enough smoke tests that we catch things like this; I'm not really sure. I just think we should be thinking about this :).

**Comment by kunall17** [comment]
(Unrelated to this PR) 
@timabbott talking about the smoke test's we recently merged the detox test's to the CI and they work nicely, now I need the server running on the CI to take the test's further and test the actual stuff! 
So we have two options
- Start supporting osx for non-vagrant or non-docker installs 
- Mock everything 

As nor the docker neither the vagrant is supported in the travis for osx build! 
What do you suggest?

**Comment by timabbott** [comment]
It's probably possible to support OSX for non-vagrant installs, though it'd be a significant project.  The things that will be hard are installing RabbitMQ and Postgres, if I recall correctly.  

I think for many tests, where there's just 1 network request involved, we can probably just mock the network requests and have something reasonable happen.  I'd see whether you can get somewhere good with that approach, and if it isn't going well, I'd be happy to collaborate on getting `provision` to run in OSX for the tests.

**Comment by Sam1301** [comment]
makes sense, till we have better tests, having fixed versions for dependencies which often break might be better -- we'd atleast be preventing an error (even if it might require more manual work to update).

**Comment by borisyankov** [comment]
The dependency thing is tricky, but a few general rules:
* we should try to not use many external components if we can replicate the functionality easily ourselves (we are doing a decent job)
* we definitely want to keep them updated when there is no issue, React Native breaks stuff or makes them incompatible relatively aggressively, so usually keeping up is the smart choice
* in case like this, we will lock to a previous version, when the release is buggy
* if we decide to use a component, and the component is having issues, we should be more active to contribute bug reports and bug fixes to that project

**Comment by kunall17** [comment]
@timabbott Hmmm, if the server runs then it would be the best (considering it does not takes huge amount of memory, as the ios sim's + testing will take a lot mem) otherwise I'll mock them No other option.

I'll try for the dev and post the results!

**Comment by timabbott** [comment]
Cool.  Post frequently on Zulip as you work on this, since with a lot of things, I'll be able to save you a lot of time :)

**Pull request merged**
