### PR TITLE
Fix: Logout gives endless loading screen

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes: #4723

### CODE REVIEW

**Review by WesleyAC — APPROVED** [review]
LGTM, thanks!

**Comment by chrisbobbe** [comment]
Thanks for the review! I'd like @gnprice to take a look as well, as I think he said on the call that this diagnosis was surprising or at least not as precise as it could be (which, it's true, it's not super precise).

**Comment by WesleyAC** [comment]
Did we end up talking about this again? Somehow I thought we made progress towards merging this, are we still waiting on @gnprice?

**Comment by chrisbobbe** [comment]
> Did we end up talking about this again? Somehow I thought we made progress towards merging this, are we still waiting on @gnprice?

Yes, I think we chatted a bit on a video call but Greg hasn't yet had a chance to review the code in more detail.

**Comment by gnprice** [comment]
Thanks @chrisbobbe for this fix (and the underlying diagnosis)!

It's still kind of mysterious to me how this bug causes the particular symptoms we're seeing -- it feels like there's a bug in react-navigation involved here. But the fact that we're making a new `ComponentType` value, for each of these screens, in each render of `AppNavigator` is definitely a bug in our code, and this is a good fix.

I think the boilerplate is avoidable, though. I've pushed an additional commit onto this branch that demonstrates how, by adding a React hook `useHaveServerDataGate` that just factors out what your fix does for each of these screens.

If that looks good to you, please go ahead and merge after fixing up the branch -- I think either squashing the commits together, or putting a commit that adds `useHaveServerDataGate` first and then a commit that uses it, would be fine.

**Comment by chrisbobbe** [comment]
Thanks for the review!

> If that looks good to you, please go ahead and merge after fixing up the branch -- I think either squashing the commits together, or putting a commit that adds `useHaveServerDataGate` first and then a commit that uses it, would be fine.

Done.

**Pull request merged**
