### PR TITLE
NativeModule: Android module to ignore SSL when connection to url

### PR DESCRIPTION
**Pull request by ebouJ**
Implemented a native module in android to connect to a URL ignoring all SSL errors.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @ebouJ ! Will be very glad to have this working and merged.

A few thoughts:
* Please make your branch a plain series of commits -- no merge commits. Instead of merging, rebase.
* What happens on iOS with this change? I'd be OK with merging a version of this that helps only on Android, and leaving iOS for later; but it's important that it not make anything any worse on iOS.
* What documentation or examples did you rely on to write this Java code? In anything with SSL, there can be a lot of fiddly details to get right; so it's important to know what sources to consult to compare this to, to help understand how we can expect it to behave.
* There's a lot of funny whitespace in this code: odd indentation, extra space at the end of a line, etc. Your IDE should have a feature to clean that up; please use it. (We don't seem to have such a thing in the build, because we don't edit Java *that* often; if this happened frequently we definitely should.)

**Comment by ebouJ** [comment]
@gnprice thanks I rebase to resolve the conflicts. I haven't tested it on ios yet. But people have raised concerns about using this code in production. The example is from [here](https://stackoverflow.com/questions/19723415/java-overriding-function-to-disable-ssl-certificate-check) and [here](https://stackoverflow.com/questions/1201048/allowing-java-to-use-an-untrusted-certificate-for-ssl-https-connection)

**Comment by borisyankov** [comment]
I think the changes to the `RealmScreen.js` file can be made in a different PR.
I have comments about it, but it is too early to discuss it.

It will be good to examine how this is done on iOS so both approaches look as similar to one another as possible.

**Comment by ebouJ** [comment]
@borisyankov sure will work on the IOS version soon.

**Comment by borisyankov** [comment]
For that reason, we will leave this PR open.
After you have some progress with the iOS we will consider whether this is ready or needs changing

**Comment by gnprice** [comment]
I took a quick look at the Java code, and I'm pretty sure this will disable cert checking for *all* connections the app makes, once it runs once. We don't want to do that.

There is another answer on one of those SO threads you linked, here:
https://stackoverflow.com/a/21103499/378130
which shows an example of how to do it for just one connection at a time. Let's try doing that.

Let's prioritize that ahead of the iOS version; it's more important to get one thing that works right than to get two things.

**Comment by ebouJ** [comment]
@gnprice I will work on that tonight.

**Comment by borisyankov** [comment]
@gnprice We should probably close this?

**Comment by gnprice** [comment]
Yeah, agreed. We're continuing to track the issue it was intended to address as #1191 .

**Pull request closed without merging**
