### PR TITLE
deps: Upgrade to RN v0.66!

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes: #5231

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Here are the RN commits that touch the [RN template app](https://github.com/facebook/react-native/tree/main/template) that are in v0.65.2 but are not in v0.66.4. They're ordered from first to last (oldest to newest).

I.e., they're the commits in the output of `git log --oneline --reverse v0.64.2..v0.65.2 -- template`, when I run it in a clone of the facebook/react-native repo.

Along with whether, how, and when we propagate the changes to our app.

We shouldn't forget to update this, if necessary, to follow any changes made during code review and merge.

| RN commit | When resolved | Comment |
| --- | --- | --- |
| facebook/react-native@6386f691f Deploy Flow v0.150.0 | main commit | Flow 150 adds a `format.bracket_spacing` option; see facebook/flow@2d7614f38. The RN template app sets that to `false`, but I think we're fine to stick with its default, `true`. |
| facebook/react-native@7252798ab Deploy Flow v0.151.0 to xplat | main commit |  |
| facebook/react-native@726e68926 Deploy Flow v0.152.0 | main commit |  |
| facebook/react-native@547b4c92e Gradle 6.9, Android Gradle Plugin 4.2.1 (#31593) | 53ed19500 | This was backported to RN v0.65 in facebook/react-native@7599593b3 and we processed it for that upgrade. |
| facebook/react-native@70da64094 remove jcenter (#31609) | 1f80f4b6c | This was backported to RN v0.65 in facebook/react-native@9a923be89 and we processed it for that upgrade. |
| facebook/react-native@5d01110b5 bump buildToolsVersion to 30.0.2 (#31627) | N/A | This was backported to RN v0.65 in facebook/react-native@37e9f1d36 and we processed it for that upgrade. |
| facebook/react-native@b3a715f6e removal of textColor from base application theme (#31487) | 4fc4e9681 |  |
| facebook/react-native@80927791e Update _gitignore - Remove .hprof (#31679) | N/A | The commit doesn't help me understand why an .hprof file might appear, and I've never seen one appear. Let's wait till we see one, then maybe we can get a better idea of why it appears, and we can act on that. |
| facebook/react-native@06c33e9ab Bump Android deps to 0.93 (#31675) | 7b4be5d33 | This was backported to RN v0.65 in facebook/react-native@d8b115afa and we processed it for that upgrade. |
| facebook/react-native@b176617d1 Release v0.153.0 to xplat | main commit |  |
| facebook/react-native@aa43aab77 Bump NDK to 21.4.7075529 (#31731) | N/A | Instead of pinning explicitly, we defer to the Android Gradle Plugin's choice of NDK version; see https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/Pin.20to.20explicit.20NDK.20version.3F/near/1132815 |
| facebook/react-native@36318b677 Deploy v0.154.0 to xplat | main commit |  |
| facebook/react-native@ca440b910 Upgrade Metro to v0.66.1 | this PR |  |
| facebook/react-native@d6ed1ff58 Allow configuring ndk build architectures (#31232) | N/A | We're skipping this for now; see https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/RN.3A.20.22Allow.20configuring.20ndk.20build.20architectures.22/near/1377512 |
| facebook/react-native@efd4dafc5 Update xplat to Flow v0.155.0 | main commit |  |
| facebook/react-native@1e6fddbe0 Deploy Flow v0.155.1 | main commit |  |
| facebook/react-native@cfdc4fed0 Upgrade metro to 0.66.2 | this PR |  |
| facebook/react-native@a67799fc4 Deploy 0.156.0 to xplat | main commit |  |
| facebook/react-native@41f45a77a Bump Flipper to 0.99.0 (#31896) | this PR |  |
| facebook/react-native@d27288044 Handle OSS renderers in sync script | 72583b13c | This was backported to RN v0.65 in facebook/react-native@5a1dc1b6b and we processed it for that upgrade. |
| facebook/react-native@d583c2f15 Fix Undefined symbol: __swift_FORCE_LOAD_$_swiftFileProvider when building with Xcode 13 | N/A | This gets cleanly reverted in facebook/react-native@ec083f914; ignore. |
| facebook/react-native@83b16292c Deploy 0.157.0 to xplat | main commit |  |
| facebook/react-native@ae494e7ce Bump AGP to 4.2.2 | this PR |  |
| facebook/react-native@ec083f914 Back out "Fix Undefined symbol: __swift_FORCE_LOAD_$_swiftFileProvider when building with Xcode 13" | N/A | This cleanly reverts facebook/react-native@d583c2f15; ignore. |
| facebook/react-native@eb9388630 Include Swift lib in LIBRARY_SEARCH_PATHS | N/A | The RN maintainers announced a simpler fix to the build failure this seems to be aimed at: just don't include the LIBRARY_SEARCH_PATHS section at all. With one requirement: take an easy CocoaPods version bump. We did all that in 80a86212f. See there, and also https://github.com/facebook/react-native/commit/eb9388630#commitcomment-58407458 |
| facebook/react-native@b48c3d1d4 Fix irregular indent in template (#29871) | N/A | This tiny indentation error doesn't appear in our project. |
| facebook/react-native@06e31c748 fix AGP 7 compatibility (#32030) | N/A | This was backported to RN v0.65 in facebook/react-native@8b430e00d and we processed it for that upgrade. |
| facebook/react-native@b55201c53 Deploy 0.158.0 to xplat | main commit |  |
| facebook/react-native@ab829005b Move react-native-codegen to root | main commit |  |
| facebook/react-native@a0429ebb5 (tag: v0.66.0-rc.0) [0.66.0-rc.0] Bump version numbers | N/A |  |
| facebook/react-native@ea5109fc0 OSS: add Xcode 12.5 + M1 machines CocoaPods post_install workaround | main commit |  |
| facebook/react-native@038cdda23 Switch order of search libraries to fix M1 build error | N/A | This is downstream of facebook/react-native@eb9388630, which we decided not to follow; see there. |
| facebook/react-native@d552362f8 (tag: v0.66.0-rc.1) [0.66.0-rc.1] Bump version numbers | N/A |  |
| facebook/react-native@614a370d8 (tag: v0.66.0-rc.2) [0.66.0-rc.2] Bump version numbers | N/A |  |
| facebook/react-native@ab50c6ee2 (tag: v0.66.0-rc.3) [0.66.0-rc.3] Bump version numbers | N/A |  |
| facebook/react-native@d47fd4a32 (tag: v0.66.0-rc.4) [0.66.0-rc.4] Bump version numbers | N/A |  |
| facebook/react-native@09a21f0f3 (tag: v0.66.0) [0.66.0] Bump version numbers | N/A |  |
| facebook/react-native@d48ed4a4b (tag: v0.66.1) [0.66.1] Bump version numbers | N/A |  |
| facebook/react-native@6c19dc326 (tag: v0.66.2) [0.66.2] Bump version numbers | N/A |  |
| facebook/react-native@3b5e4463a (tag: v0.66.3) [0.66.3] Bump version numbers | N/A |  |
| facebook/react-native@1b31d6bb5 (HEAD, tag: v0.66.4, origin/0.66-stable) [0.66.4] Bump version numbers | main commit |  |

**Review by gnprice — COMMENTED** [review]
Thanks @chrisbobbe for taking care of this upgrade! This all looks good; just small commit-message comments below.

**Comment by chrisbobbe** [comment]
Thanks for the review! Revision pushed.

**Comment by chrisbobbe** [comment]
Before merging, let's let a release with RN v0.65 go out to all users.

**Comment by gnprice** [comment]
> Before merging, let's let a release with RN v0.65 go out to all users.

(That way if there are issues that seem related to the upgrade, we have a head start on narrowing them down and don't have to wonder whether they were introduced by RN v0.65 or v0.66.)

**Comment by gnprice** [comment]
Meanwhile, this branch all looks good! So once we have a release out to prod with RN v0.65, this will be ready for merge.

**Comment by chrisbobbe** [comment]
Great! Thanks for the review!

**Pull request merged**
