### PR TITLE
Deduplicate slashes in social auth login endpoints

### PR DESCRIPTION
**Pull request by chrisbobbe**
This fixes an issue noted in https://github.com/zulip/zulip-mobile/issues/3567#issuecomment-622574435 where we're duplicating slashes when we call social auth endpoints.

A better fix depends on https://github.com/zulip/zulip-mobile/issues/4081. The commit messages reflect that issue being blocked by the RN v0.61 upgrade, but Ray points out that we may be able to do it without the available JS library, and instead make a native plugin, in which case the issue is not blocked; discussion is ongoing.

### CODE REVIEW

**Comment by ray-kraesig** [comment]
The PR text and comment say RN v0.61, but the commit message says RN v0.62.

Other than that, LGTM.

**Comment by chrisbobbe** [comment]
@ray-kraesig [said](https://github.com/zulip/zulip-mobile/pull/4082#issuecomment-623650592):
> The PR text and comment say RN v0.61, but the commit message says RN v0.62.
> 
> Other than that, LGTM.

Good catch. 😆

I've removed both mentions, following our new knowledge that it isn't actually blocked at all.

**Comment by ray-kraesig** [comment]
I'm a bit behind on PRs, I'm afraid; this one's fallen through. ... much like #3819 did, which seems to have fixed the same bug. I'll be happy to merge the JSDoc, of course; do we still want the first commit?

**Comment by chrisbobbe** [comment]
> which seems to have fixed the same bug

They're similar but different bugs; #3819 was for trailing slashes on the realm URL; this is for leading slashes in the login URL. #4081 will much reduce our woes in both places (and many more), but for now, I think the fix in this PR would be good to have.

**Pull request merged**
