### PR TITLE
shared: Use tsc-generated versions of shared code

### PR DESCRIPTION
**Pull request by gnprice**

### CODE REVIEW

**Comment by gnprice** [comment]
zulip/zulip#22586 is now merged. Updated this to use it, and it should be ready to merge.

**Comment by chrisbobbe** [comment]
Looks good to me!

**Comment by chrisbobbe** [comment]
Are we waiting for another review on this?

**Comment by gnprice** [comment]
Nope! Thanks for the bump (and the review); must have slid off my radar. Merging now.

**Pull request merged**
