### PR TITLE
Fix time separators in message list

### LINKED ISSUE #361: Date separators in message list not using locale settings
The date separators in the stream view (for example, '----------- today ------------') seem to be in the wrong place for me (and do not divide actual days in my time zone).

My guess is that we're not checking the user's locale when computing these.

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #361 

* Use 'date-fns', instead of several custom written functions.
* Throw away some code and tests no longer needed.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
I like replacing 'moment' with 'date-fns'!

Does this fix the separator issue though? It doesn't look like it uses the user's locale

**Comment by borisyankov** [comment]
It does use it. 
Date class is tricky and I could have fixed it by fixing our custom code too. But since date-fns had literally the same funcs with same names, but correct, it made most sense to delete our code.

**Comment by neerajwahi** [comment]
👍

**Pull request merged**
