### PR TITLE
ADD: Type annotations for timing.js

### PR DESCRIPTION
**Pull request by mayank4kathuria**
fixed the type errors and type annotations for timing.js . Also tested with yarn run flow with no error.

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks @mayank4kathuria for taking a shot at this!

* I'm going to ignore on this PR the first few commits, with setup docs -- let's discuss those on #2107.
* Your diffs make a lot of extra changes because they add DOS-style, "CRLF" line endings. Please set up your editor so it doesn't do this; if you ask in the #mobile stream, we can help you figure out how.
* Run `yarn run test:lint` to see the issues it flags; this includes the line endings (so it will help you make sure you've fixed that), and it finds one small other issue. We keep our lint error-free.
* Please read our guide on [writing clear, coherent commits](https://zulip.readthedocs.io/en/latest/contributing/version-control.html). All these changes (again, ignoring the setup instructions) should be one commit; and take a look at what the guide says about the summary line of your commit message.
* There's no need to write types redundantly, like repeating `(key: string)` for the variable right next to where it appears for the arrow function itself.
* Generally I don't think we need to write `void` as a return type when the function definition is right there; it doesn't add much for the reader.
* Adding the type `number` for what `now` returns is helpful, though! I'd be glad to merge a change that added that.
* Generally the type `Object` doesn't add much information, or even any at all. What would be useful on `timingMap` and `countMap` is to add a type that says what types the keys and values in these maps should be -- [see the Flow docs for how](https://flow.org/en/docs/types/objects/#toc-objects-as-maps).

Would you try revising this PR with these points in mind? Thanks again!

**Comment by timabbott** [comment]
@gnprice for the CLRF thing, we can use the zulip.get `.gitattributes` file, which prevents that from happening to people trying to develop on Windows.

**Comment by gnprice** [comment]
@timabbott Yeah, good thought -- done, as 58c70ecc.

**Comment by mayank4kathuria** [comment]
@gnprice  Sorry for the rookie mistake it was my first time making a PR and Thanks for the advice, will keep those in mind from my next PR onward.

i will submit another PR with all the mentioned points for the same file.

**Comment by borisyankov** [comment]
Cool, thanks @mayank4kathuria 
I'll close this one then, and waiting for the new one 👍

**Pull request closed without merging**
