### PR TITLE
Initial implementation of message long press.

### PR DESCRIPTION
**Pull request by jainkuniya**
Fix: #1590

### CODE REVIEW

**Comment by jainkuniya** [comment]
Updated/Rebased 👍 

@borisyankov Ready for initial review :)

**Comment by borisyankov** [comment]
I was going to go over each element, but I can summarize the changes:
Minimize the changes needed to handle all the actions, use the very same code we already have.

**Comment by borisyankov** [comment]
This is still a priority, just keep in mind you probably added too much stuff, and you can implement it mostly with existing code (plus long-press detection)

**Comment by jainkuniya** [comment]
So will be splitting it into parts, detecting long press and handling it.

**Comment by borisyankov** [comment]
Good idea!

**Comment by borisyankov** [comment]
I guess this was the old PR. Closing.

**Comment by jainkuniya** [comment]
Yup! final part is https://github.com/zulip/zulip-mobile/pull/1788

**Pull request closed without merging**
