### PR TITLE
Fix: unexpected markdown rendering.

### PR DESCRIPTION
**Pull request by vishwesh3**
Fix: #1184

**Advantages**
We are having better rendering (no more extra white spaces)
image
image

**Disadvantages**
Now there are many elements (components), so this might increase bridge communication, but in my general testing i can't find any difference :)
(Now sure is this really a disadvantages or not)

BTW in next week or so, I am planning to improve our current scrollView so that there is minimal bridge communication, scroll events etc

### CODE REVIEW

**Comment by borisyankov** [comment]
If we ignore the performance implications, this makes a good step forward in rendering norma text, but also breaks several renderings (like links). Generally, if we wanted to implement this, something like a dozen tests would be a good thing to have.

That being said, it is very likely that the performance impact is not only not negligible but very significant. If I would have to guess, I would have to say this will be 3x to 5x slower than our current rendering (depending on the average length of a message).

We already did some testing with @Sam1301 a couple of months ago, and the performance and memory consumption heavily depends on items rendered (just as you would expect). Bridge communication in this case may not be as relevant (it might still have an impact). But memory and time to render messages when switching narrows is critical.

The real issue is that you **need to benchmark** before and after. Because your PC/Mac is equal to a super fast phone, you might not be noticing the difference. Try it on a real phone, load few hundred messages and test again.

**Comment by vishwesh3** [comment]
Tried on Android physical device: in the debug mode it is already slow, so can't able to get complete difference. Also tried debugger tool, not able to get exact time difference.

@borisyankov I have added an option in Diagnostics Screen to enable this PR. So we can merge this and release it in next beta, which will give more insights on physical device in release mode.

In future when we will go with `SectionList`, its performance will automatically improved.

**Comment by vishwesh3** [comment]
Moved Split message option to Debug Screen. :+1:

**Comment by borisyankov** [comment]
Thanks. I will merge to try it out but remain super-skeptical about this being viable as the main setting.

**Pull request merged**
