### PR TITLE
Handle bot account details

### PR DESCRIPTION
**Pull request by borisyankov**

### CODE REVIEW

**Comment by timabbott** [comment]
Just a quick comment: we have a little bot icon that we use here: 
image
and we might want to also use in the mobile app to indicate messages sent by bot users (not sure if we do already; I haven't checked, but this just came to mind on seeing this PR title).

**Comment by borisyankov** [comment]
We are currently showing the gravatar from the bot's email.
While we can add a custom icon for all bots, wouldn't it be better if we did make sure we have different and cool ones on Gravatar?

**Comment by timabbott** [comment]
The avatars for most bots (everything but the system ones like Notification Bot are uploaded by users, so we have no control over what they look like).  The main purpose of that little bot icon next to the name is to make it clear when something was sent by a bot vs. a real person, for user-uploaded bots.  I think Slack just uses the word "BOT" for this, but I think that's a lot uglier.

**Comment by borisyankov** [comment]
So we can use this it in place of the status indicator?

**Comment by timabbott** [comment]
status indicator = presence?  Yeah, that's where I'd put it.

**Pull request merged**
