### PR TITLE
Upgrade to React Native 0.56 & 0.57

### PR DESCRIPTION
**Pull request by borisyankov**
Upgrade dependencies, config and build files to RN 0.56

Previous upgrades were done manually by updating dependencies and
.flowconfig

This commit contains a full `diff` with previous versions.

What was done is:
 * run react-native-git-upgrade
 * resolve merge conflicts
 * update dependencies that were needed but missed by the script

Note: 
* In another commit I'll need to fix Flow issues before merging
* Jest test runner need fixing: https://github.com/facebook/react-native/issues/19859

### CODE REVIEW

**Comment by borisyankov** [comment]
I actually have 5-6 more of these fixes locally, will clean them up and push to review (they should all be independent of the upgrade to RN 0.56 but a requirement to not get the errors once upgraded)

**Comment by borisyankov** [comment]
@armaanahluwalia apart from few Flow issues that need fixing, this PR is ready to go.

Give it a try and give us feedback if you are having any issues. If it works for you, that is one more assurance that will let us merge faster.

We are also looking to merge this one #2955

**Comment by armaanahluwalia** [comment]
Okay I’ll do that and get back to you. Is there any reference document for manually testing the entire application? Something that might guide someone looking to test all the major features?

**Comment by borisyankov** [comment]
Not really. Manual testing almost by definition is ad-hoc.

**Comment by gnprice** [comment]
@borisyankov Do you believe some of these commits are ready? (It sounds like yes.) It'd help a lot if you would `rebase -i` them to the front of the branch, so that there's a specific series of changes you've tested and are recommending to merge.

**Comment by borisyankov** [comment]
Indeed, ready to review.
I did prefix the two commits that need more work with `WIP` and moved them to the end of the list.
All the remaining commits should be independent and can be reviewed and merged in any order.

**Comment by borisyankov** [comment]
Trying to define the Flow types correctly for the code added here:
https://github.com/zulip/zulip-mobile/commit/a31f717e7bfe71c20404daaac2ca5d82378f6c4e#diff-c825c78596317a49f7911a5f9fb5a81d

Was there a reason to create a custom stylesheet and mutate it in code vs setting the style directly on the node?

**Comment by gnprice** [comment]
> Was there a reason to create a custom stylesheet and mutate it in code vs setting the style directly on the node?

You have the tools to answer this question :wink: :
```
$ git log --stat -p src/webview/html/htmlBody.js
commit a31f717e7bfe71c20404daaac2ca5d82378f6c4e
Author: Greg Price <greg@zulipchat.com>
Date:   Mon Jul 30 16:05:40 2018 -0700

    webview: Make error banner and headers play nice, using the CSSOM.
    
    Fancy name, but the CSS Object Model is just an API for manipulating
    CSS rules, which we use here in quite boring ways.  [...]
```
That commit message (on a31f717e7) has several paragraphs about exactly this question. Happy to answer follow-up questions, but please do read the original answer first.

**Comment by gnprice** [comment]
Thanks @borisyankov ! Just merged most of these commits that come before the upgrade proper; comments below on the others. I haven't yet looked at the commits that come after.

In the commits that I merged, I made some changes to the commit messages, some of style and others of fact:
* Changed some references to "previous Flow versions" / "now" to references that are less confusing in the context of coming before the actual upgrade
* On exports, we have tons of exports in our codebase that Flow infers the types of just fine, so the rule can't be that an exported function requires a return type. On looking at it a bit, the actual story appears to be that when there's a free *type variable* (moreover, one "in an input position", e.g. as type parameter to `Array`), an annotation is required. See https://github.com/facebook/flow/issues/6828 and https://github.com/facebook/flow/issues/6151 . 
* "Provide missing types" sounds like adding annotations -- make clear it's just imports
* "refactor" is rarely a useful word for the summary line, even when accurate; edited.
   * Here I think it's not accurate for the `elementSheetHide` etc. commit, too. 

---

On the remaining commits before the upgrade:
* Message new fields -- two of them are already there, a bit earlier in the definition. I'm curious what the error message was!
* `children` type errors: adding `any` :cry: 
   * "fix" is never an appropriate description of a commit that introduces `any`, even if the commit is justified by expedience.
   * I can't tell what errors these are fixing; rebasing the upgrade + flow-typed commits on top of the parent (or grandparent), I don't see any obviously-related errors, but of course the list is long. What's the error message? I'd like to poke at it before we add `any`s.
   * Without seeing the errors I'm not sure, but perhaps this might help: https://github.com/facebook/flow/issues/6151#issuecomment-403071686
* style issues:
   * Hmm, `any` is sad. We should be using `TextStyleProp` and friends. Happily they already exist in v0.55! Though they get [much nicer jsdocs](https://github.com/facebook/react-native/blob/v0.56.0/Libraries/StyleSheet/StyleSheet.js#L33) in v0.56.
   * The `|` thing won't work. `DangerouslyImpreciseStyleProp` might work; if so it'd be OK as a hack for now.
   * Failing that... I'll want to poke at this a bit in the next round.
* handleLongPress "Fix for exception": this fix doesn't look right; what should the type of this function's parameter be? Seems like it should be `Element` or subtype; we control the call site, so we can take care of things there.
* Aha, the `is incompatible with Node` -- I never like the term "incompatible" for this concept, and this error message illustrates why. The concept they actually mean is "is not a subtype of", which unlike "incompatible" is not symmetric. In fact the complete sentence in the error message is `Cannot call getMessageIdFromNode with e.target bound to node because EventTarget [1] is incompatible with Node [2]`, and that is absolutely correct -- `EventTarget` may be a supertype of `Node`, but it is not a subtype and an `EventTarget` can't play the role of a `Node`.
* `flow: Event handlers` summary/message is missing the crucial term that says what the commit actually does: add types, or annotations.

**Comment by gnprice** [comment]
(Just merged was 14 commits, so good progress! There were 29.)

A few thoughts from the upgrade commit itself:
* This commit message, with the explanation of where these changes came from, is super helpful -- thanks!
* Does GH recognize "Implements"? Just uniformly saying "Fixes" seems fine to me.
* We can break some of this up into meaningful chunks; that will make it more comprehensible already, and make a big difference in comprehensibility if we end up squashing anything else into it from later.
* E.g., these can probably each be a commit:
   * upgrade Android build environment: Gradle, Gradle plugin (therefore add maven repo), build tools, target and compile SDK versions, support lib version, and factor all version numbers out into root `build.gradle`. Ideally separate the refactoring of where versions live from the version upgrades; definitely call out the upgrades in the commit message.
   * round launcher icons -- in fact, this commit has the generic Android hello-world icons, and we should use our own with the Zulip logo instead :)
   * `module.system.haste` stuff in flowconfig -- looks like from d5e9e55fa upstream, should be fine to do in advance
   * maybe upgrade Flow? I'd like to at least try doing this separately; would give us a bit more flexibility in how we handle this.

**Comment by borisyankov** [comment]
> * Does GH recognize "Implements"? Just uniformly saying "Fixes" seems fine to me.

I don't think so
https://help.github.com/articles/closing-issues-using-keywords/

Other options 'closes' and 'resolves'.

**Comment by borisyankov** [comment]
The suggestions on splitting the upgrade sound good. Will work on that next.
The RN 0.57 is split more logically, as I had to do it manually :)

**Comment by borisyankov** [comment]
I've split the actual upgrade commit into several commits.
Also, the circular icons work was separated into #2993

**Comment by borisyankov** [comment]
If we don't upgrade to Babel 7, the `generate-webview-js` script stops working.
There is now a PR for that #2994
Safe to merge before this PR.

**Comment by gnprice** [comment]
Sounds good! Just looked at #2994; will do #2993 next, and then back to this one.

One thing I noticed on #2994 : several commits that came from this PR edited `js.js` without updating `generatedEs3.js` to match. Really this underlines how we ought to get #2690 finished and merged so that we don't need to track the generated file in version control. Until then, one thing I find handy when I'm developing a branch like this one is a command like
```
$ git filter-branch --tree-filter 'yarn generate-webview-js' upstream/master..master
```
which makes sure every commit contains exactly the change to `generatedEs3.js` that it should.

**Comment by gnprice** [comment]
> I've split the actual upgrade commit into several commits.

:+1: 

I'd love to merge the first few of those changes (updating flowconfig, Gradle version, and build tools / SDK / etc versions), if they are ready. They're only ready if they're tested, of course; and testing them, without including other changes that aren't ready to merge, begins with preparing a version that has those changes and not the other changes. I.e., using `rebase -i` to put the possibly-ready changes at the beginning of the branch.

If you believe those changes are ready to merge, would you
* rebase them to the start of the branch,
* test them -- i.e., check out each commit partway through the branch where you think all the changes are ready, and try things out,
* and push that version of the branch that has them at the front?

Then I can do some quick poking around myself, and merge them! :tada: 

A couple of quick comments from skimming these now:
* A commit message says Gradle 4.4, but the actual commit has 3.5.1.
* I really liked the reference to `react-native-git-upgrade`, and description of how you prepared these changes, in the previous version of the branch! Even though the changes are now spread out across several commits, I think that's still useful discussion to have in at least one of these commit messages -- preferably an early one, because it's easier to find an early commit from a later one than vice versa. It's also fine to repeat some of it where it applies to several commits.

For reference, that commit message was
```
Upgrade to React Native 0.56

Implements #2788

Upgrade dependencies, config and build files to RN 0.56

Previous upgrades were done manually by updating dependencies and
.flowconfig

This commit contains a full `diff` with previous versions.

What was done is:
 * run react-native-git-upgrade
 * resolve merge conflicts
 * update dependencies that were needed but missed by the script
```
and that last set of bullets is the really great info I'd like to be sure to keep; also the "previous upgrades" line for historical context.

The "Update Gradle configs" change is the one I'd most especially like the RN / `react-native-git-upgrade` context on.

* As I mentioned above, definitely call out the upgrades in the commit message where we're upgrading build tools, target SDK version, etc. Those are important substantive changes.

**Comment by borisyankov** [comment]
@gnprice I did about a dozen changes on the PRs 0.56 + 0.57
I think the majority of the commits are good to go in.

I haven't done the 'disable Flow issues first, then re-enable and add FlowFixMe` thing we discussed. Not sure if it is ideal.

I might have missed some of the things we discussed, though I went over all commits if you notice something that I've missed just a short ping to remind me is enough.

**Comment by gnprice** [comment]
Thanks @borisyankov !

* is_mentioned: It's not clear from the information in this commit message if the type definition is actually wrong (and we should fix it), or if instead the code that looks for this field is wrong (and we should fix that). Does this field actually exist in `message` events from the server?

  I don't see it in a quick grep. So it looks to me like the right fix is more likely to stop looking for that field. But presumably there's more to the story somewhere -- we must have had something in mind when writing that code. Would you try to get to the bottom of this?

* `children` type errors: it looks like my previous comments still apply. Would you respond to those?

* style issues: You mentioned in a chat message that you'd tried `DangerouslyImpreciseStyleProp` and weren't able to get that to work either. So I guess I'll poke at this myself as mentioned.

* These two comments still apply -- would you please address these? In our call and PM conversation back at the beginning of last week (Oct 1), we dug into how to handle these, and I sent you a short diff with code to do it. Please ask if there are followup questions I can answer or another way I can help.

  * handleLongPress "Fix for exception": this fix doesn't look right; what should the type of this function's parameter be? Seems like it should be `Element` or subtype; we control the call site, so we can take care of things there.
  * Aha, the `is incompatible with Node` -- I never like the term "incompatible" for this concept, and this error message illustrates why. The concept they actually mean is "is not a subtype of", which unlike "incompatible" is not symmetric. In fact the complete sentence in the error message is `Cannot call getMessageIdFromNode with e.target bound to node because EventTarget [1] is incompatible with Node [2]`, and that is absolutely correct -- `EventTarget` may be a supertype of `Node`, but it is not a subtype and an `EventTarget` can't play the role of a `Node`.

* Fix Xcode project settings warnings:
  * The upstream commit you link to has two blocks of changes like this, one for Debug and one for Release config. What's the reason to change only Debug?
  * Why is this separate from the `LastUpgradeVersion` / `LastUpgradeCheck` changes that are in a later commit, in the #2955 branch? In our conversation last week, my understanding was that those two record the fact that we've acknowledged the warnings recommending these changes.

* "Add TouchEvent types to params" -- looks good, thanks! I'll try rebasing this to the front and merging.

* "Make `getMessageNode` input and result nullable" -- looks like a good fix, thanks!

* "flow: Add MouseEvent type" -- Cool, this is a nice cleanup. The commit message is a bit misleading -- we really shouldn't be saying "flow: " when the commit changes the actual runtime logic, as this one does.

* "Update .flowconfig" -- Looks good, except the summary line is pretty vague: should mention Haste name reducers, or say something similarly specific.

* "Upgrade Gradle" -- Thanks for fixing the message! Looks good.

* "Update Gradle configs" -- I think all my feedback in the second half of my previous comment (from "I really liked ..." to the end) still applies. Would you please address that?

---

Scanning through the later commits:

* "Give a type to the containing function in `Input`" -- Is there a reason this commit wasn't rebased to the front for a quick merge? Looks like it should be compatible, if it's correct at all.

* "Import ... explicitly" -- ditto

* "Update gradle wrapper binary and scripts" -- this looks good, except it has the `android.useDeprecatedNdk` change which looks unrelated. That should be its own commit.

  * We discussed this NDK change in our conversation on Oct 1. I added some info there:

    > https://github.com/facebook/react-native/commit/6117a6c7205c969f93d39ba02e0583881572d5fa
    > [We mention the old NDK version in] `rn-from-git.md`
    > Maybe just put a line at the top of that file saying it was written for older RN versions and some details won't be right
    > Not a priority to actually update those instructions properly until we're doing the work to actually switch to that style

* OK, we have two different commits that say two different Gradle versions are the "version used by android studio 3.x and gradle plugin 3.x." That does not give me confidence that when you wrote those explanations you were actually checking that the things you're saying were true. :-/

  * Would you sort out which of these (if either) is actually right, and fix the other one to be a correct explanation?

* Then after we've upgraded to Gradle 4.4, another commit says "use Gradle 3". That doesn't seem right either. (Maybe you mean the Android Gradle Plugin?)

**Comment by gnprice** [comment]
I went and merged three of those four Flow-related commits that looked good. Thanks!

The exception was "Add TouchEvent types to params" -- this affects `handleLongPress`, so it requires the `handleLongPress` fixes discussed above. (When I try it alone, it causes an error.)

**Comment by gnprice** [comment]
> I haven't done the 'disable Flow issues first, then re-enable and add FlowFixMe` thing we discussed. Not sure if it is ideal.

So specifically, my suggestion was:
1. Disable *errors on unused suppression comments*;
2. Add the various fixmes from the back half of your branch;
3. Upgrade;
4. Re-enable errors on unused suppression comments.

I think we should do that, for the reasons I described in our call last week: it's extremely easy to do (comment out one line -- `git log --stat -p .flowconfig` and you'll see how we turned those on in the first place), and goes a long way toward not breaking things mid-branch.

If there's something I'm missing, though, I'd be glad to hear more thinking about it.

**Comment by borisyankov** [comment]
After investigation of the mysterious `is_mentioned` property, I dropped the commit in favor of #3029

**Comment by borisyankov** [comment]
> "Give a type to the containing function in Input"

This can be before the upgrade. Rebased.

> flow: Import `ReactTestRenderer` explicitly

This cannot. So left as-is.

**Comment by gnprice** [comment]
> > "Give a type to the containing function in Input"
> 
> This can be before the upgrade. Rebased.

Hmm. Did you test that, though? When I check out that commit and run `yarn flow`, I get this error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/common/Input.js:84:17

Cannot create FormattedMessage element because:
 • string [1] is incompatible with $Iterable [2] in property children.
 • string [1] is incompatible with React.Element [2] in property children.
 • string [1] is incompatible with React.Portal [2] in property children.
 • string [1] is incompatible with boolean [2] in property children.
 • string [1] is incompatible with null [2] in property children.
 • string [1] is incompatible with number [2] in property children.
 • string [1] is incompatible with undefined [2] in property children.

     src/common/Input.js
      76│     const placeholderMessage = placeholder.text || placeholder;
      77│
      78│     return (
      79│       <FormattedMessage
      80│         id={placeholderMessage}
      81│         defaultMessage={placeholderMessage}
      82│         values={placeholder.values}
      83│       >
 [1]  84│         {(text: string) => (
      85│           <TextInput
      86│             style={[styles.input, style]}
      87│             placeholder={text}
      88│             placeholderTextColor={HALF_COLOR}
      89│             underlineColorAndroid={isFocused ? BORDER_COLOR : HALF_COLOR}
      90│             onFocus={this.handleFocus}
      91│             onBlur={this.handleBlur}
      92│             ref={(component: any) => {
      93│               this.textInput = component;
      94│               if (textInputRef) {
      95│                 textInputRef(component);
      96│               }
      97│             }}
      98│             {...restProps}
      99│           />
     100│         )}
     101│       </FormattedMessage>
     102│     );
     103│   }
     104│ }

     flow-typed/npm/react-intl_v2.x.x.js
 [2] 205│       children?: (...formattedMessage: Array<React$Node>) => React$Node
```

**Comment by gnprice** [comment]
(Notes from an audio conversation with @borisyankov:)

In Boris's main dev environment right now (with Xcode 10), it takes a lot of time to switch between the front and back of the branch, with different RN versions. That makes some kinds of revisions to the branch slow and expensive for him that are much cheaper for me. (I think the biggest variable here is iOS vs Android, or possibly RN-on-iOS vs RN-on-Android in particular. A build of an RN app for iOS ends up doing a ton more work than a build of the same app for Android, for reasons I partly understand.)

Here's our plan for the next steps on this and #2955 , the RN 0.57 upgrade:
* I'll pick up the baton on the Flow fixes and Android build changes in this branch: taking what's here and revising and merging as much as I can up front.
* Ditto the two commits at the end of #2955 (`rn-fetch-blob`, and `SpinningProgressImg`); if I can't readily get them to work pre-upgrade, I'll report back.
* Boris will revise #3029 following the discussion there, and the Xcode project settings as discussed above, to try to get those merged up front too.
* That leaves the actual upgrades, and not much else. We'll re-assess what's left after making a go of the above, which is around 80% of the branch.
* When we do get to merging the actual upgrades, we'll aim to do one immediately after the other; running on 0.56 should work in principle, but Boris finds that it's flaky in his environment.

**Comment by gnprice** [comment]
On the `react-native-fetch-blob` upgrade:

I tried this one by itself. When I touched an image to get the lightbox, then went to the overflow menu and chose to download, I got a redscreen with this message:
```
notification
getValue
    ReadableNativeMap.java:122
getBoolean
    ReadableNativeMap.java:137
run
    RNFetchBlobReq.java:164
fetchBlob
    RNFetchBlob.java:352
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:790
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764
```

OK, it's a little better in the log seen through adb:
```
Exception in native call
com.facebook.react.bridge.NoSuchKeyException: notification
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
	at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:137)
	at com.RNFetchBlob.RNFetchBlobReq.run(RNFetchBlobReq.java:164)
	at com.RNFetchBlob.RNFetchBlob.fetchBlob(RNFetchBlob.java:352)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:164)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)
```

Did the forked library's API change so we have to tweak our code to use it? This *could* be somehow related to the RN upgrade, but it doesn't really look like it.

**Comment by gnprice** [comment]
On the `jest/preprocessor.js` change, I did a bit of digging to try to understand what that's doing and how it could break (how we'd know if it was breaking something).

It seems to be a bit of a messy workaround. Did you see this later comment by one of the RN maintainers? https://github.com/facebook/react-native/issues/19859#issuecomment-407748189 We do have a `.babelrc`, which this causes Jest runs to ignore. That's OK right now because the only thing we customize with it is prod... but that's fragile.

That comment suggests just renaming `.babelrc` to `babel.config.js`. If you try that, does that suffice to fix the issues that this commit was meant to fix?

**Comment by gnprice** [comment]
On the ART issue / the `SpinningProgressImg` workaround:

Thanks for this detailed commit message! Also the three reference links in it -- this is all very helpful for understanding what this is doing and why.

Replying to one bit of your explanation:

> Unfortunately, there is a serious bug on Android, that have existed for a while. Surprisingly we did not encounter this bug until RN 0.57 but it has always been there.

My reading of [this comment](https://github.com/facebook/react-native/issues/17565#issuecomment-390328526), as well as the rest of that issue (which you linked to, thanks again) is that this has always been an issue *on a `targetSdkVersion` of 25+*, aka Android 7.1+. The discussion isn't really explicit about that, but I think it's clear once you see it. See also that issue's appearance on the list at facebook/react-native#19297 .

So the reason we need to fix this is in order to bump `targetSdkVersion`. Which happens to come in the 0.56 release, but the only reason it's even happening then is that Google decided this year to force everyone to finally update.

Does that fit with the information you know? If so, that'd help us clarify the story of what this really fixes and why.

**Comment by gnprice** [comment]
Oh, one other thought on the SpinningProgressImg change:
* I think I'd much rather have this be an edit to the same file.
  * Source control is forever -- we're not in danger of losing the current code -- so just a comment about how this is a temporary substitute until `ART.Surface` works again would do just as well for helping us revert later.
  * And having code lying around that looks *just as if* it does a thing, but it's actually dead (i.e. never invoked) and there's some other code next to it that actually does the thing, is super confusing when reading a codebase. I speak from experience. :stuck_out_tongue: 
  * I'd also delete `Arc.js` and `Circle.js`; they're less dangerous to understanding than a zombie `SpinningProgress.js`, but still get in the way, and it's super cheap to just remove them. (And the `git revert` when we're ready to go back to ART will be just as effective in bringing them back.)

And I guess another thought:
* Thanks for the clear explanation in that commit message of how this design and these images were made! And identifying what functionality is lost, and why it's OK. That's all very helpful in giving me confidence efficiently that this will be a good replacement.

**Comment by gnprice** [comment]
OK, and I've pushed the `rn-cli.config.js` change, as 3011d5bd9. I added a bit more explanation from what I learned in studying it; take a look.

**Comment by gnprice** [comment]
OK, and I went and merged a whole bunch of the Gradle config updates, as the series ending at 75e9547ee.

The one thing still open there is the `targetSdkVersion` update -- which I'm not sure is necessary for the RN upgrade itself, but is certainly required if we want to publish any new releases on Google Play after the end of this month :slightly_smiling_face: . That's blocked on:
* The `SpinningProgress` commit in this branch, discussed above (and below)
* Updating our launcher icon; that's #2993 , which is on your plate
* Testing more, and reading release notes, to make sure that's it :)

I went and pushed a branch `rn-0.57` to my fork, to collect in one place (and rebased onto current master) all the work that's left. It looks like this (broken down):
```
1669c687b Fix Xcode project settings warnings
7d6e0a768 Upgraded Project settings to be compatible with Xcode 9.4
```

These are on your plate; we've discussed some edits.

```
f51a74c23 Fix: Incorrectly calculated unread mentions
```
This is #3029 , and is on your plate.

```
45b43c0c9 jest: Fix Jest tests not running with Babel 7
63465425f SpinningProgress: Replace temporarily with SpinningProgressImg
7b71304ac dependencies: Upgrade `react-native-fetch-blob`
```
These I commented on above, yesterday, so at this stage they're on your plate. As discussed in more detail above, I think the first two should be easy to revise for merge. The third, I'm more puzzled about.

```
3a64fc07a WIP android: Bump targetSdkVersion to 26.
```
Discussed at the top of this comment.

```
493ccd56f style: Use RN upstream's narrower version of an over-broad style type.
3c1167c39 style: Add fixmes for a few issues the RN/Flow upgrade turns up.
041e08968 Upgrade to React Native 0.56
d52b97552 Update Flow Typed definitions
2a3098010 Upgrade to React Native 0.57.1
d5c9577c8 Upgrade to Babel 7
c70bb1a98 flow: Remove a couple of error suppression comments
542d460e5 flow: Remove fixme-56 in `Input`.
0ecc5a4a3 ZulipSwitch: Replace component's deprecated props
43860f3c4 flow: Import `ReactTestRenderer` explicitly
```
Discussed in the previous comment; these are the same changes as in my `flow-rn0.57` branch, except I moved the #3029 change to an earlier part of the branch.

**Comment by gnprice** [comment]
Update: @borisyankov has split two pieces of this as #3041 (SpinningProgress; just merged!) and #3042 (react-native-fetch-blob; just reviewed), in addition to previously-split-out PRs mentioned above.

**Comment by borisyankov** [comment]
Not sure if clear from any comment but:
> 1669c687b Fix Xcode project settings warnings
was updated with both `release` and `debug` warnings

**Comment by gnprice** [comment]
OK, to be specific at risk of repeating myself: items on your plate, other than the ones you've split out as separate PRs, include

* The Jest commit. I had some comments and questions above: https://github.com/zulip/zulip-mobile/pull/2789#issuecomment-428420391

* The Xcode changes. I had two separate comments above: https://github.com/zulip/zulip-mobile/pull/2789#issuecomment-428035595 , of which this version responds to one of them.

Would you please address these?

**Comment by borisyankov** [comment]
I am going through these, in the meanwhile, I went through the commits that update `yarn.lock` and rerun `yarn` with the latest version to ensure `integrity hashes` are included.

**Comment by borisyankov** [comment]
I worked on this:
> The Jest commit. I had some comments and questions above: #2789 (comment)

I remember reading it before, but now I went through in detail on everything that was discussed and issues that were linked to.

I spent few hours on trying to make a `babel.config.js` and it isn't working. It seems it can work with a lot more messing with configuration and plugins etc. but I don't think it is worth it.

**Comment by borisyankov** [comment]
A couple of hours more on this issue, suggest that several people found the solution:
```
"transform": {
  "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
},
```
works fine for them.

**Comment by borisyankov** [comment]
Squashed the two XCode commits and updated the commit message.
Also rebased onto `master`.

**Comment by gnprice** [comment]
And merged! :confetti_ball: Thanks @borisyankov for all your work on this :smile:

**Pull request merged**
