### PR TITLE
WebView rendering of MessageList

### PR DESCRIPTION
**Pull request by borisyankov**
Not 100% match feature-wise with current implementation.

Advantages: any message that is heavy-html+css is trivially implemented, and already a lot of it is supported, while in native implementation is hard and requires a lot of effort and overhead.

Rendering 5000 messages to string takes about 20-30msecs, adding them in the WebView and rendering is rather fast (by the underlying system), but hard to benchmark.

Memory-wise - my guess is orders of magnitude more efficient. Has to measured for a definitive answer.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by neerajwahi** [comment]
Thanks @borisyankov. Excited to compare this solution to the ScrollView.

It's hard to evaluate right now for the following reasons:
- The scroll position is not maintained as more data is fetched (meaning that we constantly jump to the beginning of the stream) -- this is critical for the real app
- There are no sticky headers (which I would like to see because I believe they will be difficult to make performant with a WebView)
- The scroll speed is too low and not comparable to a UIScrollView (this setting can be changed, see http://stackoverflow.com/questions/14763255/why-does-scrolling-a-uiwebview-feel-so-much-different-than-scrolling-any-other)

Could you update the diff to address the above?

**Comment by neerajwahi** [comment]
@borisyankov the WebView doesn't seem to be fetching more data as I scroll

**Comment by borisyankov** [comment]
I think last commit contains a bug. Will push an update soon.

**Comment by neerajwahi** [comment]
Thanks again for this putting together. As discussed, we're going to stick with the native ScrollView (at least for now).

**Pull request closed without merging**
