### PR TITLE
dependency: Update react-native-vector-icons to v5.0.0.

### PR DESCRIPTION
**Pull request by jainkuniya**
As https://github.com/oblador/react-native-vector-icons/pull/693 got
released in v5.0.0.

Fix: #2209

### CODE REVIEW

**Comment by gnprice** [comment]
This comes out pretty badly broken for me:

image

That's after `yarn` and `react-native run-android`.

Does it work right for you? Thoughts on what the issue might be?

Also this is the kind of PR that would definitely benefit from screenshots :)

**Comment by gnprice** [comment]
Hmm. Something's wrong, I think, if `react-native link` is a step that everyone has to repeat, instead of a step that you do as part of preparing a commit that works for everyone.

---
Some notes which may help in figuring that out:

Your latest version adds something interesting -- it adds some fonts to the Android assets, also edits some others, and it edits the Xcode metadata to refer to the same new fonts:
```
 android/app/src/main/assets/fonts/EvilIcons.ttf              | Bin 13128 -> 13456 bytes
 android/app/src/main/assets/fonts/Feather.ttf                | Bin 55288 -> 65112 bytes
 android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf    | Bin 0 -> 116280 bytes
 android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf   | Bin 0 -> 40416 bytes
 android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf     | Bin 0 -> 168176 bytes
 android/app/src/main/assets/fonts/Ionicons.ttf               | Bin 143936 -> 112472 bytes
 android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf | Bin 292556 -> 373772 bytes
 android/app/src/main/assets/fonts/Octicons.ttf               | Bin 27512 -> 27440 bytes
 ios/ZulipMobile.xcodeproj/project.pbxproj                    |  13 ++++++++++++-
 ios/ZulipMobile/Info.plist                                   |   5 ++++-
```
However, when I run from just this commit, I still get a messed-up set of icons -- diffferent from above, but still wrong.

Then if I run `react-native link react-native-vector-icons` (in an Android dev environment), I get basically this change:
```
 android/app/src/main/assets/fonts/EvilIcons.ttf              | Bin 13456 -> 13128 bytes
 android/app/src/main/assets/fonts/Feather.ttf                | Bin 65112 -> 55288 bytes
 android/app/src/main/assets/fonts/Ionicons.ttf               | Bin 112472 -> 143936 bytes
 android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf | Bin 373772 -> 322456 bytes
 android/app/src/main/assets/fonts/Octicons.ttf               | Bin 27440 -> 27520 bytes
```

Which changes two of those fonts (or three? not sure about Feather) *back*:
```
$ git di @^^ --stat android/
 android/app/src/main/assets/fonts/Feather.ttf                | Bin
 android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf    | Bin 0 -> 116280 bytes
 android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf   | Bin 0 -> 40416 bytes
 android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf     | Bin 0 -> 168176 bytes
 android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf | Bin 292556 -> 322456 bytes
 android/app/src/main/assets/fonts/Octicons.ttf               | Bin 27512 -> 27520 bytes
```
and makes yet different changes to two others, leaving the three new fonts alone.

And after that, it works.

**Comment by borisyankov** [comment]
It seems the latest version of the library is '6.1.0' now...

**Comment by jainkuniya** [comment]
Oh! Will update

**Comment by gnprice** [comment]
This PR has been stale for a while. I think most likely the easiest way to make a clean fix for this issue will be to approach the upgrade again fresh, so let's close this PR.

**Pull request closed without merging**
