### PR TITLE
homescreen_icon: Swap All-Messages icon from 'globe' to 'list'.

### PR DESCRIPTION
**Pull request by dootMaster**
to match mobile's All Messages icon with the one found in web Zulip.

Previous Mobile:
Screen Shot 2022-07-30 at 5 41 14 PM

Browser:
Screen Shot 2022-08-19 at 8 19 26 PM

Update Mobile:
Screen Shot 2022-08-19 at 5 57 20 PM

Fixes: #5303

### CODE REVIEW

**Comment by dootMaster** [comment]
@chrisbobbe @alya @gnprice 

> Thanks, [@dootMaster](https://github.com/dootMaster)!
> One nit: the web app uses Font Awesome for this icon, and this PR would use Feather.
> The difference is pretty small; the order of short and long lines is just reversed: 
> But we might as well use exactly the same icon while we're making this change.

I noticed the new list icon from the FontAwesome collection doesn't quite match the aesthetic of the rest of the icons. The lines are bolder. What do ya'll think?

**Comment by dootMaster** [comment]
One solution would be to to invert the old Feather list icon via the transformY in the style prop.

**Comment by dootMaster** [comment]
Here's what I came up with:
Screen Shot 2022-08-23 at 6 55 15 PM


I did this by swapping back to Feather in the makeIcon function and passing in `[(scaleY: -1)]` to the transform inside the `TopButtonGeneral` component.

**Comment by chrisbobbe** [comment]
> One solution would be to to invert the old Feather list icon via the transform in the style prop. I'm going to try it and post the result.

Huh, interesting! Sure, that seems fine.

**Comment by gnprice** [comment]
Agreed -- @dootMaster, I'd be glad to see a version of this PR that does what you showed in that last screenshot :slightly_smiling_face:

**Pull request closed without merging**
