### PR TITLE
Fixes #475: Entire button is selectable

### LINKED ISSUE #475: Entire button on the log in screen is not selectable
When logging in, the user is prompted to enter the server URL. The button for "Enter" is supposedly the entire green area, but actually it does nothing when tapped on the green area. It only works when the user taps the text "Enter". The same happens for the following screens where you have to enter the username and password.

### PR DESCRIPTION
**Pull request by saketkumar95**
Fixes: https://github.com/zulip/zulip-mobile/issues/475
Now the  Entire button is selected whenever pressed.

### CODE REVIEW

**Comment by borisyankov** [comment]
You need to fix that inside the ZulipButton component, which already uses a 'Touchable' component.

**Comment by borisyankov** [comment]
Also, be aware of linting errors. Install an eslint plugin in your IDE/editor or make sure to run:

```
npm run test:lint
```

**Comment by saketkumar95** [comment]
@borisyankov Done! :)

**Comment by borisyankov** [comment]
We want to preserve the use of `TouchableNativeFeedback` but we want to fix it.
This one is the animation where circle that expands.

**Comment by borisyankov** [comment]
@saketkumar95 any update on this?

**Comment by saketkumar95** [comment]
@borisyankov Will solve this today. Busy in my universities exams. :)

**Comment by borisyankov** [comment]
No problem. Thanks ;)

**Comment by borisyankov** [comment]
Do we really want to have two touchables wrapping each other? I suspect that the inner one can be just a `View` and it will still work. Will you try that?

**Comment by saketkumar95** [comment]
@borisyankov `TouchableHighlight` was looking fine so i added that. :P 
It will work with `view` i already tried that. Should i update the PR with a view then? :)

**Comment by borisyankov** [comment]
We definitely prefer View (which is a general-purpose component) vs extra Touchabe-something.

**Pull request closed without merging**
