### PR TITLE
WIP: Combine downloadFile and shareImage, android & iOS files.

### PR DESCRIPTION
**Pull request by jainkuniya**
part of #3018

### CODE REVIEW

**Comment by borisyankov** [comment]
Get these files out of the `/api/*` directory, as we want to make it general and independent of our project. These calls depend on `react-native`.

**Comment by gnprice** [comment]
Thanks @jainkuniya ! I just merged the first of these commits (the one not marked WIP.)

In the second commit, what generated the files that appear in android/app/ -- was that from using Eclipse? I'm curious about your experience; in general my recommendation for doing work in Java or in Android build config and resources is to use Android Studio.

**Comment by gnprice** [comment]
Also I agree with Boris that these files belong outside `api/`. That's best done as a separate commit from this change, though -- best after it, I think, among other things so there's just one of each file to move.

**Comment by borisyankov** [comment]
Already done in the API PR, the commits are:

https://github.com/zulip/zulip-mobile/pull/2819/commits/1691091b9a40675013bfd5408b074f273744161d

https://github.com/zulip/zulip-mobile/pull/2819/commits/d30a4e8c0c22768ba1c8502dd264fefe3b327354

**Comment by gnprice** [comment]
Great :)

**Comment by gnprice** [comment]
(That's #2819, for the sake of not having to look that up more than once.)

**Comment by jainkuniya** [comment]
@gnprice 

> was that from using Eclipse?

I haven't used Eclipse. I prefer Eclipse only for pure Java development. Wondering how that got added. 🤔

**Comment by gnprice** [comment]
Closing the remaining part of this PR -- this went stale for a while, and now #3018 is complete.

**Pull request closed without merging**
