### PR TITLE
Changed UI for Subscription status for `All streams`

### PR DESCRIPTION
**Pull request by thisisnitish**
Fixes: #4658

Hey @chrisbobbe!,

* I've tested the functionality and it is working, though it took so much time but I was able to complete. It would be a great help if you take a look at that.
* Here, I've used `Pressable` component of `react-native` instead of `TouchableOpacity`, because, when I looked into the docs there was not any prop named `disabled` for `TouchableOpacity`. So, I thought, may be `Pressable` would be a great choice.
* I will change the variable names, once the review will be done.
* Also, It would be great help if you could give me the idea of size of the icons, because when I looked into the [Switch](https://github.com/facebook/react-native/blob/main/Libraries/Components/Switch/Switch.js) component of `react-native`, there was no any reference of size of the `Switch` component.

**Below is the preview:**

https://user-images.githubusercontent.com/48220369/162817634-6f331475-c506-4241-b371-219ba48c5412.mp4

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Thanks! Continuing from [chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4658/near/1364807), where you said

> My concern was, whether I'd taken the right approach or not. So, I wanted you to take a very thorough review of this.

Here are some initial thoughts:

- @alya, do you have feedback about the size and shape of the plus and check icons? I think I'd personally prefer if the shapes weren't on a circular background; I like the example of the podcast app in https://github.com/zulip/zulip-mobile/issues/4658#issue-857274958 but maybe that's just me.
- You've documented the `disabled` prop with this: `@prop [disabled] - If set the component is not switchable and visually looks disabled.` I don't think that behavior (giving a distinct appearance when disabled) is implemented, is that right?
- I like the idea of using `Pressable`. One thing it lets you do, which we like, is fade the button while your finger is on it, so you know it's responding to touch. You can look at our other uses of `Pressable` to see how we do this.
- There are a few things that still refer to a "switch", including the jsdoc on the `disabled` prop (quoted above), the `showSwitch` prop, and more. Those will cause confusion to future readers that don't find the "switch" that's referred to, so we should change them so they don't say "switch".

**Comment by alya** [comment]
> @alya, do you have feedback about the size and shape of the plus and check icons? I think I'd personally prefer if the shapes weren't on a circular background; I like the example of the podcast app in https://github.com/zulip/zulip-mobile/issues/4658#issue-857274958 but maybe that's just me.

Agreed, these icons don't look great to me, and I think plain checkmarks/pluses would look better.

One reference point we have is the streams management UI in the web app:
Screen Shot 2022-04-12 at 3 00 54 PM

Note that in the webapp, a grey checkmark appears on hover, and you can click it to subscribe. (Of course, we can't quite do the same thing on mobile. ;))

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!,
I've made some changes based on your suggestions:

> * @alya, do you have feedback about the size and shape of the plus and check icons? I think I'd personally prefer if the shapes weren't on a circular background; I like the example of the podcast app in [#4658 (comment)](https://github.com/zulip/zulip-mobile/issues/4658#issue-857274958) but maybe that's just me.

So, for this one, I've changed the icon, as you said not to use circular icons. So, again I move to the `react-native-vector-icons` and found from `FontAwesome` and used it. Please have a look once. I hope those icons will be fine.

> * You've documented the `disabled` prop with this: `@prop [disabled] - If set the component is not switchable and visually looks disabled.` I don't think that behavior (giving a distinct appearance when disabled) is implemented, is that right?

Umm, Sorry for that, actually I tried to understand what role `disabled` prop is playing here and I kind of realised that It isn't playing any role....may be I could be wrong. If you can give me some idea that what is the working of disabled, then it would be a great help. This is the only reason, I've added `disabled` prop here. 

> * I like the idea of using `Pressable`. One thing it lets you do, which we like, is fade the button while your finger is on it, so you know it's responding to touch. You can look at our other uses of `Pressable` to see how we do this.

Yeah!, I checked in our codebase where we have used `Pressable` and tried to add the feedback when we press the button. Also if you look at the stream `nitish-testing-1`, you will get the clear idea for that.

> * There are a few things that still refer to a "switch", including the jsdoc on the `disabled` prop (quoted above), the `showSwitch` prop, and more. Those will cause confusion to future readers that don't find the "switch" that's referred to, so we should change them so they don't say "switch".

Yeah!, I've changed from switch to some meaningful variable names, you can review the code. Also, the reason why I haven't done previously, because I wanted you to review it thoroughly and then I'll change the name. I've already mentioned here

From the first comment:
> I will change the variable names, once the review will be done.

Now, I think, I've done all the changes as you asked me to do except the `disabled` prop. This one still confuse me so, if you can give me some idea or thoughts, then It would be a great help. The reason I've added `disabled` prop here because in `ZulipSwitch` component is also using `disabled`. So, I thought, may be this would be a necessary prop and also as I mentioned I wasn't able to understand the `disabled ` prop clearly.
Hope it clears everything 😊

**Below is the preview, Please have a look at that:**

https://user-images.githubusercontent.com/48220369/163260709-e7b9fcc3-5695-491c-af09-762c83dc84f1.mp4


Thanks 😊

**Comment by gnprice** [comment]
Discussion thread in chat: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4658.20subscription.20UI.20in.20streams.20list/near/1366266

**Comment by thisisnitish** [comment]
Hi @chrisbobbe!, I've added the disabled appearance to the `Pressable` component. In order to do this, I just had to add the `opacity` value to the style prop of `Pressable`, when `disabled` is `true` make it `0.5` otherwise `1 (default)`. 

Actually, I looked into the react native documentation for [Switch](https://github.com/facebook/react-native/blob/main/Libraries/Components/Switch/Switch.js) component. I was looking for what `opacity` value they use for `disabled` prop but there was not any reference.  So, I thought of using `0.5` as an `opacity` for `Pressable` component when `disabled` will be `true`.

**Here is the Preview:**
* When `disabled` is `true`.
Simulator Screen Shot - iPhone 12 - 2022-05-03 at 00 12 05

* When `disabled` is `false`.
Simulator Screen Shot - iPhone 12 - 2022-05-03 at 00 41 50

I hope this will be fine. Thanks 😊

**Comment by chrisbobbe** [comment]
Thanks for the revision and the screenshots! For review, please make sure your PR branch is tidy. No commit should contain regressions or choices we've decided against. In this case, I think that should start by squashing all three commits into one.

The lines in those check and plus icons look pretty thick to me, compared with the example Alya gave in https://github.com/zulip/zulip-mobile/issues/4658#issue-857274958. Could you try Feather icons? We've already got an `IconDone` that uses Feather. I think 24 is a good size for the icon.

I don't expect `'#ffffff'` (white) to work as the icon's color in light mode, since the background is white, or nearly white, too. I think `color` from our `ThemeContext` might be a sensible choice, but it'd be good to see screenshots in dark and light modes to be sure.

Did you have a reason in mind for making a separate `ZulipSubscribe` component? The job we're asking it to do is so specific that I think we're unlikely to want to reuse its code. I think I'd just skip making a new component, which adds maintenance cost (like maintaining a jsdoc) and put the JSX inline. But if you have a reason for wanting to make a new component, please mention it.

**Comment by thisisnitish** [comment]
Hey @chrisbobbe!, I've squashed the commits and made some changes based on your suggestions. Please have a look at that.

>* The lines in those check and plus icons look pretty thick to me, compared with the example Alya gave in https://github.com/zulip/zulip-mobile/issues/4658#issue-857274958. Could you try Feather icons? We've already got an IconDone that uses Feather. I think 24 is a good size for the icon.

Done.

>* I don't expect '#ffffff' (white) to work as the icon's color in light mode, because the background will be white, or nearly white, too. I think color from our ThemeContext might be a sensible choice, but it'd be good to see screenshots in dark and light modes to be sure.

I've tried to fix this one and tried to implement as you asked me. I've added the preview below with both dark and light mode. Please take a look. I hope this will work 🤞🏻.

>* Did you have a reason in mind for making a separate ZulipSubscribe component? The job we're asking it to do is so specific that I think we're unlikely to want to reuse its code. I think I'd just skip making a new component, which adds maintenance cost (like maintaining a jsdoc) and put the JSX inline. But if you have a reason for wanting to make a new component, please mention it.

So, when I started to work on this issue, I realised that the component which is used in implementing this feature is `ZulipSwitch` and there is a high chance that we might use `ZulipSwitch` component later in future. Also, `ZulipSwitch` by the name it feels something like `Switch` component. And, we know, having `Switch` in any sort of mobile-app or web-app is very common and we might use it in future. So, I decided not to alter the code in `ZulipSwitch` component. Then, I thought of implementing a new component for this.

**Here is the preview:**

* Just, not to waste your time: Please take a look at stream `A test stream` 5th from top. I hope you will get the idea.

https://user-images.githubusercontent.com/48220369/166520198-37cac3f5-862a-4ecd-9982-56162bf1d473.mp4


* When `disabled` is true.
Simulator Screen Shot - iPhone 12 - 2022-05-03 at 23 08 57

* When `disabled` is false.
Simulator Screen Shot - iPhone 12 - 2022-05-03 at 23 08 34


I hope this clears everything. Thanks 😊

**Comment by chrisbobbe** [comment]
> So, when I started to work on this issue, I realised that the component which is used in implementing this feature is `ZulipSwitch` and there is a high chance that we might use `ZulipSwitch` component later in future. Also, `ZulipSwitch` by the name it feels something like `Switch` component. And, we know, having `Switch` in any sort of mobile-app or web-app is very common and we might use it in future. So, I decided not to alter the code in `ZulipSwitch` component.

This all makes sense. I agree that we don't want to change the `ZulipSwitch` component.

> Then, I thought of implementing a new component for this.

There's another way, which I mentioned above:

> I think I'd just […] put the JSX inline.

More concretely, this approach would mean removing the `<ZulipSwitch … />` in StreamItem.js, and replacing it directly with a `<Pressable … />` with all the props and children it needs.

**Comment by thisisnitish** [comment]
Sure @chrisbobbe! I got it, how can I miss this 😞. Every time I try to think of a simpler solution, but at the end you suggests something more simpler than mine. This shows, I still have to learn a lot and there is a long way to go.

By the way, @chrisbobbe!, I'll be implementing directly `Pressable` in `StreamItem.js` and will let you know. Hope this time it will work. Thanks 😊

**Comment by thisisnitish** [comment]
Also, @chrisbobbe!, I just noticed, the checks are failed. I don't why, because before committing I ran `tools/test` and it worked, there was no errors as such. If you could suggest some reason for this, then It would be a great help. Thanks 😊

**Comment by chrisbobbe** [comment]
Following links from that checks-failed notice in GitHub, here's the output of the `native` suite, which is what's failing:

```
Running native...
Running Android native tests...
Using expo modules
— expo-application (3.3.0)
— expo-constants ([12](https://github.com/zulip/zulip-mobile/runs/6295482555?check_suite_focus=true#step:7:12).1.3)
— expo-error-recovery (3.0.5)
— expo-file-system ([13](https://github.com/zulip/zulip-mobile/runs/6295482555?check_suite_focus=true#step:7:13).0.3)
— expo-font (10.0.5)
— expo-keep-awake (10.0.2)
— expo-modules-core (0.4.10)
— expo-screen-orientation (4.0.3)
— expo-sqlite (10.1.1)
— expo-web-browser (9.3.0)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-community_cameraroll'.
> Could not resolve all artifacts for configuration ':react-native-community_cameraroll:classpath'.
   > Could not download stax-ex-1.7.7.jar (org.jvnet.staxex:stax-ex:1.7.7)
      > Could not get resource 'https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7.jar'.
            > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 2m 47s
```

That looks like a network failure from trying to contact jcenter, so it's unrelated to your changes. I'd expect it to resolve on its own after some time. I've just asked it to rerun, hopefully it'll work this time. But again, your changes didn't cause this failure. 🙂

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe!, I was hoping for this 😊. By the way, Please have a look at the changes that I've made. Thanks 😊

**Review by chrisbobbe — CHANGES_REQUESTED** [review]
Thanks, this is getting closer! See a few small comments, below. Greg will be back from a vacation on Monday, and I'd like to give him a chance to review too, just to let you know. 🙂

To see the disabled appearance a bit better, I think it's helpful to see a mix of some that are disabled and some that aren't, in the same list, like so:

 

The disabled and non-disabled states are pretty hard to distinguish, for me. Here's a thought: what if we represent the disabled state—the cannot-subscribe state—as just not showing a button at all?

If you want to simulate different possible states and see how it looks, you can temporarily hard-code some values, or get a dev server set up where you can be an admin, as Greg explained [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.23M4658.20subscription.20UI.20in.20streams.20list/near/1367879).

**Comment by thisisnitish** [comment]
> The disabled and non-disabled plus signs are pretty hard to distinguish, for me. Here's a thought: what if we represent the disabled state—the cannot-subscribe state—as just not showing a button at all?

Sure @chrisbobbe!, we can give it a try. I'll do it and let you know. Thanks 😊

**Comment by thisisnitish** [comment]
Hi @chrisbobbe!, Sorry for the delay. I've PMed you the reason for this. By the way, I've done the work as you asked me to do. Please have a look at that. Below is the preview.

Just have a look at `Nk private stream`

Simulator Screen Shot - iPhone 12 - 2022-05-08 at 23 33 12
Simulator Screen Shot - iPhone 12 - 2022-05-08 at 23 33 25


Here is the video for your better reference:
* Here, I've shown you with 2 streams. One is private and one is public one.
* `Nk private stream` (9th from top) is a private stream and `nitish-testing-1` (8th from top) is a public stream.
* Now, when you unsubscribe from the private stream then you should not be able to see the icon.
* But, when you unsubscribe from the public stream then you should be able to subscribe later whenever you want.

https://user-images.githubusercontent.com/48220369/167311446-c5a47e61-c021-4fca-9837-745f221af742.mp4


I hope It will be clear to you. Thanks 😊

**Comment by chrisbobbe** [comment]
Thanks, @thisisnitish! I showed this to Greg in our office, and he suggested still showing the plus icons when disabled, instead of hiding them, as I'd suggested—but that they should be more faded than they were in your revision 36c3831. And he also suggested that the disabled plus signs should respond to presses by alerting the user with a message saying why they can't subscribe to the stream (i.e., because it's private).

To help avoid going back and forth again, I've gone ahead and pushed a revision that does all that. @gnprice, would you take a look? 🙂

Here are screenshots from this revision:

 

And a video showing the error alert:

https://user-images.githubusercontent.com/22248748/168945602-41ec51bd-357e-4125-889c-68397e005ec5.mp4

**Comment by thisisnitish** [comment]
Thanks @chrisbobbe! for the revision. Thanks a lot. 😊

**Comment by alya** [comment]
Do you guys think we should change the webapp to use the faded `+` sign approach? Seems like it would be clearer there as well.

**Comment by chrisbobbe** [comment]
> Do we have any other places in the mobile app where we pop up a message telling the user that they can't do something? I'm just trying to think about consistency in phrasing/formatting/etc.

Makes sense. Here's a good approximation for the other places we do. The first argument passed to `showErrorAlert` (before the comma) is the alert title; the body is the second argument. Please let me know if I can clarify anything. I already see some inconsistencies, e.g., sometimes we use a period in the body and sometimes not.

```
$ git grep -e 'showErrorAlert\('
src/account/AccountPickScreen.js:          showErrorAlert(_('Failed to connect to server: {realm}', { realm: realm.toString() }));
src/chat/ChatScreen.js:            showErrorAlert(_('Failed to edit message'), error.message);
src/chat/ChatScreen.js:          showErrorAlert(_('Failed to send message'));
src/compose/ComposeBox.js:      showErrorAlert(isEditing ? _('Message not saved') : _('Message not sent'), msg);
src/compose/ComposeMenu.js:        showErrorAlert(_('Error'), _('Camera unavailable.'));
src/compose/ComposeMenu.js:        showErrorAlert(_('Error'), errorMessage);
src/compose/ComposeMenu.js:      showErrorAlert(_('Error'), _('Something went wrong, and your message was not sent.'));
src/compose/ComposeMenu.js:        showErrorAlert(_('Error'), e);
src/message/fetchActions.js:    showErrorAlert(
src/sharing/ShareWrapper.js:      showErrorAlert(_('Message not sent'), msg);
src/streams/CreateStreamScreen.js:        showErrorAlert(_('A stream with this name already exists.'));
src/streams/CreateStreamScreen.js:          showErrorAlert(error.message);
```

That one in `fetchActions` is multiple lines:

```js
    showErrorAlert(
      // TODO: Set up these user-facing strings for translation once
      // `initialFetchAbort`'s callers all have access to a `GetText`
      // function. As of adding the strings, the initial fetch is dispatched
      // from `AppDataFetcher` which isn't a descendant of
      // `TranslationProvider`.
      'Connection failed',
      (() => {
        const realmStr = getIdentity(getState()).realm.toString();
        switch (reason) {
          case 'server':
            return getIsAdmin(getState())
              ? `Could not connect to ${realmStr} because the server encountered an error. Please check the server logs.`
              : `Could not connect to ${realmStr} because the server encountered an error. Please ask an admin to check the server logs.`;
          case 'network':
            return `The network request to ${realmStr} failed.`;
          case 'timeout':
            return `Gave up trying to connect to ${realmStr} after waiting too long.`;
          case 'unexpected':
            return `Unexpected error while trying to connect to ${realmStr}.`;
          default:
            ensureUnreachable(reason);
            return '';
        }
      })(),
    );
```

**Comment by chrisbobbe** [comment]
> Do you guys think we should change the webapp to use the faded `+` sign approach? Seems like it would be clearer there as well.

No objections from me.

**Comment by chrisbobbe** [comment]
> For the error message, let's use `#stream-name` rather than `"stream-name"`. We could also consider linking to https://zulip.com/help/stream-permissions, maybe from a "Learn more.".

Makes sense! Revision pushed, with that change.

**Comment by chrisbobbe** [comment]
> edit: Oh, oops—I haven't done the "Learn more" part; will do in a minute.

Done; revision pushed. Here's a screenshot:



Also, did you mean https://zulip.com/help/stream-permissions specifically? How about `<realm>/help/stream-permissions`, to get the version of the doc for the server the user is on. E.g., https://chat.zulip.org/help/stream-permissions, for CZO.

**Comment by gnprice** [comment]
This looks good to me! @chrisbobbe, feel free to merge. Thanks to both you and @thisisnitish :slightly_smiling_face:

**Comment by chrisbobbe** [comment]
Thanks for the review, Greg, and thanks again, @thisisnitish! Merged.

**Comment by thisisnitish** [comment]
YAY! 🎉

**Comment by thisisnitish** [comment]
YAY! 🎉, Thanks @chrisbobbe , @gnprice , @alya 😊

**Comment by alya** [comment]
I filed #22217 for making the webapp UI look like the UI we came up with here.

**Pull request merged**
