### PR TITLE
message-edit: Close edit mode on back button press.

### PR DESCRIPTION
**Pull request by jainkuniya**

### CODE REVIEW

**Comment by borisyankov** [comment]
I noticed this issue and it is good to work on it!
But I I think you are too specific. This does not happen only on 'Back' but also on 'Forward' - as in, you open the info screen of a stream while you've focused the compose box.

First, search inside React Navigation documentation and issues for a good solution.

**Comment by gnprice** [comment]
Hmm, good catch on the issue. This fix looks pretty brittle, though. Why do we need this special case?

If the existing logic is wrong in this case, I suspect it's wrong in some other cases too. I'd rather work out what it is we're really trying to say here, and write the logic to match that.

**Comment by borisyankov** [comment]
I also don't think this is the right place for the logic.

We need some more generic 'things that are cancellable by going back'.

**Comment by borisyankov** [comment]
Actually, I think the 'Edit Message' functionality is an example of 'logic in the wrong place'.
Any time we add a feature by 'if'-ing in unrelated place should be a warning sign.

**Comment by jainkuniya** [comment]
> Any time we add a feature by 'if'-ing in unrelated place should be a warning sign.

Yup!

Before I start rework on this.
Let's discuss what behaviour we want.
Option 1) If user is in edit mode, change back button to cross icon and hide other options in the nav bar (info button etc). On pressing back button, cancel edit mode.
Option 2) Maintain normal flow, while user is in edit mode, he can go forward (in the  narrow info screen), but on back button dismiss edit mode. (Which I guess it better from mobile perspective).
Just checked webapp supports multiple message editing and maintain edit compose box even after changing narrow.

Slack follows the first one (except changing it to cross icon.)

**Comment by borisyankov** [comment]
I tested out Slack and it behaves as if the 'Edit Message' screen is a new navigation route.
That also works great with the `Back` functionality by default.

We may not want to recreate a whole screen (or we might produce a slightly differing `Chat` one).
If we can use some functionality that makes it create a route but just changes a state in our view, that might be optimal.

**Comment by borisyankov** [comment]
I like the animated features that I think we can merge independently of the 'Edit' changes.

The Edit feature should really be reworked as a new navigation route and then we will simplify the `if`s inside the `ComposeBox` and we'll not need to add custom `if`s to the `Back` functionality.

**Comment by jainkuniya** [comment]
Submitted #2717 fro the animation feature.

For the new navigation route, let's discuss the layout.
Whether is should be same as our chat route, or only contains a full screen input for editing message?

**Comment by borisyankov** [comment]
With React Navigation V2 it has to be a different route ID.
We would likely want to combine this with some (quick) refactor of the `ComposeBox` component.

**Pull request closed without merging**
