### PR TITLE
deps: Use patch-package to fix Xcode build failure in react-native

### PR DESCRIPTION
**Pull request by chrisbobbe**
This gets the effect of facebook/react-native@52d8a797e but without having to upgrade to RN v0.69.

I believe this is the first time we've used patch-package. It's a band-aid, but at least I think an effective one, while we focus our time on the Flutter project.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Oops, I forgot a key part of this: updating our postinstall script so `patch-package` actually runs 😄

**Comment by chrisbobbe** [comment]
OK, pushed with that fix.

**Comment by gnprice** [comment]
Cool, seems best ­— thanks for working this out. Merging.

**Comment by chrisbobbe** [comment]
Thanks!

**Comment by chrisbobbe** [comment]
By the way I tested a `yarn` command and `patch-package` did its job, adding three lines to the output:

```
patch-package 6.5.1
Applying patches...
react-native@0.68.5 ✔
```

**Pull request merged**
