### PR TITLE
developer guide: Add debugging section.

### PR DESCRIPTION
**Pull request by roberthoenig**
@gnprice it'd be cool if you could add your adb shell debugging workflowto this section once this is merged.

### CODE REVIEW

**Comment by gnprice** [comment]
Also just pushed a commit which adds those `adb logcat` instructions. Please try it out! And mention in the stream if it works for you, or if it doesn't, or send a PR if something's unclear.

I'm not sure it has any particular advantages over the JS console, once you get the latter going. Maybe if you're using a physical Android device it would be hard to get the JS console working? Not sure how it'd work exactly. If so, `adb logcat` could be helpful for that.

(As I reread my ADB instructions, I'm not sure they help at all if you haven't already used ADB for something. I think standard ADB setup instructions on the web should fill in the gap, but if you find yourself searching for and using those, I'd be glad to take a PR to add appropriate links and/or other advice.)

**Comment by roberthoenig** [comment]
Thanks for the doc clarifications! I agree with every change but this one:

> - To use it, start your app.
> + To use it, start your app in the emulator.

I haven't tried it out myself yet, but the react docs suggest that you can just as easily use the remote js debugger with a physical device. Maybe we can make the line more explicit by saying smt like
> To use it, start your app in the emulator or on your physical device.

**Comment by roberthoenig** [comment]
I find the adb instructions helpful, especially the `adb logcat -T 100 | grep ReactNativeJS`.

For my part, I was familiar with adb, but didn't know about logcat and that you could also use it to debug console.log messages. Also, things break, so it's probably better two point out two tools than just one.

**Comment by gnprice** [comment]
Thanks for the fact-check!

> I haven't tried it out myself yet, but the react docs suggest that you can just as easily use the remote js debugger with a physical device.

Huh, I didn't see that, and it's not obvious to me how that'd work (how would the device talk to the browser on the host?)

But then I searched in the page for "device", and there's [this other section](https://facebook.github.io/react-native/docs/debugging.html#debugging-on-a-device-with-chrome-developer-tools) at the bottom, with instructions. I'll edit to point at that.

**Pull request merged**
