### PR TITLE
Use clipped views optimisation on both platforms.

### PR DESCRIPTION
**Pull request by Sam1301**

### CODE REVIEW

**Comment by Sam1301** [comment]
Up for review. This solves significant memory issues on iOS and android. Now the number of views on screen remain the same as the users scrolls through message list. Please test changes in release configuration to see the perf improvements ;)

**Comment by borisyankov** [comment]
Looks good. Is there a resource online that you used for the code? An article?
We might want to link to it.

**Comment by Sam1301** [comment]
The changes to android code is inspired from this block in RN scrollview https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java#L75. (Basically I wanted to know how to gain access to package private fields). I have added to ref to this line in the code.

**Comment by borisyankov** [comment]
Cool. Let's try it in practice then, I'll release a new Beta on the store later today.

**Pull request merged**
