### PR TITLE
Add marginTop to dev account list

### PR DESCRIPTION
**Pull request by kunall17**
simulator screen shot 18-sep-2017 2 42 44 pm

### CODE REVIEW

**Comment by borisyankov** [comment]
What if we put it inside a `FlatList`?

**Comment by kunall17** [comment]
Yeah but I don't think there would be a very significant improvement of performance as already there are only 7-8 items in this list!

**Comment by borisyankov** [comment]
You are right. No need for FlatList.

I landed a rework of how `Screen` works in general. There is a chance this auto-resolves this. Please, give it a try. If not, rebase/rework this one and I'll merge this.

**Comment by kunall17** [comment]
Nope doesn't fix simulator screen shot 19-sep-2017 11 47 51 am

**Comment by borisyankov** [comment]
I'll merge this then, when you rebase 👍

**Comment by kunall17** [comment]
@borisyankov Something is going wrong on the current master, the text in the DevAuthScreen (Administrators & Normal users) are not visible as well!

**Comment by kunall17** [comment]
@borisyankov Updated with flatList!

**Comment by borisyankov** [comment]
Cool. I guess any way of implementing it is OK, as long as it works :)

**Pull request merged**
